### ISSUE TITLE
 Columns use full typed value to sort regardless of format string

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#1013]
**Small description**
I have noticed that if I have full dates 2019-07-08 20:47:05 that I type to `date`, add the format `%H:%M:%S`, then try and sort, the original date value is used.

**Expected result**
I would expect to be able to sort by the hour/given format string.

N.B. I get why this happens, but I wanted to log it here as a potential issue and an example of how I use the sorting and date functionality

**Comment by saulpw** [comment]
Thanks for filing the issue, @geekscrapy.  This is by design, as you noted.  I think the 'fix' is to find a way to freeze the column with its formatted values instead of its typed values, and then you could sort by that.  This might just be a new freeze command.  I'll make it a wishlist item.  Kondo'd for now.
