### ISSUE TITLE
case insensitive search in C-h help to find things more easily

### ISSUE THREAD

**Issue by simonmichael** [saulpw/visidata#1015]
`/` (search) in the C-h help is case sensitive. As an emacs user I'm not used to that, I guess it's standard pager behaviour. I need to figure out how to case-insensitively search C-h, as it's kind of an essential survival doc. less seems to require that you start it with -i or -I. Perhaps it would be a better default if vs started the pager in that mode.

**Comment by simonmichael** [comment]
Though, with all the case-sensitive keybindings (z vs Z), case-sensitive search might be needed at times (more by experienced users, I think). 

Whichever is the default, if there is a way to select the other kind of search when needed, that would be pretty useful, and possibly worth mentioning at the top of the help.

**Comment by simonmichael** [comment]
From https://serverfault.com/questions/11736/gnu-less-how-can-i-search-while-ignoring-case-sensitivity-without-using-less-i : 

While in less, pressing `-` `i` toggles partial case insensitivity: any all-lower-case search term will match case insensitively.

Pressing `-` `I` toggles full case insensitivity: any search term will match case insensitively.

(In both cases, less displays "(press RETURN)"; this is to clear the mode line only, and not required.)

**Comment by saulpw** [comment]
Hi @simonmichael, thanks for the request and research.  On my platform (Linux) the search is case insensitive, and I don't appear to have any special `PAGER` set or anything.  You may want to try setting `PAGER="less -i"` outside of VisiData and seeing if that gets you the behavior you want.  Otherwise you may just have to use the workaround you found within man/less.
