### ISSUE TITLE
Plugin help

### ISSUE THREAD

**Issue by ECon87** [saulpw/visidata#1019]
Hi,

I am trying to build my own plugin. But the available resources/examples are a bit too complicated for me to use as a jump-off point. So I decided to start with a simple example in order to familiarize myself with the process.

Specifically,  I want to print the current column's name, but the following code does not work. I would appreciate any hints on how to fix it.

`from visidata import Sheet, Column, TableSheet, BaseSheet, asyncthread, copy, warning, Progress, vd

@Column.api
def get_values(col):
    vd.status(col.name)

BaseSheet.addCommand('1', 'get-value', 'get_values()')
`

The following error is returned:

`NameError: name 'get_values' is not defined`.

If I replace "@Column.api" with "@Sheet.api", then it works (i.e., it returns me the sheet name).

I guess my question is: how  can I add a command that only works on a specific column?

Thanks

Update: 

The following seems to work as a first step

```
@Column.api
def get_values2(col):
    vd.status(col.name)

@Sheet.api
def get_values(sheet):
    vd.status(get_values2(sheet.cursorCol))

BaseSheet.addCommand('1', 'get-value', 'get_values()')
```

**Comment by ajkerrigan** [comment]
Hiya @ECon87 - closed or not this feels like a good question/discussion :).

In case it's useful at all for your plugin work, your example can also be written as:

```
@Column.api
def get_values(col):
    vd.status(col.name)

BaseSheet.addCommand('1', 'get-value', 'cursorCol.get_values()')
```

Because the intent is to target the active column, that seems pretty reasonable.

You already referenced the [plugin docs](https://github.com/saulpw/visidata/blob/77b2c3ee73aeb16a25a9cc08eeff0c53800b6467/docs/api/extensible.rst), but it can also be helpful to peek at existing plugins to see how they're structured and called.

For example the [vfake](https://github.com/saulpw/visidata/blob/77b2c3ee73aeb16a25a9cc08eeff0c53800b6467/plugins/vfake.py) plugin that comes with VisiData is a nice example of a column-focused command, while jsvine's [dedupe](https://github.com/jsvine/visidata-plugins/blob/cd721bc2dca49b533d0b1f643f4e87a0bf4503b6/plugins/dedupe.py) is a good example of a sheet-focused one.

Ifyou want to kick plugin ideas around, there are folks [in IRC](https://github.com/saulpw/visidata#help-and-support) or the [discussions](https://github.com/saulpw/visidata/discussions) section here who will happily chat :). Happy authoring!

**Comment by ECon87** [comment]
Hey @ajkerrigan,

Thank you for the response and the suggested resources. I will definitely visit the IRC and the discussion forms.

**Comment by ghost** [comment]
I would also recommend starting _at the beginning_ of the API docs, and working your way through the examples.
I spent a week banging my head against a wall, because I skipped to the section I thought I needed, and didn't understand some of the things explained in the first couple of sections!

https://www.visidata.org/docs/api/index.html

**Comment by saulpw** [comment]
I'm sorry to hear that it was so frustrating, @davidwales!  What did you get stuck on?  Do you think it would help to put some links in places later on, too?

**Comment by ghost** [comment]
Thanks @saulpw! I've somewhat documented the process in [this discussion question](https://github.com/saulpw/visidata/discussions/984).

The main issue was that my mental model of columns was incorrect, so I kept reading the [Sheets](https://www.visidata.org/docs/api/sheets.html) and [Columns](https://www.visidata.org/docs/api/columns.html) pages and not fully understanding what was happening!

Things started to click for me when I went back to the start and read the page on [Loaders](https://www.visidata.org/docs/api/loaders.html). I haven't updated the discussion question with my latest understanding yet, but I realised I probably need to create a Loader rather than just trying to push data into a new Sheet. (Things started working a bit better when I did that!) I also realised that columns don't really exist in visidata. (I was trying to create columns directly from lists. However, I think I am supposed to create rows, then columns are views into those rows.)

**Comment by saulpw** [comment]
I'm so sorry, @davidwales, I completely missed your discussion!  I'm glad you figured it out, and you're right, that is pretty foundational.  Maybe make it clear in the sidebar that a few pages are "essential".  Anyway, please do update the discussion with your latest findings and questions, and I'll see if I can't figure out how to turn on email notifications for Discussions.

**Comment by daviewales** [comment]
Thank you @saulpw. :) I really love visidata. To be honest I was rushing, because I have a toddler and not much time for coding at home! (And we haven't got an open source policy at work yet... hopefully soon!)

But it might be good to put a note on the Columns page telling people to go back and learn the basics first!
