### ISSUE TITLE
Calling `Control-^` on single-sheet instance raises error

### ISSUE THREAD

**Issue by jsvine** [saulpw/visidata#102]
## Specs

- VisiData v0.99
- Python 3.6.0
- MacOS
- Terminal.app

## Observed Behavior

When calling `Control-^` ("jumps to previous sheet (swaps with current sheet)") on a single-sheet instance, VisiData raises " IndexError: list index out of range".

Full error, via `Control-e`:

```
Traceback (most recent call last):
  File "[[redacted]]/site-packages/visidata/vdtui.py", line 1110, in exec_command
    exec(cmd.execstr, vdglobals, LazyMap(self))
  File "<string>", line 1, in <module>
IndexError: list index out of range
```

It seems to make sense — if there's only one sheet, there's no previous sheet — but it's a bit unexpected.

## Example

- From the VisiData git repo, run `vd sample_data/surveys.csv`, then press `Control-e`. When I do that, I get this:

![screen shot 2018-01-06 at 8 02 20 pm](https://user-images.githubusercontent.com/534702/34645501-281ff4b0-f31d-11e7-978b-2d0753d0dcaa.png)

## Questions

- Do you see the same behavior?
- Would it be possible to replace that error message with a more descriptive one? (E.g., maybe "No previous sheet"?)

**Comment by saulpw** [comment]
Yup!  Reasonable error messages are good to have, and adding them is usually all but trivial (see 993c0a7 with the fix for this issue).  I haven't added too many of them proactively, because there are a thousand corner cases, and I personally don't mind if the wires are exposed.  I've mostly added nice error messages only when the default error message is confusing to me.  But feel free to call out more of these, or submit PRs if you like!  Especially for common errors and novice mistakes.

**Comment by jsvine** [comment]
Thanks! And good to know about the approach re. error messages. Now that I see how they're added, I'll submit a PR next time I'm keen to have one added.
