### ISSUE TITLE
Cannot cancel long running aggregators

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#1036]
When used on large sheets, if an aggregator is use on a process intensive column, its calculation (when SHIFT+F is used) cannot be cancelled and don't show progress.

I added this a feature request as I know we talked to aggs and async before, but I thought they were still cancellable.

**Comment by anjakefala** [comment]
This is a good, specific performance-experience suggestion @geekscrapy.

**Comment by saulpw** [comment]
I'm not sure this totally addresses your issue, @geekscrapy, but I refactored so that now there's a `sheet.loading` boolean variable, and aggregators aren't calculated until sheet.loading has completed (and then they'll be cached).  This removes the performance problem that comes from aggregators applied to large groupings, at the cost of not showing any aggregator values until loading has stopped (either completed or canceled).  I feel like this satisfies the spirit of this issue, since you can cancel a freq table with aggregators without any performance issues.

If there's a different performance issue that hasn't been addressed, please file a new issue with a more detailed set of steps that highlights the issue.
