### ISSUE TITLE
After typecasting, frequency tables still reflect underlying text

### ISSUE THREAD

**Issue by jsvine** [saulpw/visidata#104]
VisiData version: 0.99

## Observed behavior

Frequency tables appear to reflect cells' original text, rather than their typecast representation, yielding somewhat surprising results.

## Example

The one-column dataset `ones.csv` contains the following:

```
x
001
01
01
1
```

Opening that file in `vd` and casting the `x` column to an integer (using `#`) yields this, as expected:

```
 x  #‖
   1 ‖
   1 ‖
   1 ‖
   1 ‖
```

But running a frequency table on that column results in this, which (while understandable what's happening) is somewhat unexpected:

```
 x  #‖ count  #| percent  %| histogram                                        ‖
   1 ‖       2 |     50.00 | *                                                ‖
   1 ‖       1 |     25.00 |                                                  ‖
   1 ‖       1 |     25.00 |                                                  ‖
```

In a frequency table, I'd expect only one entry per typecast value, rather than one entry per underlying value. But perhaps I'm overlooking an important trade-off?

Example dataset and cmdlog here: 
[ones.zip](https://github.com/saulpw/visidata/files/1618976/ones.zip)

**Comment by saulpw** [comment]
So there are 3 different values: the underlying value, the typed value, and the display value. Would you want the frequency table to group based on the typed value, or the displayed value?  If the format string is changed (like if you format the date as %Y-%m) should that affect the grouping?  This seems desirable to me.

But what about the 'distinct' aggregator, then?  The aggregator is given a list of typed values, which is necessary for a consistent aggregator architecture and to accurately handle null values.  Should the number of distinct values match the number of rows in the Frequency/Pivot table?

For that matter, should all null values be grouped together?  i.e. None, 0, False, and empty string.  What about errors?  I think errors should remain on the Frequency Table, but should they all be grouped together, or grouped by error type?

**Comment by jsvine** [comment]
> Would you want the frequency table to group based on the typed value, or the displayed value? If the format string is changed (like if you format the date as %Y-%m) should that affect the grouping? This seems desirable to me.

Ah, yes, that sounds ideal.

> But what about the 'distinct' aggregator, then? The aggregator is given a list of typed values, which is necessary for a consistent aggregator architecture and to accurately handle null values. Should the number of distinct values match the number of rows in the Frequency/Pivot table?

My gut instinct is yes, but I may be overlooking downsides to that. What'd be the argument against this?

> For that matter, should all null values be grouped together? i.e. None, 0, False, and empty string.

I don't think so. In the datasets I work with, `None`, `0`, `False`, and empty string often signify (within the same dataset) different things.

> What about errors? I think errors should remain on the Frequency Table, but should they all be grouped together, or grouped by error type?

I don't have a strong opinion on this. For troubleshooting's sake, though, it seems slightly preferable to have them grouped by error type.

**Comment by saulpw** [comment]
> What'd be the argument against [the number of distinct elements matching the number of rows in the frequency table]?

Sorry, that was an implied counter-argument to using the displayed value for the frequency grouping.  The aggregators all have the same interface, which for the numerical aggregators (sum, avg, etc), needs to be the typed value.  So if we use the displayed value for the frequency grouping, then the number of distinct elements could be surprisingly different, e.g. when the displayed value loses precision.  I'm thinking that the usefulness of using the displayed value for the frequency table outweighs the contradictory behavior of 'distinct'.

> In the datasets I work with, None, 0, False, and empty string often signify (within the same dataset) different things.

Sorry again, I meant "whatever things are null values", based on the "_is_null" options.  By default only "None" counts as null, but if you have e.g. `zero_is_null` also set to true, it seems like you'd want both None and 0 to be counted in the same 'null' frequency bin (which is not what happens currently).

**Comment by saulpw** [comment]
These changes (using display value for freqtbl and pivot grouping) should go into v1.1.  I'm leaving the null and error behavior alone for now.

**Comment by jsvine** [comment]
Thanks, @saulpw! That's great. 

---
p.s.:

> Sorry again, I meant "whatever things are null values", based on the "_is_null" options. By default only "None" counts as null, but if you have e.g. zero_is_null also set to true, it seems like you'd want both None and 0 to be counted in the same 'null' frequency bin (which is not what happens currently).

Heh, I think we may be talking on slightly different wavelengths here. I actually would prefer both `None` and `0` to be counted *in separate bins*.

What I meant to say, but did not communicate clearly: In many datasets I work with, `None` and `0` (and the empty-string, for that matter) often denote, within the same dataset, different things ... and it'd be great if VisiData preserved that difference. It sounds like it already does, yeah?

**Comment by saulpw** [comment]
Yeah, there's a lot going on here, and several implicitnesses (implicities?).  VisiData does not group None/0/''/False together except:

1. when considering nulls
   a. which happens on the Describe Sheet (in the nulls column);
   b. or filtering nulls from values given to aggregators
 2. even then, they are only considered 'null' if the corresponding `none_is_null`, `zero_is_null`, `false_is_null`, or `empty_is_null` are set.

So the current behavior on the Frequency and Pivot sheets, is to put them each into separate bins (as you prefer).  This is regardless of the `*_is_null` options.

My proposal was to make the null behavior more consistent, and use those `_is_null` options to also determine grouping behavior on Frequency and Pivot sheets, such that all 'null' things would be in a single bin.  But because only `none_is_null` is set by default, the default behavior wouldn't change for you (except that `None` would probably be labeled `null`).

So for the datasets where None/0/False/'' are separate values, it would already act like you want.  If ever you had a dataset where e.g. both '' and/or 0 were used to indicate "no measurement", and you wanted to aggregate the values for all 'no measurements' into the same bin, then you could use the `zero_is_null` and `empty_is_null` options to do so, just like you can already use those options to exclude them from the set of values given to aggregators like `avg`.  This may not be a common case, but it would make things more consistent, and it seems like a consistent 'null' story is something that every data package needs.

**Comment by jsvine** [comment]
So interesting, and such helpful insight into VisiData's internals. Thanks! Your proposal makes a lot of sense and sounds good.
