### ISSUE TITLE
[loader-json] Columns with __ are duplicated for each row when --clean-names is True

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#1058]
**Small description**
Columns with a double underscore as the key get duplicated

**Expected result**
For columns with a double underscore to only be shown once like other columns

**Actual result with screenshot**
Actual:
![image](https://user-images.githubusercontent.com/11225502/126990172-568c2e8a-dd51-4880-bdde-a642b68c1cd6.png)

Expected:
![image](https://user-images.githubusercontent.com/11225502/126990257-ef650030-5f1b-482a-88e0-d8011d56e864.png)

**Steps to reproduce with sample data and a .vd**
```json
{
    "objects":[
        {
            "col1": "col1a",
            "_col2": "col2 value a",
            "__col3": "valueA"
          },
          {
            "col1": "col1b",
            "_col2": "col2 value b",
            "__col3": "valueB"
          },
          {
            "col1": "col1c",
            "_col2": "col2 value c",
            "__col3": "valueC"
          },
          {
            "col1": "col1d",
            "_col2": "col2 value d",
            "__col3": "valueD"
          },
          {
            "col1": "col1e",
            "_col2": "col2 value e",
            "__col3": "valueE"
          }
    ]
}
```

load with `pbpaste | vd -f json`

**Additional context**
v2.6dev

**Comment by ajkerrigan** [comment]
Hey @geekscrapy, I'm trying to reproduce this locally and seeing the expected results. Any chance you've got something in a plugin or .visidatarc that may be getting tripped up? Do you see the same behavior if you use `pbpaste | vd -f json --config=/dev/null`?

**Comment by anjakefala** [comment]
We should maybe add that to our bug report checklist, @ajkerrigan!

**Comment by geekscrapy** [comment]
Got it: `pbpaste | vd -f json --config=/dev/null --clean_names=True`

**Comment by geekscrapy** [comment]
> We should maybe add that to our bug report checklist, @ajkerrigan!

Can we add this to the issue creation template too?

**Comment by frosencrantz** [comment]
@geekscrapy if you do find the cause of the duplicate columns I would like to know what you find.

I've seen something similar, but haven't had time to track it down.

**Comment by geekscrapy** [comment]
FYI I'm running with this modification for now if anyone wanted to try it out:

visidata/loaders/json.py
```python
        for k in row:
            k = maybe_clean(k, self)        # This is the new line @ 73
            if k not in self._colnames:
                self.addColumn(ColumnItem(k, type=deduceType(row[k])))
        return row
```

Are there any other loaders in which the columns are added per row like JSON?

*Edit*
- geojson
- vcf
- xml

**Comment by frosencrantz** [comment]
For my data, it is not related to the clean-names being on.  It appears related to JSON, and it might even be this code, but the suggested fix does not help.

**Comment by geekscrapy** [comment]
Can you share a sample of the data that does not work for you? What format is it?

**Comment by frosencrantz** [comment]
The problem lines are the ones that @geekscrapy found in: https://github.com/saulpw/visidata/issues/1058#issuecomment-895833174

The column that was duplicated was from a JSON fieldname that contained a newline '\n'.  Visidata must be cleaning that up, but then the matching in those code fails, and it adds the column multiple times.

Thanks @geekscrapy for finding the issue!

**Comment by geekscrapy** [comment]
> The problem lines are the ones that @geekscrapy found in: [#1058 (comment)](https://github.com/saulpw/visidata/issues/1058#issuecomment-895833174)
> 
> The column that was duplicated was from a JSON fieldname that contained a newline '\n'. Visidata must be cleaning that up, but then the matching in those code fails, and it adds the column multiple times.
> 
> Thanks @geekscrapy for finding the issue!

So this works for your dataset? I was under the impression from https://github.com/saulpw/visidata/issues/1058#issuecomment-899122549 that it didn't work for you?

**Comment by frosencrantz** [comment]
Visidata is broken for my original dataset.  However, I don't need the column name to include the newline, that was a bug in my code that filtered the data.  It was not intentional to include the newline in the fieldname.

Also, your fix from #1058 did not help for the broken dataset.  I did not look at what is happening to the column name cleaning when a column name contains newline.

**Comment by geekscrapy** [comment]
Ok, if you open a normal (not broken) dataset, does this patch work for you?

The patch is designed to stop multiple columns being created for the duplicate keys, not to fix issues with JSON key name formats 👍

**Comment by frosencrantz** [comment]
You found the core issue:
  - those lines are adding the extra columns.
  - the column name doesn't match the actual JSON field name.
  - the comparision fails, and adds the extra columns one per object.
 
There might be multiple ways the name is being cleaned.  I don't use clean_names, mostly because I didn't know.

I think your patch doesn't break other data.  But I only tried it for a limited time.  So your fix seems like a partial fix.

**Comment by saulpw** [comment]
This is a great find, @frosencrantz and @geekscrapy, thanks for digging on it.  These checks for existing columns should be checking based on `col.expr` instead of `col.name`, as `expr` reflects the underlying (raw) column index, whereas `name` is officially internal to VisiData.  In addition, drilling down into the rows of a JsonSheet actually pushes a ListOfDictSheet, which does its own checking for existing keys.

We don't want every loader to have to think about `maybe_clean`, so the Column does the cleaning itself.
