### ISSUE TITLE
Mention on install page the requiremnet to install openpyxl if I want to read xlsx files

### ISSUE THREAD

**Issue by halloleo** [saulpw/visidata#1090]
I wanted to look at XSLX files in VisiData, but got an error in `vd`.

The reason is that `vd` needs `openpyxl` installed. However the documentation to the default python install (`pip install visidata`) does not mention this - while the VisiData introduction talks freely about opening xlsx files with `vd`.

So it would be good to mention that `pip install openpyxl` is needed after the VisiData install if I want to read XSLX files.

**Comment by anjakefala** [comment]
Thanks for filing an issue! =)

We mention the dependencies required for supporting formats here: https://www.visidata.org/docs/formats/.

The https://visidata.org/install page then mentions `These packages all support csv, tsv, fixed-width text, json, and sqlite, at minimum. Packages often support additional formats.` I will add a hyperlink to the formats page in that sentence, and mention that additional dependencies will likely need to be installed.

If you have feedback for the introduction to VisiData, please make an issue here! https://github.com/jsvine/intro-to-visidata/issues It would be helpful if you linked to the specific place you would like that information to be added. Some packages actually would not actually need manual installation of `openpyxl`, because it will come pre-installed (this applies to the debian one, as an example).

We are actually not directly affiliated, and cannot make direct changes to it.

**Comment by halloleo** [comment]
Fair enough. 

Great that you add on the [install page](https://www.visidata.org/install/) a pointer to the format page! :-)

BTW, thanks for all the work on VisiData. It's great!
