### ISSUE TITLE
~2 orders of magnitude slowdown when loading large file structured vs. unstructured

### ISSUE THREAD

**Issue by wjv** [saulpw/visidata#113]
First of all, great tool! It’s going to see a lot of use in my line of work!

I’m loading a 10GB [VCF file](https://samtools.github.io/hts-specs/VCFv4.3.pdf) from local SSD into `vd` 1.0 (Python 3.6.4) on a mid-2014 retina MacBook Pro /w 16GB RAM (macOS 10.13.3). The file contains just over a million lines in ~2500 tab-separated columns.

Due to the VCF’s headers, `vd` doesn’t recognise the file as tabular and loads it into a single column. The async load takes 30.3 seconds by my timing. Stripping the headers and splitting the remainder of the file on `\s+` are both near-instantaneous. Great!

_However:_ Stripping the same file of its headers _first_ (so that `vd` would recognise it as tsv) and then piping it to `vd`…

    grep -v '^##' <vcf_file> | vd

…took over 20 **minutes** to load. (I didn't time it exactly.) Upon inspection, it turns out the `python3.6` process is using ~70GB of virtual memory during the load. It did eventually complete successfully (after I came back from lunch!) so there's no trace to attach.

**Comment by saulpw** [comment]
The .tsv parser splits each of the lines into separately allocated field strings; this split takes time (especially with 2500 columns!), and the additional memory usage would be expected as well.  When that goes above your 16GB RAM and has to use virtual memory, it would necessarily start taking a lot longer.

~10GB of that 70GB used is due to piping the data into stdin; the internal PathFd object saves every read line so that the whole thing can be reloaded if necessary.  We could cap this to something reasonable, like 10k or 100k lines (or set via option), to save those 10GB (and hopefully some of the time).

The fundamental problem is that 10GB is at the upper limit of what VisiData can handle with the current "load everything into memory" strategy.  Do you need to load the whole file in the first place?  At any point you can press ^C to abort the load thread, which will keep the rows already loaded into memory.

I have plans to support terabyte-size datasets, by not loading the entire file into memory.  But that will not be ready for 1.1.  If I may ask, what is your actual workflow with this data?  Are you just moving/searching, or aggregating, or filtering, or creating computed columns?  Do you need to save the result afterwards?

**Comment by wjv** [comment]
Hi Saul, and thanks for responding

To answer your last question first: “I’m not sure yet.” I’ve only been playing with VisiData for a few days and it’s clear that it will be hugely useful, but I have yet to integrate it into my workflow. Also, my workflow varies day by day. At a guess, I’d say that merely moving/searching would be a lot of what I (or my colleagues) would do, followed by filtering, creating computed columns and aggregating.

Working with genome data often means working with terabyte-scale files. Common workflows usually include manipulating files with the usual sed/grep/awk suspects, as well as a menagerie of custom tools suited to our file formats (bcftools, bedtools, … Python modules like PyVCF, etc., etc.) Eventually, once the raw data has been filtered/combined to highlight whatever one wishes to focus on, statistical analyses are usually undertaken in R, or the Python/NumPy/Pandas stack.

My intuition is that VisiData may significantly speed and simplify that *initial* analysis where you’re still coming to grips with the data, and usually (after multiple ad hoc filters and munges) end up with a multi-terabyte directory full of altered copies of bits of the original files. :)

I should also note that actual analyses would likely not take place on a laptop with constrained RAM but rather on shared servers with considerably more memory. So *in practice* the 70GB memory requirement is not an immediate roadblock. It just seemed odd to me (and arguably “a bug”) that loading the file first and then splitting it uses vastly different system resources compared to doing both at the same time.

I’m looking forward to the future enhancements you mention. Any improvements on working with large files would make VisiData more useful to someone working on genome-scale bioinformatics. Meanwhile I’m evangelising to my colleagues in-house, and it will be interesting to see the extent to which it is adopted — especially by those research scientists who are not necessarily technically inclined.

**Comment by saulpw** [comment]
Thanks for this information, @wjv, it's very helpful.

> It just seemed odd to me (and arguably “a bug”) that loading the file first and then splitting it uses vastly different system resources compared to doing both at the same time.

Well, it is kind of a trick: when you add a column, the splitting does not happen across the entire file at that time, but is computed as necessary.  So you would incur the time later, if you use commands that touch every row, like sort, aggregate, filter, save, etc.  And notably, by default you would also incur the cost for every command afterwards, unless you use `z'` to setup a cache on the current column (or `gz'` for all columns).
