### ISSUE TITLE
SQLite databases with invalid unicode not supported

### ISSUE THREAD

**Issue by WesleyAC** [saulpw/visidata#1156]
**Small description**

Opening a SQLite database will fail when a cell in a TEXT column has invalid unicode characters

**Expected result**

Either the specific cell that has invalid unicode is not imported, or it is imported but the invalid characters are stripped or slash-escaped.

**Actual result with screenshot**

![error screenshot](https://user-images.githubusercontent.com/5001092/137644252-3474128c-52be-40cb-89bb-6b13498169d7.png)

![error screenshot](https://user-images.githubusercontent.com/5001092/137644398-e3b388e3-ebfe-476e-94b3-ede0a418223f.png)

(those are errors from two different DBs that I've seen this problem on)

**Steps to reproduce with sample data and a .vd**

Here's a SQLite file that has this problem: https://hack.wesleyac.com/test.sqlite

**Additional context**

`vd --version`: `saul.pw/VisiData v2.4`

dbcli/litecli#89 is a similar issue in a different python project, which may have useful context for fixing this

**Comment by anjakefala** [comment]
Thanks so much for filing this bug report! Both the issue you linked to and `test.sqlite` were really helpful. :blush: 

On `develop` branch, we expanding `--encoding` so that it now applies to the sqlite loader. So `vd test.sqlite --encoding='latin-1'` will work. 

Unfortunately, we have the same tension as the issue you located in that we cannot decode or mark as errors individual specific cells, due to my understanding of `sqlite3` limitations. So, what we added is the ability to use alternative decoders when working with sqlite db.

**Comment by WesleyAC** [comment]
Thanks! This will be really useful :)

> Unfortunately, we have the same tension as the issue you located in that we cannot decode or mark as errors individual specific cells, due to my understanding of `sqlite3` limitations. So, what we added is the ability to use alternative decoders when working with sqlite db.

What do you think about the possibility of using [sqlite3.Connection.text_factory](https://docs.python.org/3/library/sqlite3.html#sqlite3.Connection.text_factory) to do something cleverer in terms of encodings, like `lambda x: x.decode("utf-8", "backslashreplace")`? IIUC, that should handle cases where most but not all of the strings are unicode more cleanly than just falling back to latin-1.

**Comment by anjakefala** [comment]
@WesleyAC I re-opened to look into it! Currently, I do not understand the `backslashreplace` fix, but I will read up on it.

**Comment by saulpw** [comment]
We have `options.encoding_errors` which we can use there as well.
