### ISSUE TITLE
Trying to delete a column when there are none causes IndexError

### ISSUE THREAD

**Issue by aldanor** [saulpw/visidata#116]
This is really a minor thing I noticed, if you press `-` multiple times to delete all columns, next time you press it will cause an `IndexError`.

Also, in the directory browser mode, does it ever make sense for the `name` column to be deletable?

**Comment by saulpw** [comment]
Hi @aldanor, thanks for reporting this issue.  There are many places where VisiData just relies on Python exceptions instead of constructing a meaningful error message.  I've chosen to add explicit messages only in cases where it is confusing why the command didn't work.  In this case, however, the failure seems pretty straightforward.

Ultimately I'm thinking that each command could have a 'precondition' which would return True or a clean status about what the user would need to do to enable the command.  This would help a couple of things, including making a general mechanism for edge cases like this, that don't involve overly complicating the command execstrs.

**Comment by saulpw** [comment]
As for your second question, I can't think of a reason why someone would want to hide the `name` column on the DirSheet, but I've learned to not add code to disable functionality.  There have been enough times that I've made things more complicated to prevent what I thought was improper usage, only to come back a few months later and wish that the functionality was still there.  This is a guiding philosophy of VisiData and one of the reasons it is so powerful.

Also note that a column hidden with `-` is not actually deleted, but merely has its width set to 0.  You can unhide it by changing the width in the `C`olumns Sheet.
