### ISSUE TITLE
What to do when visidata freeze? (often happen with bigger dataset) 

### ISSUE THREAD

**Issue by Awannaphasch2016** [saulpw/visidata#1160]
**Small description**
usually visidata freeze when I send some command (for example, it freezes because I open new frequency sheets) 

**Expected result**
not freeze

**Steps to reproduce with sample data and a .vd**
dataset is  2.312841 GB.

**Additional context**

visidata version = saul.pw/VisiData v2.6.1

**Comment by frosencrantz** [comment]
Can you type `Ctrl-T` so that you can see active threads?

**Comment by saulpw** [comment]
Hi @Awannaphasch2016, we need some more details to help figure out what's going on.

1. What does it mean for VisiData to "freeze"?  Does it stop responding to all commands, and for how long?  Does this happen right away or after some amount of time?
2. Do other programs on your computer continue working just fine while VisiData appears to be frozen?
3. What OS are you running on?  How much memory does your computer have?

A lot of effort has been put into making VisiData so that it doesn't become non-responsive for an extended period of time.  It still might, sometimes, in some extreme edge cases; for example, trying to reload thousands of files at once, or using `c` to search for a column in a dataset with thousands of columns.  (I think both of these have been addressed but I'm sure there are others still laying around).

The example you gave, opening a Frequency Sheet with a 2.3GB dataset, does not cause VisiData to freeze for me.  It goes straightaway to a new Frequency Sheet and starts tallying up the results.  There may be some lagginess but it's not 'frozen'.  So there's either a misunderstanding of what it means to 'freeze' (a second or two of delayed response might be unavoidable), or the datasets you're using have a particular quality that is relevant.

One thing you might want to try, is setting `options.min_memory_mb=100`.  This will use `free` (Linux/macos only) to show available memory on the statusbar, and stop processing if it ever goes below 100MB.  This might be useful to stop VisiData from consuming all available memory when it's doing a lot of processing.

I'm going to close this issue for now because it's too vague to be actionable, but if you reply with more details about specific datasets and commands you're using, and the experience you have, we can re-open it or create a new one that's more specific.
