### ISSUE TITLE
CSV without headers & replay with different files

### ISSUE THREAD

**Issue by niko** [saulpw/visidata#118]
I'm trying to use a cmd log on multiple CSV files without headers. The first problem was: Commands are bound to the sheet name. I solved this by using STDIN to load the data. Next problem: Commands are bound to column names. And the column names are derived from the first row as the CSV files I have don't have headers. Is there anyway to name columns by position?

**Comment by saulpw** [comment]
Hi @niko, sorry for the delay, it's been a hectic couple of days for the 1.1 release.

I need to fix the issue in which commands are bound to a specific sheet name.  I'm glad you found a workaround for now.

The column names in the .vd should be specifiable by number instead of name; in fact, if they aren't named, it should use numbers for them automatically.  I'm guessing that the bigger issue has to do with #97, that you used `--header 0` to specify no headers, but that option is not saved in the cmdlog for the replay.

As a workaround, if you have a saved cmdlog.vd with improper column names, you should be able to replace the column names with their number (0-indexed) manually, and the replay will try the column field as a number when the column name isn't found.

I hope to fix both of these issues in v1.2.

**Comment by niko** [comment]
Thanks for the hint with the numbered colors.

I found out the playing a cmd log on stdin doesn't seem to work at all: "FileNotFoundError": [Erno 2] No such file or directory: stdin". I'll open a separate issue.
