### ISSUE TITLE
[save-selected] default save filename is not valid

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#1180]
**Small description**
When doing a `save-selected` the default sheet name is invalid, see the screenshot below

**Expected result**
For the suggested file name to be valid and useable. Maybe something like '`sheet1_sheet2_.csv`'.

**Actual result with screenshot**
![image](https://user-images.githubusercontent.com/11225502/140711890-afa742c8-0927-4d79-ab51-c06a54dcdb89.png)

**Steps to reproduce with sample data and a .vd**
Open a number of sheets, go to `sheets-stack` select a few and do `save-selected`. This gives a stringified list rather than a proper name.

**Additional context**
Commit: https://github.com/saulpw/visidata/commit/9ce048d0378de0211e53f1591d79c8fbed39dff1

This seems to work:
`IndexSheet.addCommand('g^S', 'save-selected', 'vd.saveSheets(inputPath("save %d sheets to: " % nSelectedRows, value="_".join(vs.name or "blank" for vs in source)), *selectedRows, confirm_overwrite=options.confirm_overwrite)', 'save all selected sheets to given file or directory')`

**Comment by geekscrapy** [comment]
While looking at this, I was interested to see there is some ambiguity in the saver functionality when it comes to saving multiple files, for example:

- For savers that are not capable of embedded sheets (e.g. csv, as opposed to xlsx), there are no indications to the user they should provide a directory, rather than a single file. Only a full trace exception.
- When saving to a directory, you cannot specific a filetype? Unless by `option.save_filetype`?

Question: Should all `save_foo` methods be capable of taking multiple sheets? If the path is a dir, they save each sheet within it, if it is a full path, it should `vd.fail("cannot save multiple sheets to a single file")`

**Comment by anjakefala** [comment]
https://github.com/saulpw/visidata/commit/a5aa0da3935cb77eac81e72ca66d4467983164c6

**Comment by anjakefala** [comment]
The original documented issue has been fixed on `develop` here: https://github.com/saulpw/visidata/commit/a5aa0da3935cb77eac81e72ca66d4467983164c6! 

The

> vd.fail("cannot save multiple sheets to a single file")

bugfix when given a single file for multiple non-embedded sheets is in this PR: https://github.com/saulpw/visidata/pull/1188

This issue is remaining open for @geekscrapy's expanded comment about `options.save_filetype`, though maybe that should be moved to its own issue.

**Comment by anjakefala** [comment]
Hi @geekscrapy! An additional change is that now the `options.save_filetype` has been moved to `'tsv'` by default, and will confirm that the user wants to save in tsv, if they are over-writing an existing file. We are going to close this issue for now, since the primary core issue has been addressed, and please open others, or comment in others, for further polishing of format save behaviour!
