### ISSUE TITLE
[batch mode] When batch mode (-b) is used on a DirSheet, keycols aren't saved

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#1181]
**Small description**
Obscure, but I think valid! The columns `directory` and `filename` are not output when batch mode (`-b`) is used.

**Expected result**
For the Sheet to be output the same as when the save feature is used in interactive mode

**Steps to reproduce with sample data and a .vd**
`vd --config=/dev/null ~/Downloads -o - -b --save_filetype=csv`

If you use the following to un-keycol `directory` and `filename` columns, it works as expected.

`vd --config=/dev/null ~/Downloads -o - -b --play unkeycol.vd --save_filetype=csv`

unkeycol.vd
```
sheet	col	row	longname	input	keystrokes	comment
global		save_filetype	set-option	csv		
			open-file	~/Downloads	o	
Downloads	filename		key-col		!	toggle current column as a key column
Downloads	directory		key-col		!	toggle current column as a key column
```

**Additional context**
Commit: https://github.com/saulpw/visidata/commit/9ce048d0378de0211e53f1591d79c8fbed39dff1

**Comment by anjakefala** [comment]
Thanks for such a wonderful, wonderful bug @geekscrapy!

If you followed the party in freenode #visidata, you would have seen that this bug was due to the draw cache for self.keyCols not being cleared. When you ran a `.vd`, the cache would clear between commands, and the key columns would show up in the output.

For the `-b -o` case I added a cache clear in the `saveSheets`, so it will clear before saving. This is on `develop`, and will be in the next release.
