### ISSUE TITLE
Allow opening .csv.gz, .tsv.gz, etc. from URLs

### ISSUE THREAD

**Issue by theosanderson** [saulpw/visidata#1184]
Visidata is great in that you can:

-  locally run `vd bla.tsv.gz` and it will open correctly
- run `vd http://bla.com/bla.tsv` and it will open correctly.

But if you type `vd http://bla.com/bla.tsv.gz` (or for a real example, `visidata https://cog-uk.s3.climb.ac.uk/phylogenetics/latest/cog_metadata.csv.gz`) you get garbled binary due to the compression.

Could this be properly decompressed based on the URL file extension?

**Comment by saulpw** [comment]
That would be useful, @theosanderson, I agree!  Ideally this would use the decompression logic from [visidata.Path.open](https://github.com/saulpw/visidata/blob/stable/visidata/path.py#L204) somehow in the [http loader](https://github.com/saulpw/visidata/blob/stable/visidata/loaders/http.py#L66), but that's a bit tricky because of the `_iter_lines` generator used for auto-pagination.

This usage is probably more important than the auto-pagination case, so I'm willing to let that functionality go if someone provides a working PR for this case.  But probably both cases should be handled by a nice external library that can stream sheets and rows from disk or URL while transparently decompressing and decoding.  I have a private library for this (though it doesn't handle this case yet), but it is too large to fit in the margin.

**Comment by anjakefala** [comment]
Commenting to note that since this issue's opening, this feature has been supported for remote `.zip`. Remote `.gz` is not supported yet.

**Comment by tonycpsu** [comment]
@saulpw I'm having trouble opening zip files over s3. The error I get is:

```
URLSchemeUnknown: Not supported URL scheme s3
```
I can open CSV and other files over s3, but not zip.  The comment above says `.zip` is supported.  Is this the case, and if so, what, if anything can I do to get opening of zip files working over s3?

**Comment by saulpw** [comment]
I would love this, but I think it should be part of a larger effort to redo the `Path`, `open_http`, the `guess` and `guessurl`, and more, maybe even factoring all the vd loaders and savers into a separate library that can just load from any data source or format.

At the moment though, it's a bit hairy to get this use-case working, in conjunction with Progress for both reading and writing, due to fixes for #1159 and #1255.  If someone wants to try their hand at either a workable hack or a more broad solution I'd love to see a PR.  Kondo'ed for now.
