### ISSUE TITLE
Easy way to support blosc-compressed HDF5 files

### ISSUE THREAD

**Issue by aldanor** [saulpw/visidata#121]
`h5py`, as it is, does not support blosc compressors (the best ones really that everyone uses, e.g. lz4 family or zstd) out of the box, so reading a blosc-compressed HDF5 file would be impossible if you just `import h5py`. There were plans in h5py to add support for entrypoint-style plugins, but it's not there yet.

There's one easy hack, however -- importing PyTables. Upon import, it would register all blosc filters with the HDF5 C library which would then be magically shared with h5py (assuming both are linked to the same libhdf5) and it should then just work.

E.g.:

```python
import h5py
try:
    import tables
except ImportError:
    pass
```

Then in the docs, might mention something like "install pytables if you want the HDF5 driver to support blosc compressors/filters".

**Comment by saulpw** [comment]
Thanks, @aldanor!  This is a great tip and I think we'll probably add this to 1.2 for everyone's convenience.

In the meantime, you can add that same code to your `.visidatarc` and it should have the same effect.

**Comment by anjakefala** [comment]
Hey @aldanor,

I am currently trying to create a blosc compressed HDF5 file in order to test if the fix works in VisiData. Regrettably, I am having issues with it and I was hoping you may be able to help me understand this more deeply. =)

I have `tables v3.4.2` installed and `h5py v2.7.1` installed. However, they were both installed with `pip3` (not `conda`). 

(From the `pytables` release notes, it seems that their `setup.py` behaves differently in a `conda` environment than it does in a standard python virtual environment...my next attempt will be to retry in a `conda` environment.)

This is the code I am running:

```
import tables
import h5py

with h5py.File('sample_data/bloscdummy.hdf5', 'w') as f:
    f.create_dataset(name='myData', data=(100, 100), compression=32001, compression_opts=(0, 0, 0, 0, 9, 1, 5), shuffle=False)
```

and this is the error:

```
    raise ValueError("Unknown compression filter number: %s" % compression)
ValueError: Unknown compression filter number: 32001
```

**Comment by anjakefala** [comment]
In case it matters, my system is `Ubuntu 16.04 LTS`.

**Comment by saulpw** [comment]
Closing this for now, please reopen if there is any interest in fixing.

**Comment by prativadas** [comment]
whene i run this line 
f = h5py.File(os.path.join(data_path, 'train_16.h5'), 'w', compression='blosc:lz4', compression_opts=9)
i get error:
TypeError: 'compression' is an invalid keyword argument for this function
 kindly provide some solution

**Comment by anjakefala** [comment]
Hi @prativadas! This feels like a question meant for the [h5py team](https://github.com/h5py/h5py)?

VisiData is a commandline spreadsheet tool that supports the hdf5 file format thanks to the `h5py` library. =)

Having said that, I can direct you [here](http://docs.h5py.org/en/stable/high/file.html#File)! It seems like the `File` object does not support `compression` as an argument. `File().create_dataset()` does. You can check out some of the snippets in the code blocks in this issue.
