### ISSUE TITLE
Conda package? (via conda-forge)

### ISSUE THREAD

**Issue by aldanor** [saulpw/visidata#125]
Just a thought - it would be very nice to support conda by providing pre-built Linux / OS X conda package tarballs on conda-forge. It is actually fairly simple to write a feedstock so it gets built/published by conda-forge infrastructure.

**Comment by saulpw** [comment]
Hi @aldanor, I don't really use conda and so I've never done anything like this.  Would you be able to write the "feedstock"?  (Would it live in the visidata repository or in conda-forge or somewhere else?)

**Comment by saulpw** [comment]
or maybe @anjakefala, do you have time to look into this?

**Comment by anjakefala** [comment]
Hi!

I think this is an excellent proposal. I was considering looking into conda, since a lot of scientists do exclusively manage their packages with it. 

When deciding whether to add a new package distribution method, we like to investigate what the maintenance cost is before committing. I will look into it (and additionally see if it possible to automate the package updating process).

Thanks! =)

**Comment by aldanor** [comment]
Here's step-by-step instructions on how to do it, pretty simply actually: https://conda-forge.org/docs/recipe.html#step-by-step-instructions

Reference for conda's meta.yaml format: https://conda.io/docs/user-guide/tasks/build-packages/define-metadata.html

Here's a random feedstock, to show how it may look like when done: https://github.com/conda-forge/structlog-feedstock/blob/master/recipe/meta.yaml

Feel free to ping me if there's any problems.

**Comment by anjakefala** [comment]
[The conda-forge PR](https://github.com/conda-forge/staged-recipes/pull/5609)

Once it gets merged in:
- the update process needs to be added to dev/release
- the user installation info need to be added to the appropriate installation guides

**Comment by anjakefala** [comment]
We are merged in. =)
