### ISSUE TITLE
Custom type hexint does not always carry through to sub-sheets

### ISSUE THREAD

**Issue by bitwisecook** [saulpw/visidata#1254]
In the f5log plugin I create a custom type "hexint", but when navigating to sub-sheets it does not always carry through.

https://github.com/bitwisecook/visidata-f5log/blob/0.2.4/f5log.py#L20

**Expected result**
The column should display as a hexint, the icon is present but the integers are base 10 instead of base 16.

**Actual result with screenshot**
![image](https://user-images.githubusercontent.com/2267430/147275628-f8b33f2f-de8c-4faa-9aad-6780584d0fa6.png)

![image](https://user-images.githubusercontent.com/2267430/147275635-c928903f-c6a9-474a-831a-965c24a69fe8.png)

**Steps to reproduce with sample data and a .vd**
[testlog_logid1_freq.vd.txt](https://github.com/saulpw/visidata/files/7770765/testlog_logid1_freq.vd.txt)
[testlog.log](https://github.com/saulpw/visidata/files/7770766/testlog.log)

**Additional context**
2.9.0-dev with f5log 0.2.4

**Comment by saulpw** [comment]
Hi @bitwisecook, thanks for the report. I have an idea for a possible fix in 8fb4898, but it breaks other tests so we'll probably wind up reverting it.  I think the real issue here is that a custom type needs to be the identity function for something that's already this type.  From the [documentation on custom types](https://www.visidata.org/docs/api/columns#types):

    - TYPE(typedval) must return an exact copy of typedval.

This is because some things, like the keys on Freq/Pivot sheets, pull in the typed value, and then also set the column type to that type.  So if you add this identity functionality to your types, I think they'll work as expected.

**Comment by bitwisecook** [comment]
fixed in f5log https://github.com/bitwisecook/visidata-f5log/blob/0.3.2/f5log.py#L17-L22
