### ISSUE TITLE
Send selected rows to stdout ?

### ISSUE THREAD

**Issue by bradparks** [saulpw/visidata#128]
Is there anyway to echo the selected rows to stdout ? I noticed that I can just run `vd` and that opens up a browseable folder structure that I can navigate. Is there a way that I can select some column values and then hit a key to exit and have those selections output to the terminal?

If so, then I could use this as a way to choose files to pass in pipelines, which would be cool!

**Comment by saulpw** [comment]
Hi @bradparks, this is a neat idea.  You can do it this way, although it's admittedly a bit onerous:

1. launch VisiData with `vd -o -`.  This tells VisiData to output the top sheet to stdout at the end.
2. hide all columns but `filename`, with `-`.  Without this, the additional columns will be output also.
3. rename the filename column to an empty string, with `^`.  Without this, `filename` itself will be output as the first line.
4. select the files you want to output, with `s` (or `|` etc).
5. pull those files into their own sheet, with `"`.  Otherwise all files will be output, regardless of the ones you selected.
6. quit with `^Q`.  This aborts immediately without dropping any sheets, so that there is still a top sheet to be output.  `q` or `gq` will drop the sheets and not output anything.

Items 2 and 3 can be automated with a .vd script, so that you could run `vd -p filechooser.vd -o -` and then jump to step 4 (although then you would not be able to see the size/date/ext information which might be handy when selecting files).

Thanks for the suggestion!
