### ISSUE TITLE
options.quitguard = True in my rc file doesn't prevent vd from silently quitting

### ISSUE THREAD

**Issue by halloleo** [saulpw/visidata#1290]
**Small description**

`options.quitguard = True` in my ~/.visidatarc file doesn't prevent `vd` from quitting via `q` _without` any confirmation when I have modified the loaded CSV.

**Expected result**

With `options.quitguard = True` in my `~/.visidatarc` file I expect after  I have modified the loaded CSV that `Q` asks me to confirm whether I want to quit despite the modifications.

**Actual result with screenshot**

`vd` quits directly despite the modifications.

**Steps to reproduce with sample data and a .vd**

1. Unzip the attached zip. 
2. Put the included `.visidatarc` in your rc file location (`~`) . 
3. Start `vd` with the included file `quitguard-sample.csv`. 
4. Then do the actions listed in the command log `quitguard-sample.vd`.
5. Then quit with `Q`

**Additional context**

Version of VisiData: v2.8

Zip file with the sample data: [quitguard_sample.zip](https://github.com/saulpw/visidata/files/8075676/quitguard_sample.zip)

**Comment by anjakefala** [comment]
The important part is "in rc file". `--quitguard=True` on the commandline appears to block quitting. 

**Update**
An additional important part is that the `.vd` contains an `expr-col` command. If you do an `edit-cell` command, and have `options.quitguard` in your visidatarc, then VisiData asks for confirmation.

The very specific combination of "options.quitguard=True" in rc, and `expr-col` fail to quitguard. Very curious, indeed!

**Update**

Other commands that add a column, are similarly not being guarded against when quitguard is set to True in the rc.

**Update**

Commands that add a column seem to have `vs.hasBeenModified = False`. `--quitguard=False` has been working because it sets `quitguard` on a specific sheet. When a specific sheet has been set to quitguard=True, then quitguard asks for confirmation, regardless if the sheet was modified.

**We need to check if adding a column can have hasBeenModified set to True. This might also be philosophical: if we want adding a column to be constituted as a modification.**

**Comment by anjakefala** [comment]
Thanks for letting me know about this @halloleo! This should now be fixed on `develop`. `pip3 install --upgrade git+https://github.com/saulpw/visidata.git@develop` should upgrade your copy locally. =)
