### ISSUE TITLE
Saving macro fails with NameError: name 'fnSuffix' is not defined

### ISSUE THREAD

**Issue by code86** [saulpw/visidata#1297]
I am still getting the same error message as the OP in bug report [#1280](https://github.com/saulpw/visidata/issues/1280). 

Ctrl+E (error-recent) shows error was activated in line 39 of macros.py

In macros.py ([line 39](https://github.com/saulpw/visidata/blob/stable/visidata/macros.py)), `fnSuffix` is called with one argument.

But in cmdlog.py ([line 42](https://github.com/saulpw/visidata/blob/stable/visidata/cmdlog.py)), `fnSuffix` is defined with two parameters? (vd, prefix)

Could that be the problem?

Note: I am using a clean conda reinstallation in a new env, with "conda update --all" applied.

---
  File "/Users/code86/opt/miniconda3/envs/env2/lib/python3.8/site-packages/visidata/macros.py", line 39, in saveMacro
    macropath = Path(fnSuffix(options.visidata_dir+"macro"))
NameError: name 'fnSuffix' is not defined

_Originally posted by @code86 in https://github.com/saulpw/visidata/issues/1280#issuecomment-1047218735_

**Comment by anjakefala** [comment]
Question was answered here: https://github.com/saulpw/visidata/issues/1280

In general, I do re-open issues if the bug persists, so there is no need to create new issues for the same problem! It can make it harder for someone trying to understand how to fix the bug for themselves to follow the conversation if there are multiple places where the bug is discussed.
