### ISSUE TITLE
Can visidata parse a JSON document consisting of a single array without passing through jq?

### ISSUE THREAD

**Issue by deinspanjer** [saulpw/visidata#133]
This doesn't work for me:
```
cat <<JSON | vd -f json
[
  {
    "a": 1,
    "b": 2
  },
  {
    "a": 3,
    "b": 4
  },
  {
    "c": null
  }
]
JSON
```
It gives a sheet that seems to have no rows and no columns, and `z^Y` cannot expand it.

However, it works fine if I filter it through jq and then use jsonl format:
```
cat <<JSON | jq -c '.[]' | vd -f jsonl
[
  {
    "a": 1,
    "b": 2
  },
  {
    "a": 3,
    "b": 4
  },
  {
    "c": null
  }
]
JSON
```

**Comment by deinspanjer** [comment]
I'll also just ask here.. I noticed a difference in the man page for the version I have installed (1.1 via brew) and the docs on http://visidata.org/man/ regarding expanding cells containing JSON lists and maps.
The man page says to use `(` to expand them into new columns and `)` to close them, but the online docs mentions using `z^Y` to open them in a new sheet and nothing about expanding.  Are we losing that feature or is it just not consistently documented?

**Comment by saulpw** [comment]
Hey @deinspanjer, thanks for the questions.  I'll investigate the json loader above.  As to the difference between `(` and `z^Y`, the former expands the columns on the current sheet into additional columns, whereas the latter opens a new sheet for the contents of the cell.  The `^Y` series of commands are intended more as development commands (I think of them as "open pYthon sheet"), for investigating the inner workings of rows or cells (hence the "Ctrl" modifier).  `(` and `)` are meant to be more data-friendly for normal workflows.  I do not intend to remove `^Y`, but if it is inconsistently documented, it's because `(` is new (just added in 1.1).

**Comment by anjakefala** [comment]
Sorry about the confusion; we not losing that feature! 

The manpage within visidata has been updated for 1.1, but the website has not been yet. It will be updated this weekend. :)

**Comment by anjakefala** [comment]
Updated docs have been deployed: https://visidata.org/man
