### ISSUE TITLE
Hiding column cancels replay

### ISSUE THREAD

**Issue by jungle-boogie** [saulpw/visidata#1349]
Hello,

I like the `Visidata` replay feature and hope to be able to use it with my data.

I've noticed that if I hide a column in a MS Excel spreadsheet, the replay is cancelled.

1. Open vd with a MS Excel file that has multiple columns
2. Hide a column with `-`
3. Save the playback as test.vd
4. Quit vd
5. `vd --play test.vd`
6. Notice `replay canceled` will appear

I would expect the replay to hide the column I selected.

This is what's in the playback:
```
myfile  0               hide-col                -       Hide current column
```

$ vd -v
saul.pw/VisiData v2.9dev

**Comment by jungle-boogie** [comment]
Ah, the issue is if the column has no name, then the replay is cancelled.

**Comment by jungle-boogie** [comment]
If I delete the 0 in the test.vd, everything works.

```
myfile                 hide-col                -       Hide current column
```

**Comment by anjakefala** [comment]
Excellent find!

Since 6e1334167f740a78832054e63020215acc6d5a88, column indexing via the replay requires an explicit int value. This is to support column names that are numeric. `.vdj` supports typed values, and so can distinguish between an int value for **column** (index via column number), and a string value for **column** (index via column name).

I am going to make sure that VisiData does the right thing if the **CmdLog** format was `.vdj`. And then maybe we should consider making `.vdj` the default format.

**Comment by anjakefala** [comment]
Blank column names should now work in replay, when using `.vdj` as the replay format! I also ensured `.vdj` was the default format. This fix is in `develop`, and will be part of the next VisiData release.

Thanks for the issue!

**Comment by jungle-boogie** [comment]
Thank you for the fix.

What’s the difference between vdj and vd? When should each of these be used?

**Comment by anjakefala** [comment]
`vdj` is `jsonl` like and includes typing! `vd` is `tsv` like, and does not include typing. The typing of values is how we can distinguish whether a column name is an index or the name of the column. =)

**Comment by jungle-boogie** [comment]
Thanks for the reply.

Does this mean I need to format my visidata scripts differently, or is that
handled internally by visidata?

**Comment by saulpw** [comment]
@jungle-boogie If you save as .vdj it should handle it for you.
