### ISSUE TITLE
Is there a way to specify commands from outside VD, e.g. in Bash?

### ISSUE THREAD

**Issue by dancromartie** [saulpw/visidata#1384]
Liking visidata so far! I've spent maybe 4 hours fiddling with it, so apologies if this is implemented and I'm missing something obvious.

I know you can save commands to be replayed, and I could try and format my commands into that shape, but I'm wondering if something simpler exists.

I liked how easy it was to "melt" a dataset after loading it. I wanted to just pipe some text to vd on STDIN and have it be melted. I was hoping do something like this from bash:

```
cat my_file.csv | vd -f csv --commands "melt; command2; command3" - | grep ...
```

So, similar to `python -c` or `vim -c` etc. Is there a way?

Edit: I also tried the `-P=longname` option (so `-P=melt`), but it seems this runs the command *before* the data is loaded? Didn't seem to work.

**Comment by dancromartie** [comment]
Actually, much later, I've realized you can achieve this with something like:

```
csv_generating_command | vd --play melt_session.vd --batch --output - 2>/dev/null
```
assuming `melt_session.vd` is a saved session where you ran a melt command.

**Comment by saulpw** [comment]
Wow, sorry we never responded to this, @dancromartie!  That May was a really busy month and I guess it just got lost.  But I've definitely been thinking about it, because it was part of the inspiration for the new `.vdx` format, which is just a list of commands (and their inputs, if they have any).  Saving and replaying `.vdx` works already, but it should be very straightforward to add a CLI option like `-x/--execute "col abc\nmelt\n` as you suggest.

What do you think, having used replay?  Would the above CLI option be more ergonomic?

**Comment by dancromartie** [comment]
No worries at all! I was doing my intro dive into Visidata back then, and it was more of a question rather than a legitimate pain point. Yesterday, getting back into it, I was wondering if I could script the making of frequency tables, or sorting a CSV, or deleting one column, without using `pandas` (just a for-fun comparison). I had thought about trying the `xsv` tool by burntsushi, but then I thought Visidata probably does many similar things (for smaller datasets at least?) and is already installed!

I didn't know about `.vdx`. I couldn't find anything online - maybe it's very new? I tried making one as just a "list of commands", which seems to run _before_ loading the data, but you also mention the "list of inputs, if they have any", and maybe that's the missing piece.

Is there a way to save a `.vdx` file from interactive mode so I can see an example of the right structure? I tried `^d` and changing the extension to `.vdx`, but that didn't seem to work.

**Comment by saulpw** [comment]
Yes, it's very new, not even released yet, so you'd have to install from the `develop` branch on github.  Or you can wait for the next release :)

**Comment by dancromartie** [comment]
Ok, I'll keep an eye out for upcoming releases - thank you! (Btw, really enjoying Visidata lately! Makes my work much easier)

**Comment by dufferzafar** [comment]
@saulpw I think having an `execute` flag would definitely be ergonomical.

I'm currently writing a shell script that pipes some data in to visidata, and trying to get replay working with a heredoc. I don't want to save the cmdlog into a separate file, since it's only a few lines.

Here's what I have, but it doesn't work for some reason:

```bash
query_command | vd -f csv -p /dev/fd/5 - 5<< 'EOF'
sheet	col	row	longname	input	keystrokes	comment
			open-file	-
-			go-rightmost
EOF
```
