### ISSUE TITLE
Having trouble running vd on Windows

### ISSUE THREAD

**Issue by aagha** [saulpw/visidata#1406]
**Small description**
Every VD command I run outputs a python error (in notepad)

**Expected result**
Print out result, e.g, version number

**Actual result with screenshot**
I successfully install visidata w/ pip3 on Anaconda (Win 10 Pro) and then try to get the version by executing `vd --version`. Immediately I'm asked to select a file to open the output with:

![image](https://user-images.githubusercontent.com/5522103/175179345-b45d02fb-8c3e-4e1c-81e7-3a319d187c62.png)

When I select Notepad, I see:

![image](https://user-images.githubusercontent.com/5522103/175179375-d673b825-ca44-43e1-8c28-556c82245116.png)

Note -- I also tried to use conda to do the install, with the same result:

![image](https://user-images.githubusercontent.com/5522103/175179809-6e4c686b-8d34-4e5e-9fb1-2c363f28d139.png)

**Steps to reproduce with sample data and a .vd**
Please attach the commandlog (saved with `Ctrl-D`) to show the steps that led to the issue.
See [here](http://visidata.org/docs/save-restore/) for more details.

**Additional context**
Please include the version of VisiData.

**Comment by ajkerrigan** [comment]
Hi @aagha - this looks similar to #1268. That thread has a few suggested workarounds and more detail, but one of these options might get you somewhere useful:

* Try running `visidata` rather than `vd` (since pip-installing visidata on Windows should put a Windows-friendly `visidata.exe` alongside the `vd` script)
* Run `python $(gcm vd).Source` to feed the `vd` script into your active python interpreter

_Note that if you see an error about `_curses` it means you'll want to pip install `windows-curses`_

**Comment by aagha** [comment]
That solved it @ajkerrigan:

![image](https://user-images.githubusercontent.com/5522103/176060577-8b2834df-7b34-481c-98f2-8eb6b53602ae.png)

Thank you!

**Comment by s1291** [comment]
For me, it was much convenient to just rename the `vd` file to `vd.bat` and remove the content of it, and replace with the line:
```
visidata
```

The steps:
- Get the location of the `vd` file by running the following command in PowerShell: `gcm vd`
- Rename the file to `vd.bat`
- Modify that file by removing all content and adding a single line that contains `visidata`
