### ISSUE TITLE
Documentation: figures are malformed in Chrome

### ISSUE THREAD

**Issue by reagle** [saulpw/visidata#1418]
Figures in the documentation don't look correct in google-chrome/103.0.5060.53 on macOS 12.4 21F79 arm64.

<img width="878" alt="Screen Shot 2022-06-29 at 12 17 29" src="https://user-images.githubusercontent.com/596814/176486346-078a98cb-a5e0-4e24-aa56-998eac035988.png">

**Comment by jsvine** [comment]
Hi @reagle, it seems that you're referring to [the VisiData tutorial I wrote](https://jsvine.github.io/intro-to-visidata/), rather than the official VisiData documentation written by the maintainers here. But thank you for flagging that — I'll look into it and will track it over here: https://github.com/jsvine/intro-to-visidata/issues/37

**Comment by reagle** [comment]
Thanks. I'll close this here then.
