### ISSUE TITLE
Better handling of column names with spaces when computing derivative columns

### ISSUE THREAD

**Issue by cclark** [saulpw/visidata#142]
I'm working on a CSV I downloaded from a Financial Institution and there are headers like `Gross Proceeds` or `Cost or Other Basis`. When I create a pivot table these become `Total_Gross Proceeds` and `Total_Cost or Other Basis`. This leads me to believe like me (and most programmers) you opt to not use whitespace characters when naming. What is interesting is that when I use `=` to create a derivative column the tab completion of column names still works. However, the expression evaluation fails with a cryptic/unhelpful `Syntax Error: invalid syntax`.

STR:
In the sample.tsv change the column name of `Unit_Cost` to `Unit Cost`
Enter the expression `=Unit Cost/2` (Note: You can use tab completion to get to `Unit Cost` with `U` + `Tab`)

**Comment by saulpw** [comment]
Hi @cclark, 

The column names must be valid identifiers to be used in a Python expression, that's by design.  The tab completion is just given the list of column names, since that's what's in the locals dictionary too.  I went back and forth on whether column names should be forced to be valid Python identifiers, and so I made an option which you can set in your `.visidatarc` if you want that behavior:

`options.clean_names = True
`

BTW, you can get information for an error inside a cell with `z Ctrl-E`, which will display a stacktrace and can usually help you figure out how the expression is incorrect.

**Comment by techieshark** [comment]
I just ran across this. Was wondering how to fix the column names so they could be used in expressions.

Here's what I did to replace all spaces in columnn names with underscores:

`Shift+C` to get column view
`gs` to select all rows 
make sure cursor is on the `name` column 
`g=` to globally replace name contents, with expression as: `name.replace(' ', '_')`

**Comment by geekscrapy** [comment]
@techieshark these days you can add: `options.clean_names = True` to your .visidatarc and you will always have column names that you can use in expressions 👍 

Also, if you have the sheet already loaded, I expect you can set this in the global options then reload the sheet.

But your way is still perfectly valid! Sometimes you dont want the Pythonized names

**Comment by ghost** [comment]
For completeness, you can use @techieshark's method, but for the last step use `g*` with expression ` /_` (`space/_`) to update the current column by regex.
