### ISSUE TITLE
Unable to copy to Windows clipboard

### ISSUE THREAD

**Issue by pshangov** [saulpw/visidata#1431]
**Small description**

Trying to copy rows to system clipboard results in a permission error.

**Expected result**

Should be able to copy data to system clipboard.

**Actual result with screenshot**

![image](https://user-images.githubusercontent.com/112953/179730372-45bd8610-481c-46de-a7e7-d86088cff070.png)

![image](https://user-images.githubusercontent.com/112953/179730424-ab160d2b-f9b2-4d68-9db3-bbbed1ce8bcb.png)

**Steps to reproduce with sample data and a .vd**

Select rows with `gs`, copy with `gY`.

**Additional context**

VisiData v2.8

**Comment by saulpw** [comment]
Hey @pshangov, thanks for the report.  We don't officially support Windows (none of the devs use it), but if someone figures out what's going wrong here and proposes a solution, I'm sure we can incorporate it.

Also check out #1438 for some more discussion about running VisiData on Windows.

**Comment by daviewales** [comment]
This issue is because [tempfile.NamedTemporaryFile](https://docs.python.org/3/library/tempfile.html#tempfile.NamedTemporaryFile) creates _and opens_ the temporary file.
Windows refuses to read or open a file which is already open in another process.

The relevant code is here:
https://github.com/saulpw/visidata/blob/388035c36b8e1dee470323c6775ed95d6783956e/visidata/clipboard.py#L44

``` python
@Sheet.api
def syscopyValue(sheet, val):
    # use NTF to generate filename and delete file on context exit
    with tempfile.NamedTemporaryFile(suffix='.txt') as temp:
        with open(temp.name, "w", encoding=sheet.options.encoding) as fp:
            fp.write(val)

        p = subprocess.Popen(
            sheet.options.clipboard_copy_cmd.split(),
            stdin=open(temp.name, 'r', encoding=sheet.options.encoding),
            stdout=subprocess.DEVNULL,
            close_fds=True)
        p.communicate()

    vd.status('copied value to system clipboard')

```

To make it cross-platform, we could remove the second `with` statement. (no need to open a file that's already open.)
We'll need to pass the `delete=True` arguemnt (and the `mode` and `encoding` arguments) to `NamedTemporaryFile`.
We'd need to close the file before Popen tells `clip.exe` to read it.
And we'll need to manually delete the file after `clip.exe` is done with it.

I'll see if I can find some time to test this theory after work.

**Comment by daviewales** [comment]
I've got something working on Windows. However, I've had a [Chesterton's Fence](https://en.wikipedia.org/wiki/Wikipedia:Chesterton's_fence) style thought.
What if we just pipe the value directly into `stdin`, without writing to a file at all?
Is there a particular reason why we need to write to a temporary file?

Thoughts @anjakefala @saulpw?

**Comment by saulpw** [comment]
I believe there was a reason why it has to be written to a tempfile, but I don't recall why; it may have been because I didn't understand the semantics of NamedTemporaryFile :)  We can certainly try it and see if it seems to work.  Can you submit a PR?

**Comment by daviewales** [comment]
Will do. Juggling two children under 3, but a PR is definitely coming!

**Comment by daviewales** [comment]
There are two clipboard functions, one for copying individual values, and one for copying selected rows.
I've fixed both to work on Windows.

For syscopyValues, you can choose from #1518, which reuses the open file rather than re-opening an already open file, or #1519, which writes directly to the clipboard copy command stdin, without using a file at all.

For syscopyCells, I couldn't use either of the above methods without extensive refactoring, so I opted for a simple hack – just close the temp file as soon as it's opened. (This is included in both #1518 and #1519). This is because syscopyCells uses vd.saveSheets to get the data, which expects a path, and won't currently accept an open file handle.

**Comment by geekscrapy** [comment]
FWIW When things / solutions settle, let me know and I'll give it a spin on Mac if you haven't already 👍

**Comment by daviewales** [comment]
Thanks @geekscrapy. I've tested both PRs on Mac, but more tests and eyeballs are appreciated. I'm not planning to make any more changes for now.
