### ISSUE TITLE
Copy multiple columns across different files

### ISSUE THREAD

**Issue by jingxixu** [saulpw/visidata#1462]
Is there a way for me to copy multiple consecutive columns from one file and paste/insert them into another file? Thanks!

**Comment by saulpw** [comment]
Hi @jingxixu, there's not a direct way, but you could hide the rest of the columns and then use `gsgy` to copy all the rows, if you're trying to create a new sheet with that data.  Otherwise are you trying to extend existing data in one table with columns from another table?  If so then I would use the join commands with the 'extend' jointype.  And you can use `i`/`addcol-incr` to add a column to join on if it's just row number.
