### ISSUE TITLE
How to pass "no quotation char" parameter?

### ISSUE THREAD

**Issue by aborruso** [saulpw/visidata#147]
Hi,
I have a not so good CSV, like this:

```
field1|field2
"value of field1|value of field2
hello|wold
```

The separator is `|` and I apply `vd --csv-delimiter "|" input.csv`

But, if I do not remove the `"` in the first row, I have a wrong reading result. Is it possible to set `--csv-quotechar` to NONE?

I would like to have in output something like

|field1|field2|
|---|---|
|"value of field1|value of field2|
|hello|wold|

Thank you

**Comment by saulpw** [comment]
Hi @aborruso, thanks for the bug report.  Due to how the Python3 `csv` module works, you can't set the quotechar to an empty string if quoting is enabled.  `csv_quotechar` is not yet an explicit option in VisiData, but in v1.2, we made it so that all `csv_` options are passed through to the csv module.  Unfortunately you can't pass it on the command line, but it will work if you add this to your `.visidatarc`:

```
options.csv_quoting=csv.QUOTE_NONE
options.csv_delimiter='|'
```

Of course, that means that all other csv files will have quoting disabled, but it will at least work for this use case.
