### ISSUE TITLE
Impossible to read the selected record row, when it is just selected

### ISSUE THREAD

**Issue by aborruso** [saulpw/visidata#149]
Hi,
whene I select a row and than pass above it, it becomes unreadable.

I have it, in every row where there is a color different from black or white.

![visidata2](https://user-images.githubusercontent.com/30607/40282010-b70993f2-5c68-11e8-88ce-35f872acb94a.gif)

**Comment by saulpw** [comment]
Hi @aborruso, I believe you are having problems with 256-colors.  I'm not sure how you get that working in your terminal setup, but if you set all the color options to remove the numbers (e.g. color_selected_row = 'yellow' instead of '215 yellow'), then I think that might be a useful workaround for you.

**Comment by aborruso** [comment]
@saulpw it works, thank you
