### ISSUE TITLE
[alt-shift- ]  The open-memos keyboard shortcut doesn't work

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#1497]
**Small description**
The open-memos keyboard shortcut doesn't work

**Expected result**
The open-memos keyboard shortcut would open the memo sheet.

**Actual result with screenshot**
https://asciinema.org/a/iFDKQSKcR6Sn9XTPsRCb3hb2f

**Steps to reproduce with sample data and a .vd**

`vd` then press `Alt+Shift+M`  VisiData is calling it `Alt+Shift+M`, while the shortcut is called `Alt+M`

**Additional context**
Please include the version of VisiData.  Latest develop version.

**Comment by anjakefala** [comment]
Nice find! `Alt+Shift+<keystroke>` not working as expected is the bug. `open-memos` is our only one in this category for now.

**Comment by anjakefala** [comment]
The culprit is `vd.prettykeys`. Essentially, this line https://github.com/saulpw/visidata/blob/03a2325902e9c905ee2873b692028930462550f5/visidata/keys.py#L77 results in the ignoring of `Shift+` in a `Shift+<keystroke` for `Alt+` and `Ctrl+`. What is left to decide is whether to support `Alt+Shift+`. If we do, then that is where I change the code. 

(@saulpw)

**Comment by anjakefala** [comment]
Thanks @frosencrantz! =) We fixed this just in time for `v2.10`.

**Comment by frosencrantz** [comment]
Thanks @anjakefala!  I tried to quickly report the problem so it could be fixed before for 2.10, glad it helped.
