### ISSUE TITLE
Incomplete file loads when accessed from external disk drive

### ISSUE THREAD

**Issue by ronancremin** [saulpw/visidata#151]
I'm trying to load a 531MB file into VisiData from an external USB disk. The file is 5.2 million lines of CSV.

When I load this file from the externally mounted disk VisiData appears to stop loading after about 19k lines without error. The lines that do load show as expected. The exact same file loads fully when copied to the boot disk and loaded into VisiData from there. 

The external drive is a spinning disk accessed over USB 3, the boot disk is an SSD—so the external drive is many times slower. Could something be timing out? Other utilities such as wc and grep access the full file on the external disk correctly e.g. `wc -l` correctly counts the lines in the file.

MacOS 10.13
VisiData 1.2

No commandlog submitted since the issue manifests on load.

**Comment by saulpw** [comment]
That is super weird.  Can you confirm that the loading has fully stopped, and not just stalled?  The progress percentage indicator in the lower right should not be visible, and if you press Ctrl-T to go to the Threads Sheet, the loader thread should not still be running.  (If the thread aborted due to error, that error should be listed in the status column as well).  If the loading thread truly is stopped, try pressing Ctrl-E to see if there is an error stack, and Ctrl-P to look at all status messages to see if some other indicator/error slipped by.

The only other reason that a loader would end early, would be due to the `min_memory_mb` option, which if set to a value other than 0 (the default), would cancel the thread when `free` reports less than that amount of memory available.  (Though this should still show up as an error).  Do you have this option set in your `.visidatarc`, perhaps?  Copying a large amount of data over USB might cause increased memory usage for some reason.

Otherwise, if the thread has ended normally and there is no error, then I'm a little stumped as to why this would happen.

**Comment by ronancremin** [comment]
User error. I checked it twice before reporting but somehow failed to notice what I was doing. My sincere apologies for wasting your time. 

Thanks for the Threads, Error and Status tips.
