### ISSUE TITLE
Idle performance

### ISSUE THREAD

**Issue by timtroendle** [saulpw/visidata#153]
VisiData uses a lot of cpu time when being idle on my machine, i.e. sitting in the background and doing nothing -- you'd think. On my MacBook Pro i5 2017 each process takes well above 10%, actually closer to 20% cpu. Is this something particular to my setup? It appears way too high to me.

I am using VisiData v1.2 which I installed through HomeBrew.

**Comment by saulpw** [comment]
Hi @timtroendle!  This is a known 'issue', I see the same thing on Linux myself.  The cause is that VisiData simply recomputes and redraws the entire screen every `curses_timeout` milliseconds, which is set to 100 by default--or 10x/sec.  During async processing this makes the interface feel a lot more responsive, but the computation and layout process is expensive, so it uses a fair amount of CPU even when idle.  If you want to reduce the idle load, you can add something like this to your `.visidatarc`:

```
options.curses_timeout = 1000
```

making the redraw only happen once per second, which should reduce the idle load by 90%.

**Comment by timtroendle** [comment]
Ok, I see. It would be great to have the recomputation interval to somehow adapt to whether the screen is visible or not but I understand that might not be easy. Thanks for the hint with the parameter, I'll give it a try. And thanks for the great work in general @saulpw, I am having VisiData in daily use!
