### ISSUE TITLE
[Loader] RSS reader

### ISSUE THREAD

**Issue by RidaAyed** [saulpw/visidata#157]
Hi

Can vd handle rss e.g. https://hnrss.org/newest ?

**Comment by saulpw** [comment]
Hi @RidaAyed.  RSS is in xml format, which VisiData can't open yet.  I'll change this issue to a feature request for the xml loader.  It's on the ROADMAP but I haven't had a deep need to do it yet.

**Comment by saulpw** [comment]
XML can now be loaded in VisiData.  RSS might still want its own loader/sheet structure though.

**Comment by anjakefala** [comment]
This issue has been added to our [someday/maybe list](https://github.com/saulpw/visidata/blob/develop/dev/ROADMAP-someday.md). 

For this issue to be reopened, someone who has a vision for what an RSS reader would look like within VisiData is needed.

**Comment by Oblomov** [comment]
Maybe something more generic that simply an RSS reader, it could be possible to specify something like an XML path to determine 'rows'? For example for RSS this could be `//channel/item` while for other XML formats it could be something else. (I may have missed it,but  I haven't found anything in the documentation on how to select the tags to map to rows in XML view.)

**Comment by saulpw** [comment]
That's a really interesting idea, @Oblomov !  What if we changed the loader to use `findall(self.options.xml_xpath)` instead of `iter()`?  Would you be interested in submitting a PR?

**Comment by Oblomov** [comment]
Honestly I don't think I know enough of the vd internals to try my hands at this. I'm also not sure this would be sufficient, if I'm understanding your suggestions correctly, but again this might be because of my lack of understanding of the internals. From what I see, the XML reader currently predefines the columns in terms of some attributes and properties of each tag.  What I was thinking about instead was having the XML path define the row, and the nesting elements define the columns. This would be similar to how the HTML reader behaves when parsing tables, except with a generic XML element instead of what is effectively a hand-rolled `//table/tr`.

**Comment by saulpw** [comment]
I think this is totally workable, @Oblomov.  The rows are just XmlElements, so we could create an XpathColumn that has an `expr` with an xpath in it, and the `calcValue()` would return the text/attribute of the that xpath from the row.  The `iterload` would just have to walk the first item and generate the columns with all the xpaths.

Come by visidata.org/chat, and we can talk about it and maybe pair on it!  It might be easier than you think.
