### ISSUE TITLE
cmdlog does not record choices from menu

### ISSUE THREAD

**Issue by leeand00** [saulpw/visidata#1577]
**Small description**
Was inner joining a few sheets together and recording a cmdlog when I found that there was an issue playing them back.

**Expected result**
Expected that play back from the command log would play as usual, but it did not, it stopped with the error message...

sheets| no choice made | replay aborted during join-selected | merge selected sheets with visible columns from all, keeping rows according to jointype.

![image](https://user-images.githubusercontent.com/83778/198755064-92273367-52cd-434a-ad0d-91f981263632.png)

Here is the difference between the two methods:

![image](https://user-images.githubusercontent.com/83778/198755091-ba74bfec-3111-474f-94b5-9d361cd9a869.png)

Version saul.pw/VisiData v2.8

**Comment by anjakefala** [comment]
Good catch! This bug is happening because the choices menu is opening up as a new sheet, and the choice does not then get recorded as an `input` for the command.

It is on the roadmap to replace the chooser with a modal dialogue instead: https://github.com/saulpw/visidata/issues/1027 I am going to close this issue, since we have a seperate issue recording this behaviour.
