### ISSUE TITLE
Select first row in group of rows

### ISSUE THREAD

**Issue by RidaAyed** [saulpw/visidata#158]
Hi

I'm mentally blocked on a simple task. 
Given rows containing duplicate zips, How can I select the first of each group?

```bash
$ cat input.csv
zip,name
123,city1
123,city1somesuch
321,city2
321,city2somesuch
321,city2whatever
```

Expected

```bash
$ cat output.csv
zip,name
123,city1
321,city2
```

Tried marking column *zip* as keycolum by hitting `!`, followed by `F` > `gs` > `q` though logically this selects all rows in source sheet... :thinking:

**Comment by saulpw** [comment]
This is a really tough one, @RidaAyed.  I can't think of an easy way to do it in VisiData currently without implementing a custom aggregator.  I guess you could do this:

1. add a new column for the row number (using `za`)
2. populate it using a range expression like `gz=range(10000)`
3. make it a key column (for the later join)
4. add the 'min' aggregator to that column (because you want the first one)
5. do a `F`requency on the `zip` column
6. on that Frequency Sheet, unkey the 'zip' column, and make the min_rownum a key
7. finally, go to the `S`heets Sheet, and select the two sheets and `&` join with the original sheet as `inner`.

Then you should have a sheet with the first row of each group.  But, that's not exactly an obvious process.  I will think more on the aggregator approach and if it's a reasonable snippet to write.

**Comment by RidaAyed** [comment]
@saulpw  Thank you so much for taking your time and your well-elaborated answer dear Saul
