### ISSUE TITLE
Python 3.11 released with builtin toml support.

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#1587]
### Discussed in https://github.com/saulpw/visidata/discussions/1580

<div type='discussions-op-text'>

<sup>Originally posted by **frosencrantz** October 29, 2022</sup>
Python 3.11 has been released with speed improvements and builtin toml support: https://docs.python.org/3/whatsnew/3.11.html

- Sounds like VisiData should add support for toml, too.
</div>

Since Python has builtin support for TOML now, it seems like VisiData should also add basic support.

**Comment by LaPingvino** [comment]
Visidata has a relatively low baseline Python version it still supports. It would take some time for 3.11 to be broadly adopted before this can be feasibly considered I think.

**Comment by frosencrantz** [comment]
@LaPingvino  that is true about wide spread 3.11 usage.  Visidata can already handle the case where the base modules isn't available.  Also, the 3.11 support according to  [PEP 680](https://peps.python.org/pep-0680) is actually https://github.com/hukkin/tomli.  So there is a backfill available.

**Comment by frosencrantz** [comment]
I'll mention that @ajkerrigan  has already created this as a plugin: 
 - https://github.com/ajkerrigan/visidata-plugins/blob/master/plugins/vd_toml.py

Wondering if it would be possible to make it standard?

**Comment by ajkerrigan** [comment]
> I'll mention that @ajkerrigan has already created this as a plugin:
> 
>     * https://github.com/ajkerrigan/visidata-plugins/blob/master/plugins/vd_toml.py
> 
> 
> Wondering if it would be possible to make it standard?

 @LaPingvino's point seems reasonable there - making it standard would mean taking a conditional dependency on tomli for Python < 3.11 and that feels like "most people" for the time being. That doesn't feel like too big a deal, but it also doesn't feel like a clear win over installing a plugin :shrug: .

(To give credit where it's due @frosencrantz , I believe I only put that plugin together after you put the idea in my head :laughing: . And for what it's worth, I find myself using TOML support surprisingly often to poke at `pyproject.toml` and `poetry.lock` files!)

**Comment by frosencrantz** [comment]
Thanks for adding the TOML plugin, @ajkerrigan!  Also, happy to hear you use it regularly. 

I think over time I've come around in general to the idea that VisiData plugins are the way to extend VisiData further.  It would be useful to build a bigger plugin community.  There are some great ones already, but I wish there was a larger list.  Not sure how to get more people to develop plugins. Better docs, more community assistance, suggestions...

Anyways, I think in this case since TOML is now builtin to the latest version of Python it would make sense to make it a native loader.  I propose a VisiData development guideline:  When Python includes the batteries, VisiData should as well.  If Python supports a file format, so should VisiData.  (I think this should also apply to basic internal data types like tuples and sets but this is OT.)

**Comment by saulpw** [comment]
> I think over time I've come around in general to the idea that VisiData plugins are the way to extend VisiData further.

Funnily enough, I've been struggling with the overhead of coordinating several distinct VisiData repos myself, so we're planning to move to a more monolithic repo setup, especially for the "extra" code that I've written for VisiData (like vdplus and vdsql).  External plugins will still be supported via the standard mechanism that was added in v2.10, but we'll be deprecating the external Plugins Sheet, and leave discovery of new plugins to mechanisms outside of VisiData itself.

Since many of the "plugins" we've been talking about are very small (sometimes only a single command), I'm sure that having to manage a release infrastructure has been a barrier to other plugin authors as well. So we're planning to make it easier for people to contribute more "internal plugins" to the main VisiData repo, and include all plugins in the VisiData release, even if they have dependencies and/or are disabled by default.  And we'll make it as easy as the current plugins sheet for people to discover and enable internal modules, as well as enable/disable installed plugins.

> I propose a VisiData development guideline: When Python includes the batteries, VisiData should as well.

@frosencrantz That makes sense to me!

**Comment by anjakefala** [comment]
Thanks so much to @ajkerrigan for adding a toml loader. :tada:
