### ISSUE TITLE
Binding double keypress

### ISSUE THREAD

**Issue by ming-codes** [saulpw/visidata#1590]
**Small description**

```
TableSheet.bindkey('d', 'cut-cell')
TableSheet.bindkey('dd', 'cut-row')
```

Attempt to bind double key presses doesn't seem to work. But this somehow works for the built in `gg` command?

**Expected result**

`dd` to cut row

**Comment by saulpw** [comment]
Hi @ming-codes, this is because `g` is a prefix whereas `d` is not.  You can add custom prefixes (to `vd.allPrefixes`) if you really want to do this, but it might have unexpected consequences.   (And you won't be able to do `cut-cell` with a single `d`; how could it know when you're pressing `d` if you want to `cut-cell` or if it should wait to see if you want to `cut-row` with `dd`?)
