### ISSUE TITLE
Support XDG?

### ISSUE THREAD

**Issue by Freed-Wu** [saulpw/visidata#1600]
Now visidata install extensions to `~/.visidata` and use `~/.visidatarc`.

Why not use `~/.local/share/visidta` and `~/.config/visidata/config.py` (or other similar filename)?

Refer

- <https://pypi.org/project/appdirs/>, setuptools use it.
- <https://pypi.org/project/platformdirs/> fork from appdirs. black, virtualenv, jupyter_core use it.
- <https://github.com/pytorch/pytorch/blob/master/torch/_appdirs.py> copied from `appdirs`. Many projects requiring torch use it, e.g., torchvision.
- <https://github.com/mwaskom/seaborn/blob/master/seaborn/external/appdirs.py> Like above.

**Comment by anjakefala** [comment]
Support for XDG does exist: https://github.com/saulpw/visidata/commit/54dd817ede6b200cc3555a438a1c0d9b9cab9eef

I don't know about others and Saul, but I have been using `~/.visidatarc` and `~/.visidata` since the very start of the project, and it would be a -3 for me to switch where the files were located by default at this point. At minimum, all of our old issues where I recommended people update their `~/.visidatarc` would become out-of-date.

`~.,visidatarc` was I think inspired by other terminal looks like vim (`~/.vimrc`) and zsh (`~/.zshrc`).

**Comment by Freed-Wu** [comment]
> Support for XDG does exist

Oh, it's my fault which don't read the README :smile: And It should also be added to `man vd`. Closed.
