### ISSUE TITLE
Parsing key=value 

### ISSUE THREAD

**Issue by bornio** [saulpw/visidata#161]
How can I parse this [annoying] format with the awesomeness of Visidata? 

```
key1=value1, key2=value2, key3=value3
```

http://dev.splunk.com/view/logging/SP-CAAAFCK

**Comment by saulpw** [comment]
Hey @bornio..because of the quoting rules and everything, the best way would be to create a proper loader for it (would not be very hard, especially if there is already a Python module that will parse it).  If you just want something quick and dirty, see the attached .vd and sample data file.  Unfortunately it will only work if the cursor is on the row with the most elements when you do the initial split. It's not pretty but it might work in a pinch :)

BTW I would really love it if we made a loader for this format.  I'd be happy to help if you wanted to drive it.

[splunk.vd](https://github.com/saulpw/visidata/files/2117835/splunk.vd.txt)
[test.splunk](https://github.com/saulpw/visidata/files/2117836/test.splunk.txt)

**Comment by aborruso** [comment]
@bornio it's a classic input format, that you can convert in CSV with the great [miller](http://johnkerl.org/miller/doc/) in this way

    echo "key1=value1, key2=value2, key3=value3" | mlr --ocsv cat >./output.csv

With an input file

    mlr --ocsv cat input >./output.csv
