### ISSUE TITLE
Extract `histogram()` for easier patching

### ISSUE THREAD

**Issue by andycraig** [saulpw/visidata#1621]
The `histogram` function is nested within the `reload` method, which means that to patch `histogram` in a plugin you basically need to copy-paste the whole of `reload` to patch it too.

https://github.com/saulpw/visidata/blob/ad8b7f1b7eb55cf9dd986132b38cda5d57079962/visidata/freqtbl.py#L56-L59

As far as I can tell `histogram` doesn't use any variables from its parent method `reload`, so it seems like it should be possible to extract it to be a function of `freqtbl.py` or a method of `FreqTableSheet` without affecting any existing behaviour. This would make it possible to patch `histogram` by itself, as discussed here: https://github.com/saulpw/visidata/discussions/1608

Would you accept a PR to extract `histogram` out of `reload`?

**Comment by saulpw** [comment]
Hey @andycraig, yes, that sounds like it would be useful.  Thanks for offering!

**Comment by andycraig** [comment]
@saulpw Great! I will work on it.

**Comment by saulpw** [comment]
Hey everyone, I think maybe it's not clear how it could be done, so I went ahead and refactored it into a `HistogramColumn` subclass (see above).  So now you can override in your .visidatarc or plugin via

```
@HistogramColumn.api
def calcValue(col:Column, row) -> str:
    ...
```

**Comment by geekscrapy** [comment]
Is it possible to add an additional hist columns with this logic?

**Comment by saulpw** [comment]
@geekscrapy how many histograms do you need??

**Comment by geekscrapy** [comment]
@saulpw I saw this and thought I might be able to repurpose it to show gantt chart style data like my example in #924. It was fairly slow as an aggregator and only useful on Freq sheets

**Comment by geekscrapy** [comment]
@andycraig what was your usecase to override the hist?

**Comment by andycraig** [comment]
@saulpw Wonderful! I wasn't going to be able to get to this for at least another week or so, so thank you!

@geekscrapy The original use case is discussed here: https://github.com/saulpw/visidata/discussions/1608#discussion-4583002

**Comment by geekscrapy** [comment]
@andycraig ah right, thought you had a different usecase than @frosencrantz 👍

**Comment by frosencrantz** [comment]
@saulpw thanks for adding this!  I was thinking the solution would be something different, so it is great that you fix it.

@andycraig also thanks for you efforts to get this started.

@geekscrapy, I had forgotten about your great work in #924.   In addition to the suggestion in #1621, I was thinking it might be possible to show a time range in  a custom  histogram column.  Many times I add min and max aggregators on a datetime column, so that when I do a Frequency sheet it would be useful to have a simple graphical representation of the time range of a given row and be able to visually compare it with other rows.   Which is a simple gantt chart.

**Comment by andycraig** [comment]
I think this issue is done so I will close it. Thanks all!
