### ISSUE TITLE
[loader] - Unsure how to add columns dynamically

### ISSUE THREAD

**Issue by scrambldchannel** [saulpw/visidata#1632]
I'm trying to create a loader for log files produced by a nice product called tm1. I've already found visidata (:heart:) really useful for analyzing these kinda files by pipelining it with grep/cut etc but wanted to make it a bit cooler

1) A small sample representative dataset in that format.

e.g. there are metadata lines starting with `#` that I'm happy to discard and the other lines are uniformly comma delimited/double quoted but with a variable number of columns. 

```csv
#LOG_FORMAT=1
#LOGID=6
#LOGIV=
"","20200801185011","20200801185011","Admin","S","20200722131536","20200801185011","}DimensionProperties","}dimensions","LAST_TIME_UPDATED",""
#"","20200802084038","CubeSerialized: TM1py_tests_annotations: by Admin"
"","20200802084728","20200802084728","Admin","N","0","6","TM1py_Tests_Cell_Cube_RPS1","e2","e3",""
```

2) A basic Python script which queries and dumps the data (possibly using an external package).

I've hacked something half working at https://github.com/scrambldchannel/visidata-tm1-plugins/blob/master/plugins/vd_tm1log.py

Essentially, there's a range of columns 2 to 2 + n and I just want to be able to create new columns on demand. Where do I add the column? Within iterload or the class? 

Hopefully someone can point me to exactly where I'm being stupid ;)

All advice much appreciated! :)

**Comment by saulpw** [comment]
Hi @scrambldchannel !  Good questions.

You have the right idea: the static (always available) columns should be in the `columns` list in the class, and then dynamic columns that you want to create when loading, should be created during `iterload()` and added via `addColumn()`.

Because the rows coming out of the csv reader are just tuples, you should probably just yield those directly, instead of creating a separate object for each one.  Then you can add a standard `ItemColumn('name', colnum)` for each one.  If there are some you don't want to see, you can either hide them after the fact or just not add them in the first place.

For your `time` column, you can just leave it as text and pass `type=date` into the column and it should parse it into a VisiData `date` object.

**Comment by scrambldchannel** [comment]
Alright, thanks @saulpw! I think I've got enough to go have fun with :) I think you've also some of the questions I didn't get around to asking.

**Comment by saulpw** [comment]
Great.  I'll close this for now.  Let us know if you have any other questions!
