### ISSUE TITLE
no module named `openpyxl`

### ISSUE THREAD

**Issue by azinsharaf** [saulpw/visidata#1638]
**Small description**
opening `xlsx` file returns `no module named openpyxl` error. The `openpyxl` has been installed on the active conda environment.

OS: WSL (Ubuntu 22.04 LTS)
hardware: M1 Macbook Pro
python version: 3.9.13

**Expected result**
no error

**Actual result with screenshot**
If you get an unexpected error, please include the full stack trace that you get with `Ctrl-E`.

<img width="877" alt="image" src="https://user-images.githubusercontent.com/10101468/209457851-ea9e7454-6e5e-4bf7-a3ec-0f5207ff2238.png">

```
> conda list openpyxl
# packages in environment at /home/azin-wsl/anaconda3:
#
# Name                    Version                   Build  Channel
openpyxl                  3.0.10           py39h998d150_0    anaconda
```

**Additional context**
Please include the version of VisiData.
`saul.pw/VisiData v 2.2.1`

**Comment by anjakefala** [comment]
This is an environment issue! I see that your VisiData installation is not in the active conda environment. I am not familiar enough with how Python handles environment compartmentalisation, but this problem would probably be fixed by either:
* installing `openpyxl` in your user-level python3 environment
* installing VisiData in your active conda environment

**Comment by azinsharaf** [comment]
`sudo apt install visidata` installed it in a different location. It works now after uninstalling with `apt` and install it with `conda` on the active environment.
