### ISSUE TITLE
Trouble with pyenv after python was upgraded to 3.7

### ISSUE THREAD

**Issue by deinspanjer** [saulpw/visidata#164]
I'm struggling with my Mac environment here, and I would greatly appreciate it if you have any pointers.

I tried to run visidata today, and got the following error:
```dyld: Library not loaded: @executable_path/../.Python
  Referenced from: /usr/local/Cellar/visidata/1.2/libexec/bin/python3.6
  Reason: image not found
```

I tried reinstalling visidata using `brew reinstall visidata` and the error changed to:
```Traceback (most recent call last):
  File "/usr/local/bin/vd", line 10, in <module>
    from visidata import *
  File "/usr/local/Cellar/visidata/1.2/libexec/lib/python3.7/site-packages/visidata/__init__.py", line 7
    from .async import *
              ^
SyntaxError: invalid syntax
```

So I started digging and I found that it seems something has gotten goofed up between having pyenv on my system (which had not yet had an explicit 3.7.0 installed) and having the Homebrew version of python 3.7.0 installed via brew upgrade yesterday.

```
which python3
~/.pyenv/shims/python3

pyenv
pyenv 1.2.5

echo $PATH
/usr/local/Cellar/pyenv-virtualenv/1.1.3/shims:~/.pyenv/shims:/usr/local/bin:~/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

pyenv version
system (set by ~/.pyenv/version)

python3
Python 3.7.0 (default, Jun 29 2018, 20:13:13)
```

So I tried a few different fumblings and finally I decided to try removing pyenv from the path entirely.  Did that, reinstalled visidata, but still the same error about invalid syntax.

I understand this likely isn't a "visidata" problem, but if there is anything you can suggest, I'd greatly appreciate it.

**Comment by anjakefala** [comment]
Hi Daniel!

Thank you so much for bringing this to our attention! :100: 

Our current hypothesis is that the original error occurred because brew removed Python 3.6 and replaced it with Python 3.7. The VisiData installation could no longer find the 'image' for Python 3.6.

This was 'fixed' when you reinstalled VisiData, however the next error that occurred was due with the fact that Python3.7 introduced `async` as a [reserved keyword](https://docs.python.org/3/whatsnew/3.7.html). We currently have a file `async.py` and a decorator `@async`. Both will likely need to be changed. 

The things we can do:

1) We find a workaround using brew.
2) We find a workaround using pyenv on a system with a brewed and non-brewed python.
3) We release a patch where this will not be an issue anymore.

We will do (3), but it may be a while.

**Comment by deinspanjer** [comment]
Wow.  I'm glad it surfaced something that will be relevant to others.  I'll keep an eye out for new bits to test.

**Comment by anjakefala** [comment]
@deinspanjer 

I do not hear about installation failures very often, and I am sure they happen, so I was very, very grateful for this issue. =)

We merged a tentative fix into stable and are going to be testing it and releasing over the next while.

If you want to play with it, this should do it:

```
git clone https://github.com/saulpw/visidata.git
cp -r visidata/visidata/* usr/local/Cellar/visidata/1.2/libexec/lib/python3.7/site-packages/visidata/
```
With the caution that our automated tests ran fine but I have not gone through the full testing and release process yet. :)

**Comment by anjakefala** [comment]
@deinspanjer It is released and in homebrew! :D Please let me know if you encounter any other issues. ^^

**Comment by mycaule** [comment]
It is possible to install visidata on a python2 environment. Then it breaks at runtime.

Maybe we can disallow the package to be installed with python2 in the first place.
