### ISSUE TITLE
pgdn hides the rows

### ISSUE THREAD

**Issue by cool-RR** [saulpw/visidata#1661]
If you hit pgdn close to the end of the sheet, it'll show you just the last row, and none of those preceding it. I think it should show as many rows as possibly fit in the screen while still showing the last row of the sheet as the last row on the screen.

**Comment by saulpw** [comment]
I agree that filling the screen with rows is generally desirable.  However, there are some other design considerations in play; for instance, I think it's more important that pressing PgUp after pressing PgDn should be an exact inverse.  If it worked as you suggest, then this would never be true for the final page.  As it is, it should only have the behavior you say (only one row visible) if you PgDn without a full page of rows visible.  This is intentional so that you can set the top row so that you *don't* have a full page, if you want.  If we forced a full page of rows (or prevented PgDn when the last row was already on the screen) then you could never do this.  As it is, you can always press End or `gj` to go to the bottom-most row, and it will fill the screen with rows.

**Comment by cool-RR** [comment]
I understand, thanks.
