### ISSUE TITLE
Row of nulls in csv that came from csvbase

### ISSUE THREAD

**Issue by calpaterson** [saulpw/visidata#1704]
**Small description**

I get a row of unexpected nulls when using a csv from csvbase

**Expected result**

No row between rows 21 and 22

**Actual result with screenshot**

![image](https://user-images.githubusercontent.com/224844/215052189-8cb8a85c-acd4-4028-9d07-0ceddc238a82.png)

**Steps to reproduce with sample data and a .vd**

```shell
vd https://csvbase.com/r-datasets/airquality
```

```
#!vd -p
{"longname": "open-file", "input": "https://csvbase.com/r-datasets/airquality", "keystrokes": "o"}
```

Please attach the commandlog (saved with `Ctrl-D`) to show the steps that led to the issue.
See [here](http://visidata.org/docs/save-restore/) for more details.

**Additional context**

Python 3.10 on debian linux

Is this a bug in visidata?  Or a bug in csvbase?

**Comment by saulpw** [comment]
This is apparently a bug in the `requests` library: psf/requests#5540.

The issue is that for this particular (lucky/unlucky) csv, the `\r\n` between line 21 and 22 straddles bytes 512 and 513, which means that the first chunk ends in `\r` and the second chunk starts with `\n`.  So the iterator splits up the first chunk and yields the final line, and then when it starts to split up the second chunk, it also yields an additional empty line.

I agree with @vitidev from the requests bug, that streaming lines from an HTTP request with `iter_lines()` should act identically to iterating over lines from the same file on disk.  To fix this bug, we'll have to remove the `requests` dependency and rewrite the streaming functionality ourselves.

**Comment by anjakefala** [comment]
We switched over to `urllib` which appears to have fixed this! Please re-open, if you are still running into problems.

**Comment by calpaterson** [comment]
Nice, I was able to reproduce this on v2.11 and not with the latest git.  Many thanks!!!
