### ISSUE TITLE
The `reload-every` command isn't present in the commands list or is missing documentation

### ISSUE THREAD

**Issue by keck-in-space** [saulpw/visidata#1712]
**Small description**

I would like to have my data reload every few seconds using the `reload-every` command [here](features/reload_every.py). I do not see that command in the commands list inside Visidata and do not see any documentation on the Visidata site when I try to search for it.

**Expected result**

This feature is well documented and present in the commands list.

**Steps to reproduce with sample data and a .vd**
Search for the command `reload-every` in the documentation of command list.

**Comment by saulpw** [comment]
Hi @keck-in-space!  That command has only recently been added to VisiData, and isn't part of a release yet--I think it's not even imported yet in the version of `develop` that's on Github!  It's importing for me locally, but that's because I'm quite actively working on a good way to manage extra little features like this, which are easy enough to write (`reload-every` is only a few lines of code), but of course even the smallest feature requires those extra niceties like documentation and menu placement.  We'll get there before we release the next version (which will be 3.0, precisely because we need to change how we deal with all these extra little features), but until then, if you want to use a new feature like this, you may have to read the source code or experiment a little (in this case, you can try `import features.reload_every` in your .visidatarc, which should at least make the command available).

As long as you're here, how do you feel about helping us with some documentation for this particular feature?  It would be much appreciated, since you'll have just figured out how to use it (and therefore what you would have wanted to know), and it would also help us on our path to figuring out a more scalable process and structure for our documentation.  If you come by our Discord at https://visidata.org/chat, we can chat and we can figure out what should go where.

**Comment by keck-in-space** [comment]
Thanks @saulpw this is very helpful. I don't use discord for privacy reasons, but I will take a look at using this feature and look forward to seeing how these types of features evolve.
