### ISSUE TITLE
[sqlite schema]  Add metadata query for SQLite columns 

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#1719]
Related to Saul's next SQLite Deep Dive request: https://github.com/saulpw/visidata/issues/860

Simon Willison has documented some general SQLite queries which could be added to VisiData:
- List of all the tables/columns: https://til.simonwillison.net/sqlite/list-all-columns-in-a-database 
  - This learning includes a reference to a query litecli uses for this purpose
- List of all supported functions: https://til.simonwillison.net/sqlite/pragma-function-list or https://til.simonwillison.net/sqlite/function-list
This provides some generic details about tables/columns.

Simon has gone deep into SQLite for Datasette and this could be useful.

**Comment by saulpw** [comment]
For a list of all columns in a database, I go to the table index, press `gs gEnter gC` which loads all tables and then opens the all columns sheet.  This seems easier than running the monster meta-query mentioned in that post.

As for `pragma_function_list()`, it's a neat sqlite tip, but I don't think it's useful enough by itself to put in VisiData as a special feature.  But I agree you'd want to be able to get the list into VisiData easily.  So I added an `exec-sql` command to sqlite sheets, so that you can enter in any query (including `select * from pragma_function_list()`) and see the results.
