### ISSUE TITLE
[www] Create favicon for visidata.org

### ISSUE THREAD

**Issue by anjakefala** [saulpw/visidata#172]

**Comment by deinspanjer** [comment]
What would you think about crowdsourcing this on a site like https://www.designcrowd.com/ ?  I'd be willing to sponsor with < $100

**Comment by saulpw** [comment]
Hey @deinspanjer, that's an interesting idea, and very generous of you.  Do we need to have a conceptual direction outlined before starting that process?  I've never paid for crowdsourced design like this before.

**Comment by deinspanjer** [comment]
It certainly doesn't hurt, but it isn't strictly necessary.  Here is the pitch I was thinking about:

FavIcon needed for the VisiData project's website.  If a variant of the design is also suitable for a larger app icon, that would be great.

Link to project's logo: https://github.com/saulpw/visidata.org/blob/master/vdlogo.svg
VisiData is an interactive multitool for tabular data. It combines the clarity of a spreadsheet, the efficiency of the terminal, and the power of Python, into a lightweight utility which can handle millions of rows with ease.

Theme ideas:
Something that matches well with the logo is a good start.  Images that evoke the concepts of tabular/relational data or spreadsheets are most interesting.  Note that VisiData is run entirely within a terminal (command prompt) rather than having a standalone window such as you'd see with an application like Excel, so an image that ties into that would be a plus.

**Comment by saulpw** [comment]
That sounds good to me!  Do you want to just run with this and see what comes out of it?

**Comment by deinspanjer** [comment]
Sounds good. I'll do so.  Obviously, I'll make sure you have all copy rights to whatever  comes out of it.

**Comment by anjakefala** [comment]
You are lovely @deinspanjer :purple_heart: =)

**Comment by saulpw** [comment]
Maybe it's also worth it to mention that `vd` is the actual command name?

**Comment by deinspanjer** [comment]
I'll add that to the brief now.  As soon as any proposals come in, I'll share links to them here.

**Comment by deinspanjer** [comment]
https://www.designcrowd.com/vote/first-poll-promising-designs

**Comment by deinspanjer** [comment]
https://www.designcrowd.com/vote/poll2visidataicons

**Comment by saulpw** [comment]
Many of these are very close to the [vim logo](https://commons.wikimedia.org/wiki/File:Vimlogo.svg), which I think we should avoid.  Also many of these seem like they wouldn't render well at 32x32.  Maybe we should be more explicit about using it as a favicon?

**Comment by deinspanjer** [comment]
I was pretty explicit about that, but I agree on the feedback, and I've noted such on my feedback to the designers.

I suspect the issue is that the first pool of designers are the lower-tier trying to get something in quickly in the hopes of a quick and easy close.

That said, I did like this one in particular: https://dcassetcdn.com/design_img/3602876/687234/687234_19747419_3602876_64611145_image.jpg

I will continue pushing toward more favicon friendly designs and suggest people avoid just the "V" as that conflates with vim.

**Comment by deinspanjer** [comment]
https://www.designcrowd.com/vote/3votingpolliconforopensourcevisidataprojectaninteractivetoolfortabulardata

**Comment by deinspanjer** [comment]
I've closed the previous polls and opened this one that captures my favorites.  I don't believe I excluded anything that was voted 3 stars or higher by anyone, but if there is another you would like to be in this poll, please let me know.

https://www.designcrowd.com/vote/4votingpolliconforopensourcevisidataprojectaninteractivetoolfortabulardata

**Comment by deinspanjer** [comment]
If we settle on one or two choices, we can definitely ask for further revisions and tweaks from those designers.

**Comment by saulpw** [comment]
I liked two of them, the one you pointed out above, and the one with two stacked "sheets".  What do you think about adding some color to them?  Or should the logo and favicon stay monochrome?

**Comment by deinspanjer** [comment]
I love a logo / app icon with some color, but I do find that for website favicons, black only tends to give the best visibility.  The github favicon is a good example there.

Not strongly tied to it though, if you'd like to see some alternatives, I'm happy to ask.

With the designs that have been submitted, I think we can pretty easily come out of this with two icons, one favicon and something larger that could be used in the project logo, if you want.

**Comment by deinspanjer** [comment]
Are you leaning toward one or the other more?  I think I'm pretty tied on them.  I like the eye one because it feels visually distinctive while still a little abstract.  I like the stacked sheets because it ties very strongly into the purpose and operation of the app.

**Comment by anjakefala** [comment]
>  I like the stacked sheets because it ties very strongly into the purpose and operation of the app.

I voted a preference for the stacked sheet one for this reason!

**Comment by saulpw** [comment]
I like the stacked sheet one too, I think (similar reasons).  Looking at it more, I think it would be better if there were 4 or 5 "rows" on the bottom sheet (instead of 3) packed closer together (so only 2-3 pixels spacing between them instead of the same height rows and spacing).  Also @anjakefala suggested that it might be good to have some indication of columns on the underlying sheet, which I think is a good idea if it's not too busy/cluttered.  Can we get the designer to make those changes?  That one seems like it would work pretty well like that.

**Comment by deinspanjer** [comment]
Okay, I'm going to go ahead and lock it down on that one and then get the designer to give us some options.

**Comment by KingCozy** [comment]
Hi 
Thanks again for selecting my design I will be online to try make sure I can attend to the changes as per your requests

KingCozy (The designer from Designcrowd)

**Comment by KingCozy** [comment]
![visi6](https://user-images.githubusercontent.com/36403756/45885804-4665e280-bd6c-11e8-9ab1-52f9ff3e1519.png)

**Comment by saulpw** [comment]
Yeah I like it. Let's convert it to favicon 32x32 and see how it looks.

**Comment by KingCozy** [comment]
![untitled-3](https://user-images.githubusercontent.com/36403756/45917039-3f9aa680-be24-11e8-85a7-818faa8f4975.png)

**Comment by saulpw** [comment]
Great, that's a lot crisper than it seemed in the other picture at that size.  What do you think, @deinspanjer and @anjakefala, should we use this as the favicon?

**Comment by anjakefala** [comment]
That was my top vote and the adjustments are wonderful. =)

**Comment by KingCozy** [comment]
Thank you for the feedback, I can have the icon ready in svg and other formats as soon as you all approve on the final look

**Comment by deinspanjer** [comment]
Alright! I'll close it out this now. :)

**Comment by KingCozy** [comment]
Great :) let me upload the files required on designcrowd if you need to contact me I will be available here or designcrowd

**Comment by KingCozy** [comment]
Thank you for approving the payment I have uploaded the files to designcrowd, I can drop the zip folders here if need be, it has been a pleasure to create this icon for you

Kind regards
Cozy

**Comment by KingCozy** [comment]
[source.zip](https://github.com/saulpw/visidata/files/2410735/source.zip)
[print.zip](https://github.com/saulpw/visidata/files/2410736/print.zip)

**Comment by deinspanjer** [comment]
Thank you again KingCozy. :)

**Comment by deinspanjer** [comment]
@anjakefala @saulpw Is there anything more you need from me to finish this up?

**Comment by anjakefala** [comment]
@deinspanjer Hi! =) Once again thank you so much for driving this.

The favicon has been added [here](https://github.com/saulpw/visidata.org/blob/master/static/favicon.ico).

You can get a preview of the favicon live [here](http://beta.visidata.org/).

We are currently in the process of updating [visidata.org](https://github.com/saulpw/visidata.org). I think the current consensus is that we will close this issue once the new version of the website has been shipped.

**Comment by anjakefala** [comment]
@deinspanjer We are live! https://visidata.org/ :tada: =) =)
