### ISSUE TITLE
Copying and pasting a row ignores values from manually added columns

### ISSUE THREAD

**Issue by daviewales** [saulpw/visidata#1727]
**Small description**

If I create a new column within Visidata (`za` or even the default new column from `Shift+A`), enter a value, then yank `y` and paste `p`, the pasted value for that column is null.

**Expected result**

The pasted row would be the same as the yanked row.

**Actual result with screenshot**
![image](https://user-images.githubusercontent.com/2499066/217152420-fe325b31-4988-47d6-bb64-fed264eb90ac.png)

**Steps to reproduce with sample data and a .vd**
[copy-paste-row.vdj.zip](https://github.com/saulpw/visidata/files/10671676/copy-paste-row.vdj.zip)

**Additional context**
Please include the version of VisiData.
v2.11

**Comment by anjakefala** [comment]
This is actually a known limitation of VisiData! I documented it here =) https://www.visidata.org/blog/2020/row-major/

**Comment by daviewales** [comment]
If I understand correctly, this is because rows which are read from a file are row-major, and stored in Visidata as rows, but the columns which are added interactively are column-major, and stored as columns separately?

I assume that `SettableColumn` is column-major to allow creating columns instantly on huge datasets?

I can see that the other issue was closed as 'document and close', and the documentation says "...it can't be fixed."
But I'm very slightly sceptical about the word "can't".

Would it be possible to elaborate the trade-offs which made this the more desirable choice?
I can imagine the main trade-off would be speed vs. surprise.
If you add code to copy both the regular rows and the SettableColumn rows, then for very large selections you'll be doing lots of column-minor operations to copy and paste all the row data into the pasted rows in the SettableColumns.
This would make the copy slower than usual.
However, it would be less surprising to the user!

**Comment by saulpw** [comment]
Hi @daviewales, we need to make a distinction here between "data values in the rows" and "row object references".  It's vital to VisiData's architecture that we treat rows as whole units, and columns as 'views' into those units. This enables many features and no small amount of performance.

When we copy/paste rows, we can either copy/paste the row objects or the data values.  Currently, when rows are copied to the clipboard, it copies the row references and the list of visible columns.  Then when `paste-after` is executed, it makes a copy of each row object and appends that to the sheet.

Now, this actually allows some neat low-level hacks; did you know you can copy columns from one Columns Sheet to another Columns Sheet?  But this is only occasionally useful and requires a deep knowledge of the architecture and how the objects are used; you have to copy columns from/to compatible sheets.  I've done this a few times and with great glee.

But I think what most people want and expect, is to copy/paste the *values*, instead of the rows.  However, this raises some thorny questions.  Like: if you make a duplicate sheet and rearrange the columns, should the values be pasted blindly in the original sheet order (as Excel would), or should they be matched to the new column order (by name probably)?  If we paste based on position, how should we deal with something like a derived column being added to the new sheet, as trying to set the value for a computed column will fail?

I'm definitely open to changing the clipboard behavior to be less surprising for people.  It would require a general overhaul though, and we'd want to think through cases like the above so that the whole feature feels coherent.

**Comment by daviewales** [comment]
Thanks @saulpw, that's very helpful. I hadn't considered copying between sheets, only copying rows within a sheet, which is slightly easier to reason about. It seems we might need different types of paste -- paste by reference, paste by column, paste by value. I can see that pasting between tables appears to paste into matching columns, even if they are out of order which is nice. I'll close this and link to #413 for discoverability.

**Comment by midichef** [comment]
I found this thread while searching for discussion of the visidata philosophy of the architecture of columns and rows. Since it was written, the copy/paste behavior has changed. On v3.1 it works as expected, the pasted row has the value of the copied row.

For future reference, I'm linking to [saulpw's October 2023 discussion of the design decision relating to the change](https://github.com/saulpw/visidata/issues/1377#issuecomment-1760521561).
