### ISSUE TITLE
[undo-last] Undo is global, but I feel that undo steps should be per Sheet

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#1780]
**Small description**
Opening a new sub Sheet, make some edits, then close it and go back to the old sheet, I sometimes want to undo something that I previously did on the original sheet. However, if I use `undo-last` the undo steps are replayed from the sub Sheet.

**Expected result**
To be able to `undo-last` as per the action for the current sheet.

There are 2 types of behaviour I have seen:
1. The undo action applies to the sheet on which thee action was taken, but this could be a currently hidden/not currently shown sheet
2. If the previous sheet is closed, the previous sheets actions are attempted to be replayed to the now, new sheet which probably doesn't make sense

**Steps to reproduce with sample data and a .vd**
1. `# ls -l | vd -f txt`
3. stoggle-rows
4. dup-selected
5. sort-asc
6. sort-desc
7. jump-prev
8. undo-last
9. Note that the undo action is applied, but to the _now_ hidden sheet

**Additional context**
v2.12dev

**Comment by saulpw** [comment]
Thanks for the bug report, @geekscrapy !  Undo actually *is* per-sheet, and this was a subtle bug that affected duped/copied sheets.  Thanks especially for including the exact repro steps, as I was about to dismiss this bug after reading the title/description, when I decided to just try the repro and saw the actual incorrect behavior you witnessed.  Should be fixed in develop now.
