### ISSUE TITLE
undo `zd` cannot remove `[M]`

### ISSUE THREAD

**Issue by Freed-Wu** [saulpw/visidata#1800]
**Steps to reproduce with sample data and a .vd**
```sh
echo 'a\tb\tc\n1\t2\te' > test.tsv
vd -N test.tsv
```
Press `zd` to delete one cell then use `U` to undo. Now the table is same as original table. However, `sheet.modifiedStatus` still be `[M]`.

**Expected result**

`sheet.modifiedStatus` still be empty string.

**Comment by anjakefala** [comment]
What a cool bug!

This actually applies to any command that calls `setValue`. `setValue` sets `hasBeenModified` to `True`. 

The undo for `hasBeenModified` gets created after the undo for `zd`. We undo the `hasBeenModified` change, and it gets set back to `False`.

But then, the undo for `setValue`/`zd` also call `setValue`, and then `hasBeenModified` gets set back to `True`.

I encountered this before. The `undo` for `delete-row` called `add-row` which has its own undo schematics that mucked with things. In that case, the fix was pretty tricky, and it might be for this one as well. I am going to look into it!
