### ISSUE TITLE
[option] Global case sensitivity toggle

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#1806]
Original discussion: https://discord.com/channels/880915750007750737/880915984481939466/1085107394842984468

When working with Windows paths filenames etc and freqing them I get a lot more rows than if they were case insensitive. However when looking at Linux data, I need case sensitivity (as case matters with paths and file names etc.). I could change each column to be case insensitve with something like `=str(curcol).casefold()` but with 10s of columns I often forget... It might be nice to have a global setting for string evaluations and case sensitivity?

It would mainly be for any string comparison features, freqsheet binning, gotonext, and regex eval

**Comment by saulpw** [comment]
Thanks for creating this issue, @geekscrapy .  One thing, when you link to a Discord discussion, please also quote the relevant bits here directly, as the link will stop working in short order (or for people who can't/won't use Discord).

**Comment by frosencrantz** [comment]
I'm not on Discord.  I agree it would be helpful to have some sort of summary of the relevant bits from the discussion in the wishlist request.

I've been somewhat interested in [smartcase] mentioned in  https://github.com/saulpw/visidata/issues/682  

One thing I have been thinking recently was it would be useful if a user could just specify a default value for regex values, which I would  use `(?i)` which would allow the user to do a case insensitive search by default.  If the user hits `^K` or deletes the leading prefix, they would get case sensitive search.  I find this hacky but practical, but it would work within what VisiData can already do.  I've done something like this with my editor for configuring patterns, and it works.

This suggestion wouldn't solve all the problems @geekscrapy is mentioning like for freqsheet binning, but might work for regex patterns entered by the user.

[smartcase]: http://vimdoc.sourceforge.net/htmldoc/options.html#'smartcase'

**Comment by anjakefala** [comment]
The Discord conversation:

geekscrapy 14/03/2023 00:49
Anyone got an idea of how to globally set string comparisons to case insensitive? When working with Windows paths filenames etc and freqing them I get a lot more rows than if they were case insensitive. However when looking at Linux data, I need case sensitivity. I could do it for each column each time I open a new sheet, but with 10s of columns I often forget... It might be nice to have a global setting for string evaluations and case sensitivity?
I guess I only really need it on freq sheets so maybe I could add the option there as a toggle?

cool-RR 14/03/2023 04:04
Is there a minimal recipe for loading a VisiData sheet as a Pandas DataFrame?

saulpw 14/03/2023 10:30
@geekscrapy which commands?
I"m guessing that the ones you're using are the regex commands, and so you want to remove I from options.regex_flags
@cool-RR yeah.  from visidata import vd; vd.view_pandas(df) 

geekscrapy 14/03/2023 11:46
So, it would mainly be for any string comparison features, freqsheet binning, gotonext, and regex eval

saulpw 14/03/2023 11:47
ah gotonext, like with > ?
so that's a lot more than just regex, hm

geekscrapy 14/03/2023 22:51
yea, that's the thinky part, I probably dont appreciate what my Q actually affects. I was hoping it could be done something like what we have with maybeClean, but I'm pretty sure I can't just do it via API calls 

saulpw 15/03/2023 00:46
yeah it would have to be an options that's applied in multiple places.  not un-doable though, and it makes sense that this would be a special option

geekscrapy 15/03/2023 06:19
ok, I'll "Feature request" it! maybe I'll take a crack if I get a sec

**Comment by anjakefala** [comment]
@geekscrapy I believe this commit https://github.com/saulpw/visidata/commit/3f314e8323cb2e4cc093410d5e4a4c0890ca38d5 addresses this feature request!

Please try it out, and let us know how it goes. =)
