### ISSUE TITLE
[date] Unix timestamp strings must be frozen first as int to be parseable

### ISSUE THREAD

**Issue by yahooguntu** [saulpw/visidata#1819]
I have a CSV file whose first column is a Unix timestamp. For example, "1679614100" corresponds to "2023-03-23 11:28:20 PM" When I open the file and set that column type to "date" using the @ key, it is unable to be parsed as a date.

If I set the column type to int using the # key, then edit a cell, that cell is then correctly parsed as a date if I change the column type to date. This works even if I don't change the cell contents during the edit; just pressing "e" and "<return>" makes it parseable.

Note: This bug also applies to Unix timestamps with fractional seconds (e.g. "1679614100.5"), the difference being I have to convert the column to a float first, instead of an int. The fractional seconds are parsed correctly after that, though of course I have to set disp_date_fmt to see them. I can provide examples of that too if needed.

Screenshot of opening the example and setting the first column to date type:
![Screenshot from 2023-03-23 18-48-26](https://user-images.githubusercontent.com/7928556/227388911-8f0da33a-9b20-4805-b22c-bc39c5c4b5b4.png)

Screenshot of the same, but first editing the topmost cell in the "Time" column:
![Screenshot from 2023-03-23 18-50-28](https://user-images.githubusercontent.com/7928556/227389213-00d8e99e-37d7-4039-9990-4085a099345c.png)

Sample file is attached, along with commandlog to reproduce the second screenshot.
[example.csv](https://github.com/saulpw/visidata/files/11057292/example.csv)
[example.vdj.txt](https://github.com/saulpw/visidata/files/11057294/example.vdj.txt)

Using VisiData v2.11, Python 3.9.2

**Comment by saulpw** [comment]
Type the column as int using `#`, then `'` to freeze the column values as int, then you can set the type of the frozen column to date with `@`, and it should be able to parse the numbers as int values.

This particular workflow is a bit nonintuitive, I would agree.  Maybe we could change the logic in the `date` constructor to check for strings that look like time_t, instead of just the type as it currently does.  And/or this functionality could be added to python-dateutil itself.

**Comment by saulpw** [comment]
Kondo'ed for now.
