### ISSUE TITLE
[help-commands] Help shortcut not working on WSL

### ISSUE THREAD

**Issue by simchuck** [saulpw/visidata#183]
I just installed the latest release (1.3.1) under WSL, and reviewing the "getting started" tutorial.  Doesn't seem that the help shortcuts (`^H` or `z^H`) are working for me, although I can get the man page with a `<F1>` press.

**Comment by anjakefala** [comment]
Hi @simchuck! =)

Thanks for letting us know. We do not test on WSL, so it is really helpful to discover issues unique to it.

To help us diagnose the problem, can you please answer the following:
* Which terminal are you running on WSL?
* What happens when you press `Backspace`? 

**Workaround**
I am glad you were able to find a manpage workaround with `<F1>`. For now, you can obtain the `help-commands` page by typing `Space` followed by `help-commands`. `Space` executes a command via its longname.

**What we suspect is causing the issue**
We actually found out that on the MacOS `^H` maps to `Backspace`. As result of that, we also created an alias between the two keystrokes (https://github.com/saulpw/visidata/commit/73236cebeceee148569a716ba3f6a818d8958eaa). I would not be surprised if `^H` is also mapped to a terminal command on WSL.



🐝

**Comment by simchuck** [comment]
I am using the wsltty terminal, v. 1.9.0.2

<BKSP> gives the message `no command for "^?"`

**Comment by saulpw** [comment]
What does Ctrl+H do, @simchuck ?  Does it show any keystroke on the status line?

We might just have to bind help to all of `^H` and `F1` and Backspace, and maybe `^?` (DEL) while we're at it because apparently that's what wsltty gives for Backspace.  At least Backspace can be the universally-supported help keystroke :D

**Comment by anjakefala** [comment]
For now, could you try adding the following to your `~/.visidatarc`:

```
bindkey('^?', 'sysopen-help')
bindkey('z^?', 'help-commands')
```

Then you should be able to access the man and command list sheets respectively by typing `Backspace`/`zBackspace`.

**Comment by simchuck** [comment]
Nothing with Ctrl-h

I can make do with it as is, just wanted to report this so you were aware.

On a related note, I am very excited about this project and would be
interested in helping out in some way.  I am relatively early in my
education with Python, although I have done a bit of coding before in
FORTRAN (many years ago), and more recently VBA.  I am also just getting
into learning proper data science, but have done some pretty decent
analysis on time-series data under Excel.  Contributing to visidata would
be an excellent project to help me develop in both of these areas, and
perhaps I could bring a different perspective in some cases.

If you have any work that you think I might be able to assist with, please
let me know.

Thanks,
Charles

**Comment by saulpw** [comment]
Hey Charles, thanks for the offer!  We'd love your help. There are a couple of directions we could go, depending on your interests.  Which areas of VisiData do you feel could use improvement?  What do you currently use VisiData for, and what might you like to use VisiData to do?

There are a couple of small tasks you could start with now, to get your feet wet and get a feel for our development process and style.  One is #169, which should be pretty straightforward and would use a little Python.  We're planning to ship 1.3.2 with a few bugfixes next Friday and if we had a fix in hand for 169 I'd be sure to include it.  See if you can figure out our development process from our online documentation, and if it's not clear, file an issue or send me email at vd@saul.pw and we can work together to make it better.

Cheers,
Saul

**Comment by simchuck** [comment]
I know this issue has been closed, but I was just playing around a bit a
discovered some interesting quirks for my configuration.

I am using WSL under Windows 10, wsltty terminal.  I typically startup in
tmux (v2.7) for my command line work, and that seems to be relevant to the
issue with visidata's Ctl-h binding.  The Ctl-h binding does seem to work
properly when I run visidata outside of tmux.

With WSL | wsltty | tmux2.7 | visidata 1.3.1:
- Ctl-h does nothing, including no message
- Ctl-Alt-h briefly displays the message "no command for "^[", then opens
the man page vd(1) - Quick Reference Guide
- after quitting the man page, on returning to visidata the message "no
command for "^[" flashes very briefly

**Comment by saulpw** [comment]
Thanks for the followup, @simchuck.  It sounds like tmux is intercepting Ctrl+H so that VisiData never gets it.  Maybe your `tmux.conf` is binding it to a secret action?
