### ISSUE TITLE
Could not select rows in unfurled array list with vdsql

### ISSUE THREAD

**Issue by radostyle** [saulpw/visidata#1857]
I ran through the clickhouse recipe demo from the video but couldn't replicate the last step.

pip install vdsql
vdsql 'clickhouse://explorer@play.clickhouse.com:9440/?secure=1'
/recipe
selected last column
zM to unfurl
Shift-F to get frequency table
|salt to select all the salt records
" to create a new sheet with just salt records
/saltpeter
Enter to select them, but errored

I can see "TypeError: Arguments with datatype !array<!string" in the UI, but the rest of the message is cutoff.

**Comment by radostyle** [comment]
<img width="1474" alt="image" src="https://user-images.githubusercontent.com/151909/208228278-a0158540-90e8-434b-bb08-921f72340049.png">

**Comment by saulpw** [comment]
Hi @radostyle, thanks for filing this issue.

You can view the whole error message with `Ctrl+E` which may provide more context or clues.

The particular error you're seeing may be due to a version mismatch; possibly pandas?  It seems that pandas 1.5.x works better than 1.3 or 2.x, and I've updated the vdsql requirements to reflect that.

In any event, I can walk through the demo fine, at least on the develop branch (though the functioning clickhouse URL now seems to be `clickhouse://explorer@play.clickhouse.com:443`).
