### ISSUE TITLE
Postgres schemas, i.e., namespaces, need to modelled

### ISSUE THREAD

**Issue by cstork** [saulpw/visidata#1858]
Postgres has the useful `--postgres-schema` option to specify the namespace it's navigating within. However, that makes is hard (impossible?) to work across namespaces which is not unusual at all in case of PG DBs.

I'd suggest to model the namespace (e.g. Postgres Schema)

  - either explicitly as a column `namespace_name` 
  - or more implicitly by supporting a single dot `.` as part of qualified identifiers. 

The first approach seems to be appropriate if there are many other supported DBs that support these kind of namespaces, e.g., DuckDB.
The downside is obviously that things become unwieldy and too overloaded for the common use-case.

The second approach seems much more appealing. It is also compatible with PGs use of the seach_path variable in case no schema is given. (The search_path would replace the postgres-schema option.)
The downside is that in case of PG the qualified identifiers have to be appropriately quoted, i.e., the schema-part and the name-part need to be separately quoted. Don't know if that problematic.

**Comment by saulpw** [comment]
Hey @cstork, this is probably more of an Ibis issue in how it handles Postgres schemas.  I think we should incorporate the schema (and other namespace-like things from other DBs) into the connection URL, and when we list tables in the database in vdsql, only list those in the specified schema.  If no schema is specified, we can either list from the default schema, and/or provide some option to ignore the schema and list all tables in all schemas.

This seems best to me, as the alternative would be to specify multiple connection URLs with different given schemas, and allow joins between tables from different schemas (which might be challenging for Ibis).

**Comment by saulpw** [comment]
Okay, @cstork, getting back to this, I see now that you're trying to use cross-schema references. 

I was talking with @cpcloud today, and we should be able to use Ibis' `con.table(tblname, schema="schemaname")` to get a reference to a table in a different schema, and since vdsql only uses this `con.table()` in one place in the code, we should be able to handle this, if we ever have a table from another schema.

However there doesn't appear to be a way to get a list of schemas from a database that supports them, and thus no way to list all tables in all schemas.  Referencing ibis-project/ibis#6331, it looks like Ibis is working on how to enumerate schemas, so when that functionality is added, we can revisit this.  If you have a concrete use-case before then we can try to find a workaround before then.

Kondo'd for now.
