### ISSUE TITLE
gzY sometimes doesn't copy selected rows

### ISSUE THREAD

**Issue by Mikee-3000** [saulpw/visidata#186]
Hello :-) 
first and foremost, thanks for making a great piece of software!
I have an issue with clipbard:
When some rows are selected, pressing gzY should copy the values from the selected column and the selected rows into the clipboard. Most of the time it doesn't copy anything, some times it works (I can't find a pattern).
this is on Linux 
my `clipboard_copy_cmd` is set to `xclip -selection clipboard`
I have the same issue when using xsel
zY works as expected
this is visidata version 1.3.1 running in Anaconda and in venv 
Thank you
Mike

**Comment by Mikee-3000** [comment]
On further reasearch, it seems to actually add an empty entry into the system clipboard

**Comment by saulpw** [comment]
Hi @Mikee-3000, thanks for the bug report.  You're right, that it should copy the cells for selected rows in the current column.  Looking at the code, `gzY` sources from "clipcells" which is only set with zy/zd/gzd/gzy.  So the workaround for 1.3.1 is to first `gzy` and then `gzY` will copy those cell values (which may be why it was working for you sometimes).  This will be fixed in the next version.  (Also changed so that it joins with a newline instead of a space.  Let me know if you need it to be configurable.)

**Comment by Mikee-3000** [comment]
Oh wow, thanks for the fast response! The work around works, I'm looking forward to the update. Joining with newline will work great for me.
