### ISSUE TITLE
[limits] `z"` command changes the generated SQL unexpectedly

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#1862]
### Discussed in https://github.com/saulpw/visidata/discussions/1579

<div type='discussions-op-text'>

<sup>Originally posted by **frosencrantz** October 29, 2022</sup>

Since discussions are not setup on https://github.com/visidata/vdsql, I take it they should happen here.
One big question I have is what library is converting between python and SQL functions?  That is brilliant!

I did try using `vdsql` but had a couple issues.

2.  There is an issue with the `z"` command it will convert the generated SQL from `SELECT t0.a FROM mytable AS t0` to `SELECT t0.a FROM (SELECT t1.a FROM my_table AS t1) AS t0`
</div>

**Comment by saulpw** [comment]
I believe I've fixed this issue.  It can be tricky to get Ibis to generate reasonable SQL.

**Comment by anjakefala** [comment]
Hey @frosencrantz!

We really appreciated the issue, but unfortunately we don't know how to change the type in the original expr, while minimising SELECTs in Ibis. Trying to minimise the SELECTs accidentally removed the CASTS, and resulted in some typing issues.

When we next return to vdsql, we will take another look into this. But for now, I returned the previous behaviour because not having things typed correctly was worse.
