### ISSUE TITLE
Possible issue with requirements

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#1863]
### Discussed in https://github.com/saulpw/visidata/discussions/1579

<div type='discussions-op-text'>

<sup>Originally posted by **frosencrantz** October 29, 2022</sup>

I did try using `vdsql` but had a couple issues.

1. Installation caused me issues.  `pip install` got into some infinite loop that took a while to resolve.  This might just be my environment, but it did slow me down for a while.  I ended up changing the `requirements.txt` file to
   ```
   visidata >= 2.10.2
   ibis-framework[sqlite] >= 3.2
   ibis-substrait
   sqlparse
   ```
</div>

I was able to get it to work with my workaround.  I'm only using vdsql with sqlite so far.  I'm not motivated to debug this too much at this point.   But if the are other reports or I hit further issues, I might want to revisit.

**Comment by anjakefala** [comment]
Yeah, I think `ibis-bigquery` being a project maintained by a seperate set of developers is causing problems. This issue also ran into environment problems: https://github.com/saulpw/visidata/issues/1860

This issue is currently the reason the `vdsql` tests are off.

**Comment by anjakefala** [comment]
[ibis-bigquery](https://github.com/ibis-project/ibis-bigquery) has been archived, and it seems the ibis project has moved support of the [bigquery backend internally](https://ibis-project.org/backends/BigQuery/#install). So the fix for this is to remove `ibis-bigquery` as a dependency, and get the backend updated for use with `ibis-framework[backend]`. 

I am not sure if I can update the backend to work, but I can fix the requirements file.

**Comment by anjakefala** [comment]
It seems that I need to fix the vdsql build, but its requirements.txt is now installing fine!
