### ISSUE TITLE
Request extension support .zng [loader] 

### ISSUE THREAD

**Issue by AFgh24** [saulpw/visidata#1888]
Hello

If possible, add the .**zng** extension to the list of supported extensions

[brimdata/zed](https://github.com/brimdata/zed)

Thanks

**Comment by anjakefala** [comment]
Hi!

Since no one on the core team is familiar with this format, there is more information we would need for you in order to work on it. 

For reference, we have an issue template for loader requests: https://github.com/saulpw/visidata/blob/develop/.github/ISSUE_TEMPLATE/loader-request.md

In the template we ask for:
1. A small sample representative dataset in that format.
2. A basic Python script which queries and dumps the data (possibly using an external package).
3. And, information on how you would like to use VisiData to interact with this format. Which features are important to you? What are the quirks with the format?

It is possible I am mis-interpreting your request, and `.zng` is a format that is `.json`-like, and you would like the **JsonLoader** to support it. But, if that is what you need, I would need your clarification so that I can provide you with the guidance for that.

I am going to close this for now, but can re-open it if the information is provided!
