### ISSUE TITLE
Append sheets without key columns

### ISSUE THREAD

**Issue by andig** [saulpw/visidata#189]
I'd like to filter flight data by airport, which means either departure or arrival airport has a certain value. I've tried to do this by selecting all departure and then all arrival airports into their own sheets. Now it would be nice to join `&` the sheets- however `append` doesn't do what I expected. 

Is it possible to append column-wise identical sheets without specifying key columns or is there a better approach to the problem?

**Comment by saulpw** [comment]
Hm, that seems to work for me (v1.3.1)  What version are you using?

**Comment by andig** [comment]
Using 1.3.1 via brew. I've done some screenshots:

The actual sheet:
<img width="1280" alt="screen shot 2018-09-18 at 09 34 54" src="https://user-images.githubusercontent.com/184815/45672630-f814d180-bb28-11e8-8d18-efadca9fd6dd.png">

The list of sheets:
<img width="1280" alt="screen shot 2018-09-18 at 09 35 02" src="https://user-images.githubusercontent.com/184815/45672629-f77c3b00-bb28-11e8-930e-72452e4a1d2e.png">

The result after selecting 2 identical sheets and running `& append`:
<img width="1280" alt="screen shot 2018-09-18 at 09 34 41" src="https://user-images.githubusercontent.com/184815/45672631-f814d180-bb28-11e8-99df-5d9ad7355e76.png">

I guess that's a user error or due to not using any specific join columns? It would be great if appending "identical" sheets was available without specifying join columns?

**Comment by saulpw** [comment]
Ah, okay, that shows the issue.  Join matches columns by name, and all the columns in these sheets are unnamed (the default for Excel sheets, because we can't know which line will be the column names).  To set the column names, move to the row with those names, and press `g^` and then `d`.  If you do this on both sheets and then do the join, it should work correctly.  See also [Working with Excel spreadsheets](https://github.com/jsvine/intro-to-visidata/blob/master/docs/basics/working-with-excel.rst) from @jsvine's VisiData tutorial.

**Comment by andig** [comment]
Great, thank you very much!
