### ISSUE TITLE
Help with my test failures

### ISSUE THREAD

**Issue by TheChymera** [saulpw/visidata#1905]
On `=visidata-2.8`: https://ppb.chymera.eu/d8a1a0.log
On `=visidata-2.11`: https://ppb.chymera.eu/637ad6.log

Not sure whether this is the same error in both cases, but it appears to.
Both logs end with:

```
diff --git a/tests/golden/errors.csv b/tests/golden/errors.csv
index 00eea70..1a12cc1 100644
Binary files a/tests/golden/errors.csv and b/tests/golden/errors.csv differ
```

**Comment by anjakefala** [comment]
Hello!

I'm confused, what is the action item? Who is running those tests? I noticed through your profile that you posted this context-less in a bunch of repos. If you did not have a linked twitter profile that went way back, I would have thought you were a GPT bot and just closed this. Could you share the context?

The test result for `errors.csv` is Python version specific. The bug is that it is a False Negative with that particular testrunner, not that there is something wrong with VisiData. There were changes with Unicode characters between Python 3.10 and 3.11. 

We have that addressed in our CI runner, but can't guarantee that is taken care of in test runners outside of us. If you give me more specific information on where this is running, and how I can help you, I could provide more assistance.

**Comment by TheChymera** [comment]
@anjakefala what do you mean by “action item”? regarding the context:
* Python is 3.11
* This is built in a sandbox, `/var/tmp/portage/app-office/visidata-2.8/work/visidata-2.8`
* The command that fails is `dev/test.sh` — which is from the github workflows of this repo.
What other things would be relevant?

> We have that addressed in our CI runner

Could you link me to this fix?

**Comment by anjakefala** [comment]
Yup!

We updated the `errors.csv` to be the output for Python 3.11, and then only run the test on Python 3.11: https://github.com/saulpw/visidata/commit/5ff7883563eeac32fe192c5b2d4290a4e1e91cc2

If you are running your tests on Python 3.11, I would replace the `errors.csv` with the version in that commit: https://github.com/saulpw/visidata/blob/5ff7883563eeac32fe192c5b2d4290a4e1e91cc2/tests/golden/errors-311.tsv

> what do you mean by “action item”? 

I wasn't sure what you needed or wanted me to do. Did you want me to fix the tests somewhere? Did you want me to explain why they were failing, and you fixed them? It wasn't clear to me.

**Comment by TheChymera** [comment]
@anjakefala thank you, that fixed it. Tests pass fine when building from the 5ff7883563eeac32fe192c5b2d4290a4e1e91cc2 commit tarball.

So the issue was that the tests of extant releases aren't python3.11 compatible, right?

**Comment by TheChymera** [comment]
Also, if I want the build to be tested more thoroughly, should I run pytest explicitly (as seen [here](https://github.com/saulpw/visidata/blob/58e362ea42f217b4885c27856ad2d715c827a9db/.github/workflows/main.yml#L50)) or does `dev/test.sh` run that under the hood somehow?

**Comment by anjakefala** [comment]
What are you building/testing for? =)

> So the issue was that the tests of extant releases aren't python3.11 compatible, right?

Yes, exactly! The `errors.csv` file that is used is dependent on the Python version, not the VisiData version. I am glad it helped.

> https://github.com/saulpw/visidata/blob/58e362ea42f217b4885c27856ad2d715c827a9db/.github/workflows/main.yml#L50

For now, yeah! Though, that may change in the future.

**Comment by TheChymera** [comment]
> What are you building/testing for? =)

I'm packaging the software for Gentoo Linux, and recently noticed the tests failing. Thanks for your help.
