### ISSUE TITLE
[colors] Colors don't seem to render as expected

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#1907]
Given the following example:

<img width="815" alt="image" src="https://github.com/saulpw/visidata/assets/11225502/8b8475a8-bd19-40c1-a34b-af9e660f4ebe">

The row line for the option `color_current_row` is selected. The selection color (`color_selected_row`) has been set to `bold blue on green`.

I would expect the color of the background of that row to be GREEN (which it is) and the text to be BOLD BLUE, but it looks to be a muted blue. This is in contrast to the `reverse` cell which has bold colors and exactly the type of colors I would expect (but the opposite of course!!).

Is this as expected?

**Comment by geekscrapy** [comment]
In addition:

<img width="815" alt="image" src="https://github.com/saulpw/visidata/assets/11225502/c15b9714-1f32-468c-b433-bb2fd8e3e942">

The text for the selected row isn't BLACK, its a lighter grey than the background.

UPDATE:
It seems like the bold modifier is the culprit - which I guess means the rendering terminal (in this case iTerm?) is the true culprit?

<img width="815" alt="image" src="https://github.com/saulpw/visidata/assets/11225502/9ffd6bb9-726a-4e5c-a145-da7ff5422ce1">

**Comment by saulpw** [comment]
So, `bold` is not a color modifier, it is a font modifier; more like "italic" than like "bright".  For basic usage (color on black background), a bold character is thicker, and so appears brighter, and so it seems like bold modifies the color.  But it's not the way terminal rendering works.

When you use `bold blue on green` it seems like the foreground color is `bold blue`, and when it's reversed, it seems like it would be `green on bold blue`.  But the original color is actually like "bold (blue on green)" and so the fg color is just blue, and when reversed it's actually "bold (green on blue)".  ("green on bold blue" is allowed in VisiData, but is equivalent to "bold green on blue"; the "bold" can go anywhere in the color string).

I've had a hard time internalizing this myself when picking which colors to use in the interface.  The best thing I've come up with, is to pick basic color pairs without attributes that are legible and aesthetic both forward and reverse, and use the attributes (bold/underline/italic) as modifiers for e.g. the cursor (since attributes combine readily with colors and themselves).

**Comment by geekscrapy** [comment]
Thanks @saulpw appreciate the explanation. Taken it onboard, I'll give it a spin tomorrow.

As far as I see it, this can be closed 👌
