### ISSUE TITLE
column with Japanese text is misaligned

### ISSUE THREAD

**Issue by midichef** [saulpw/visidata#1918]
**Small description**
Columns become misaligned when the text nearly fills the column and the text contains the Japanese character \u3067 ("HIRAGANA LETTER DE").

**Actual result with screenshot**
![minimal](https://github.com/saulpw/visidata/assets/67946319/65ea5b9b-f994-4ecf-9b93-7fa28e72669c)

**Steps to reproduce with sample data and a .vd**
Create a cell that is 1 character narrower than the width of the column, but also contains \u3067. For example:
[minimal.json.txt](https://github.com/saulpw/visidata/files/11738917/minimal.json.txt)
`vd -N -f json minimal.json.txt`

**Additional context**
saul.pw/VisiData v2.12dev
Ubuntu 22.04
The behavior shows up in the terminals gnome-terminal and the latest version of alacritty:
`# GNOME Terminal 3.44.0 using VTE 0.68.0 +BIDI +GNUTLS +ICU +SYSTEMD`
`alacritty 0.12.1`

The problem does not appear in visidata 2.11, and it showed up in this commit 7c10dbd6aa9855b43f055f64e85053128ec9df86.

A note on terminals and testing Unicode. gnome-terminal is not good for testing Unicode text. I've seen in the past it's had similar column alignment problems with right-to-left text in visidata. But alacritty is better, and displayed the same right-to-left text perfectly. So the fact that alacritty shows this Japanese character problem too, suggests the problem may be in visidata.

The problem can also be worked around by setting `options.disp_ambig_width=2`.

I will add that I do not know the meaning of this character or how it should be properly displayed.

**Comment by saulpw** [comment]
So, `\u3067` or `で` is a full-width character, which takes up 2 character cells on the screen.  (I'm curious why `disp_ambig_width` works, since this character doesn't have an ambiguous width).  This is why we need to use `dispwidth(s)` everywhere instead of `len(s)` when figuring out where how long a string is or where to truncate it.

In this case, it seems like if there is exactly 1 character cell remaining inside the clipdraw box and a full-width character to display, then it displays the full-width character.  When it goes to blit the `|` in the middle of the full-width character, the terminal usually appends it to the character instead.  Now the formatting is off.

So I believe we need to truncate the string earlier in this case, and append an additional space before the truncation character.

**Comment by saulpw** [comment]
Okay, should be fixed now.
