### ISSUE TITLE
[aggregators] Display value is not used as the aggregation value

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#1926]
**Small description**
When using a custom type (like below), the display value seems to be discounted when using the column as an aggregation column.

```python
class str_fmt(str): pass
vdtype(str_fmt, '¢', formatter=lambda fmt,v: str(getattr(str, fmt, str.casefold)(v)))
```

Freezing the column does not seem to be a feasible alternative.

(FWIW: I use this type to ignore file path case sensitivity when doing frequency analysis on Windows systems filenames and paths, e.g. `C:\Windows\System32\svchost.exe` and `C:\WINDOWS\System32\svchost.exe` are considered equal)

**Expected result**
If a type is applied to the column, the display value is used in the aggregation calculation.

**Actual result with screenshot**
If you get an unexpected error, please include the full stack trace that you get with `Ctrl-E`.

**Steps to reproduce with sample data and a .vd**
1. config.py
```python
class str_fmt(str): pass
vd.addGlobals(
    str_fmt=str_fmt
)
vdtype(str_fmt, '¢', formatter=lambda fmt, val: str(getattr(str, fmt, str.casefold)(val)))
Sheet.addCommand('`', 'type-str_fmt', 'cursorCol.type = str_fmt', 'Allows case insensitive matching, mainly for freq sheets and aggregation functions')
```

2. create files
```bash
touch A B C D
```

3. Add `type-str_fmt` to the filename col
4. Add `distinct` to the filename col
5. Freq on the `size` column
6. Set the `agg_filename` to a `str` column
7. Note that the values that have been distincted are based on their non-formatted values

Or if you want it in pictures:
![demo cast](https://github.com/saulpw/visidata/assets/11225502/d555a840-b0c1-4f65-8e6d-288ea0e09fad)

Obviously, I appreciate this may not be a bug :)

**Comment by geekscrapy** [comment]
Obviously, I appreciate this may not be a bug :)

**Comment by saulpw** [comment]
The grouping function of the freq/pivot tables uses the display value, but aggregators are given the typed values.  I think what you want to do instead, is make your `str_casefold` a function that returns the value you want to aggregate by:

```
def str_casefold(*args):
    return str(*args).casefold()
vdtype(str_casefold, '¢')
```

Of course, this means you'd have to make a separate type for each function, instead of being able to set the fmtstr to the function you want to use.  That's how it has to be, at least for the time being.  The alternative would be for `getTypedValue` to return the formatted/display string for `str` types.  Which might make some sense, but would be a bigger change (and more convoluted).
