### ISSUE TITLE
Bug: replaying sorting a column shows `no "stargazerCount" column | replay cancelled`

### ISSUE THREAD

**Issue by hacker-DOM** [saulpw/visidata#1951]
There is something tricky going on with replay commands and waits. I am seeing several issues:

- replaying sorting on a column worked a few times, but generally doesn't work. I get `no "stargazerCount" column | replay cancelled` error message
- waits don't work - even a 10 second wait `-w 10` yields the error message immediately. Maybe this is bc there is just one command in the replay, idk
- feature request: why not allow executing commands from Cli? Eg `vd -f json +'sort-desc stargazerCount' data.json`.

Data: gist.github.com/hacker-DOM/8d851bc19e83ade3308c6dbcec7dd9b0
Previous discussion: https://github.com/saulpw/visidata/discussions/1950#discussioncomment-6369100

**Comment by ajkerrigan** [comment]
Out of curiosity which version of VisiData are you running? I ask because I've gotten this error in a small percentage of runs with 2.11 but haven't been able to reproduce it running off develop (7ddee16320cb4050e7eddefad55a2ff19d884beb).

For repros I do find it helpful to rule out some environmental issues also, by doing something like:

```console
vdtemp=$(mktemp --directory)
vd --config=/dev/null --visidata-dir="$vdtemp" ...
```

Only because especially with timing/threading issues, a plugin load here or convenience function there can create or hide problems.

_Note that the fresh temp dir for `--visidata-dir` is handy sometimes because if you're doing something that writes to the vd cache/plugin store/etc it's nice to have a fresh writable space._

**Comment by ajkerrigan** [comment]
I wonder if the issue here is that replay is syncing _between_ commands but not before the first one? If our first command is `open-file`, we expect replay to run that command and then `vd.sync()` before executing the next command. But if we're opening the file and trying to run a replay at around the same time, things can go off the rails?

When I encounter this error from a debugger, I see the `reload()` thread still running and `rows = []` on the `dom_gho` sheet.

But if we add even a "useless" command ahead of that `type-int` call it _seems_ to work around the issue, presumably because we're getting a `vd.sync()` before the `type-int` command fires:

```
sheet	col	row	longname	input	keystrokes	comment
				helloworld		F2	print greeting to status
	stargazerCount		type-int		#	set type of current column to int
	stargazerCount		sort-desc		]	sort descending by current column; replace any existing sort criteria 
```

That also seems to address this point:

> waits don't work - even a 10 second wait -w 10 yields the error message immediately. Maybe this is bc there is just one command in the replay, idk

This is at least 34% handwaving and guessing, but seems relevant even if it's not the complete truth of what's going on.

**Comment by saulpw** [comment]
The replay mechanism has been reworked to be contained within the mainloop.  This bug may not happen any more (and maybe wasn't happening on develop anyway as per @ajkerrigan's comments above).  @hacker-DOM please try with recent develop and if you're still seeing problems we can reopen it.
