### ISSUE TITLE
[loader] GTFS support

### ISSUE THREAD

**Issue by LaPingvino** [saulpw/visidata#1952]
GTFS is a format created by Google for public transport data. As it's simply a zip file with csv contents it's almost already supported, except GTFS has the quirk that its csv contents have a txt extension, so atm visidata sees it as plain text instead. As the names are always the same (with some files being optional) it shouldn't be hard to even autodetect if a zip file is supposed to be a GTFS file.

I would be using this myself, so I will be able to test this.

**Comment by saulpw** [comment]
Hi @LaPingvino, can you provide a sample GTFS file?  (Ideally a public URL.)

**Comment by LaPingvino** [comment]
Official sample: https://developers.google.com/static/transit/gtfs/examples/sample-feed.zip

Description of the file:
https://developers.google.com/transit/gtfs/examples/gtfs-feed

Carris Metropolitana:
https://github.com/carrismetropolitana/gtfs/blob/live/CarrisMetropolitana.zip
(huge real life file that might break your tools, Open Data, good to test with)

**Comment by saulpw** [comment]
How about `vd -f zip sample-feed.zip -f csv`?

**Comment by saulpw** [comment]
This is what the gtfs loader would look like (I just subclasses `ZipSheet` and overrode `ZipSheet.openRow` to forcibly set the internal filetype to `csv`):

```
@VisiData.api
def open_gtfs(vd, p):  #1952
    return GtfsIndexSheet(p.name, source=p)


class GtfsIndexSheet(ZipSheet):
    def openRow(self, row):
        fi, zpath = row
        fp = self.openZipFile(self.zfp, fi)
        return vd.openSource(Path(fi.filename, fp=fp, filesize=fi.file_size), filetype='csv')
```

I decided not to include this as a loader, because The gtfs format is quite esoteric, and a custom filetype is less discoverable than using the standard types in the above command (`vd -f zip <gtfs.zip> -f csv`--note the order of the arguments).   Maybe it would be worth it if it were more easily auto-detectable, but it's more difficult to guess the type since the files are inside a .zip file.  I could be persuaded if this is a popular and frustrating format for other people too.
