### ISSUE TITLE
Quit guard has different behaviors in command line and options

### ISSUE THREAD

**Issue by cool-RR** [saulpw/visidata#1976]
If I run this: 

```
vd foo.csv --quitguard
```

And they press `q` to quit, I get the dialog that says "quit guarded sheet "foo"?", even though I haven't made edits.

However, if I run

```
vd foo.csv
```

Then press `shift-o` to go into options and turn on quit guard, then attempt to quit the main sheet, it'll only show the dialog if I modified the file, which is the correct behavior.

Versions:
```
saul.pw/VisiData v2.11.1
Python 3.10.6
```

An aside, I think that it's confusing that there's both a `guard-sheet` command and a `quitguard` option. It's not clear whether they're the same thing or what.

**Comment by saulpw** [comment]
This was [a deliberate choice](https://github.com/saulpw/visidata/blob/0e169289c9637d21d8be999123e39138fee3ea1d/visidata/sheets.py#L982) to confirm quitting sheets that were guarded specifically.  Note that if you changed the option via `z Shift+O` or by using the `guard-sheet` command, it would behave as if given on the CLI.  The guard-sheet command merely sets the `quitguard` option for the current sheet only.

I could see removing this code that confirms quitting unmodified sheets if they are guarded specifically, but it seemed to me that if you have an expensive sheet that took awhile to calculate, you might really want `guard-sheet` to block an unintentional exit.  Maybe `guard-sheet` could set it to a different value, which would be picked up by this code instead of the generic True that gets set by the CLI.  But then we have a bizarre option with `False/True/2` values, or `quitguard` would become an int option, so the CLI would change and you'd have to do `--quitguard=1` instead.  

Another thing that's going on here, is that the CLI applies its options directly to all sources given on the CLI; this is so you can set options on some sheets and then change them on other sheets.  Trailing options are also applied this way, which really only matters for quitguard and filetype, but the semantics of filetype are complicated enough that you might want (in some extreme cases) for a global filetype option to work as fallback, but have it overriddable by file extension or mimetype, but also allow the user to deliberately override it manually.  We could make it so that `vd -f csv https://example.com/foo.txt` applies to foo.txt, but `vd https://example.com/foo.txt -f csv` does not, but that seems more confusing than the current magic.

**Comment by cool-RR** [comment]
Oh boy, that's more than I'm going to wrap my head around. What I did now is add a monkeypatch to solve my particular problem.

My two cents, from the user's perspective, are that you have two separate features here under the same name, so if none of the solutions you're considering would work, maybe you should consider explicitly splitting the quit guard to two features with different names. They could be `prompt-before-quit` and `prompt-before-unsaved-quit`. Though now your suggestion of `False/True/2` makes more sense. If having options with several choices something that isn't well supported in VisiData, maybe it should be, because maybe this'll be useful for more options. Maybe these options should be named rather than numbered, have an enum and a nice way to communicate to people all the options, and show an informative error message when they choose a wrong option.
