### ISSUE TITLE
[site] The Ascinema player on the site won't show up.

### ISSUE THREAD

**Issue by maxim-uvarov** [saulpw/visidata#1977]
I've noticed that there is ascicast player in the code of the site
https://github.com/saulpw/visidata/blob/develop/docs/columns.md?plain=1#L221

However, its rendering is absent from the site. At least in Brave browser and Safari. 

<img width="1122" alt="image" src="https://github.com/saulpw/visidata/assets/4896754/9990482b-62a8-42ae-adf1-468147580ed6">

**Comment by maxim-uvarov** [comment]
there is a beautiful tool for producing demo terminal Gifs: VHS https://github.com/charmbracelet/vhs

If I ever have time, I would love to help you guys use it here. Let me know if this kind of help is needed here.

**Comment by anjakefala** [comment]
Asciinema is a super powerful gif alternative, but we have been running into issues with it for a while. Least of all that any page that does not have the javascript embedding would not work. I wonder if there was an update that resulted in the embedding not working.

I think we should transition them to either gifs or screenshots. I will set aside some time to update the docs in the future.

Thanks for letting us know!

**Comment by maxim-uvarov** [comment]
VHS is cool because it is reproducible. You can alter your scripts, and they will produce new GIFs. It even has GitHub Actions integration, so GIFs can be produced automatically with new commits or according to other rules.

For example, you can have a simple VHS script that starts VisiData with a well-known vdj file-replay in it. After VisiData has quit, VHS can stop recording and produce the new GIF.

Asciinema is definitely a very powerful tool too, but as far as I can understand, it is not reproducible, and the reproducibility might be useful in VisiData's example.

Of course, all the decisions are up to mainteiners! I'm just sharing my ideas here. I didn't want to be pushy or rude.

**Comment by ajkerrigan** [comment]
VHS looks sweet, those charmbracelet folks make a bunch of useful (and pretty!) stuff :heart_eyes: .

I know asciinema has _some_ support for scripting, and tools like https://github.com/zechris/asciinema-rec_script build on it. But VHS looks friendlier.

I could see converting the existing `.cast` files to gif (with https://github.com/asciinema/agg or similar tools) and keeping VHS in mind when there's a need for new recordings :sunglasses: .

**Comment by anjakefala** [comment]
@maxim-uvarov Thank you for describing the benefits of vhs so thoughtfully, and for offering to help out. You are right that that scripting opportunity is promising...

This is a bit of thinking-out-loud...

Originally, we went with asciinema, because it would not start playing until a person pressed play. A gif starts playing when you show up on the page, with possibly a less clear start-point and no rewinding, and that can be hard for something intending to be a tutorial. 

For reworking these docs (and they do need some love) going the screenshot approach is probably more helpful to folks, and the gif approach is faster.

Just converting the casts to gifs is tempting for expediency (thanks for finding that @ajkerrigan), but the VisiData interface has changed since then, so I think it is actually worth taking this opportunity to revisit these docs and make the images or gifs.

@maxim-uvarov I would love to accept your offer to help, if it is still on the available, since there is probably a lot of work here. I would happily accept a PR for any new gifs or screenshots replacing the old asciicasts. I am going to revisit the docs as well, and give them updates. 

Are you part of the https://bluebird.sh/chat for if you want to coordinate with me?

**Comment by maxim-uvarov** [comment]
> I would happily accept a PR for any new gifs or screenshots replacing the old asciicasts.

@anjakefala got it! In the next few weeks I'm busy, but hopefully I will have time after. 

Yep, I'm member of your discord, `@maxim`

**Comment by saulpw** [comment]
Deprecating the howto docs and replacing them with internal guides (`vd --guides`) (which will eventually be rendered on the webpage also).
