### ISSUE TITLE
Join should work with the typed values, not the display values

### ISSUE THREAD

**Issue by aborruso** [saulpw/visidata#2015]
If I run a join, it works with the display values, not  the typed values.

I have this a.jsonl file

```
{ "id": 1, "name": "andy" }
{ "id": 2003, "name": "bandy" }
```

and b.jsonl one

```
{ "id": 1, "color": "yello" }
{ "id": 2003, "color": "orange" }
```

And I have these display options:

```
options.disp_float_fmt = '{:,.02f}'
options.disp_int_fmt = '{:,}'
```

If I open the files `vd a.jsonl b.jsonl` and then I do a inner join using `id` field I have this error: `ValueError: invalid literal for int() with base 10: '2,003'`

![image](https://github.com/saulpw/visidata/assets/30607/b0aa481f-8684-4248-adb0-995f11879594)

_Originally posted by @aborruso in https://github.com/saulpw/visidata/issues/2014#issuecomment-1699612379_

**Comment by saulpw** [comment]
So, we changed join to use displayed values instead of raw values in 7c79bc441edad6ab000ab32eb597694cc9e2cd75 because of #1124. 

Note that grouping (via e.g. the freq table) uses the displayed value; we did this so that you can easily group by a partial date--if you have a date column from a timestamp, it will show Y-M-D as per the fmtstr, and it's nice to group by what's displayed. If we made join use the typed value, it wouldn't join these partial dates as would be expected.

However, the error you're seeing is from applying the type to the displayed value in the key column.  We can join on the displayed value, but then show the typed value as the key value on the joined sheet, with the key column display format.  This seems to fix your issue and keep our internal behavior consistent too.
