### ISSUE TITLE
[debugging] Prefix the plugin name to status messages

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#2021]
Usecase: If you have a lot of plugins (and also deving plugins) and you get a generic status message, which plugin caused this error? Additionally, if a plugin creates an exception, it stops the following plugins being loaded.

So a couple of sugestions:
1. Prefix the plugin name/shortname to the status messages generated from within that plugin
2. Include a function something like the one I have been recently using below, which catches a failed plugin and still allows the .rc to run and load other plugins. This might also be useful within `~/.visidata/plugins/__init__.py`

```python
def import_safe(module_path):
    try:
      __import__(module_path)
    except ImportError as e:
      vd.warning(str(e))
```

**Comment by frosencrantz** [comment]
I agree this would be useful.  I wish all of the status messages provided more context about what is generating them, like what command,  which module,  what file&lineno, or in batch scripts what command #.  I've used VisiData in batch mode, and  different commands provide status but these are not very helpful without context.

**Comment by ajkerrigan** [comment]
Hmm that does sound like a handy thing. Even something more bare bones like adding a bit of calling frame context seems like a useful thing to opt into.

Testing with a `.visidatarc` snippet like this: 

```python
import inspect
from functools import wraps
from visidata import vd

def traceback_wrapper(f):
    @wraps(f)
    def wrapper(vd, *args, **kwargs):
        try:
            stack = inspect.stack()
            context = (stack[1].filename, stack[1].function)
        except exception:
            context = ()
        f(vd, *context, *args, **kwargs)

    return wrapper

setattr(vd, "status", traceback_wrapper(vd.status))
```

Gives output like this after opening the sample `benchmark.csv` dataset and running a few commands:

![image](https://github.com/saulpw/visidata/assets/19539955/c0cffb79-6ef0-4ea7-b57f-c72884df0537)

Which is neat enough that I might leave it on, and I could certainly see a case for tweaking/expanding `context` based on personal preference or to fit a particular use case. (I'm typically more concerned with function/method names but can see @frosencrantz's point about line number, for example...)

Of course "neat to switch on while fiddling around" doesn't always equal "generally useful", so your mileage may vary.

**Comment by saulpw** [comment]
So, we can add another column to the status sheet that has this information, without having to pollute the actual status message.  And we could prepend it to the batch output of status messages, either always or on `--debug`.

**Comment by saulpw** [comment]
Okay, how about this?

![Screenshot from 2023-09-26 20-15-28](https://github.com/saulpw/visidata/assets/236498/c9b21db9-2869-45dc-b8ed-5bd84763115a)

**Comment by geekscrapy** [comment]
That looks good!
Maybe hidden by default so the message col can expand fully?

**Comment by saulpw** [comment]
Or we could put the source column first?  It seems like, as a hidden column, it wouldn't be very discoverable.  Or maybe that's not important and it's a power-user feature.

Also can you use `vd.importExternal()` instead of your `import_safe()`?  We could augment it to handle ImportError if that's necessary too.

**Comment by geekscrapy** [comment]
I'd say if it was trimmed down to the function name, it might be ok as a first col, otherwise I think it would be too verbose for the normal user. It depends on how people use the status sheet really. I think we are a bit bias as people here dev plugins etc, so we'd like the extra info and likely check the status page a lot, but a casual user might not, and therefore having a verbose status page likely isn't an issue.

I'll take a look at importExternal but I'm stuck on py 3.7 so unless it's been in the core for a while I maybe missing it. Would be nice to include that exception though

**Comment by ajkerrigan** [comment]
Would it be useful or annoying if the extra columns were hidden by default, but the sidebar gave a hint to use gv if you want more detail?

**Comment by geekscrapy** [comment]
Hmmm, it maybe ok. I think I'd still prefer my suggestion though.
Alternatively, could the status (where the row count and columns are) include the number of hidden columns...? Just another alternative that might help generally?

**Comment by saulpw** [comment]
> could the status (where the row count and columns are) include the number of hidden columns...?

I like this idea.  Now that the status messages are in the sidebar, there's maybe room for `1/4 columns shown`.  Though that's kind of awkward; maybe `4 columns, 3 hidden`?  Just `3 hidden columns`?

> Would it be useful or annoying if the extra columns were hidden by default, but the sidebar gave a hint to use gv if you want more detail?

I also like this idea, especially for internal sheets like the StatusSheet.

> I think we are a bit bias as people here dev plugins etc,

For awhile now we've been wanting an "expert" option that we can set in our .visidatarc, that exposes more advanced features, perhaps like these extra columns here, and on the Columns Sheet there are some that I would hide for beginners (like formatter and displayer).  Figuring out the levels and what options/commands belong though is challenging; maybe novice (would include gobs of text in help status), casual, advanced, expert/dev?  It would be nice to send novices to the options page and not have them see all the interface theme options.

**Comment by saulpw** [comment]
Okay, I made it so that there's now a `help_columns` property on the TableSheet, which can be added to a sheet's `help` which appears on sidebar.  If there are any hidden columns, it includes "`gv` to unhide N hidden columns"; this is now on the TableSheet and the ColumnsSheet at least.

Furthermore, I decided to make `options.disp_help` an integer and use it as a gauge of novice/expert mode.  When `disp_help` is:
- `-1`: status messages aren't shown
- `0`: no help is shown
- `1`: sidebar sheet help is shown
- `2`: help is shown for the input widget on the sidebar (this was condensed and moved from the former input help panel)
- Higher numbers could show even more help eventually

Now we can specify a `max_help` int attribute on any Column, which means that if `disp_help` greater than it, the column will be hidden by default.  I set this for a few columns on the ColumnsSheet to be a bit simpler for novices. We can do the same on the StatusesSheet or any other internal sheet; feel free to start a discussion.

But also!  I started to annotate options with a `max_help` number, which removes them from the OptionsSheet if `disp_help` is greater.  And I made all theme options (all `color_` and most `disp_` options) be `-1`, so they won't be overwhelming novices anymore.  You can still set them in themes or on the CLI, but if you want to play with them "live" you'll have to set `options.disp_help = -1` like a proper VisiData developer :)

I plan on doing the same with commands, so that a novice won't accidentally splitpane or turn on profiling or whatever.

And, wrapping up this particular issue, I'm still open to including some clue/affordance in the interface for hidden columns, like maybe changing the column header separator and making it clickable.  If anyone wants this, feel free to open up a new issue.

**Comment by geekscrapy** [comment]
This (these) are great additions! Thank you Saul

**Comment by anjakefala** [comment]
@geekscrapy, did you update your VisiData yet? :angel:

**Comment by geekscrapy** [comment]
Hey hey, I really like the change. I updated and I have a few updates to make for my plugins (mainly around `Sheet.allColorizers`), need to checkout a few options like the above!

**Comment by anjakefala** [comment]
Welcome back to `develop`, I'm so happy you're here. =)
