### ISSUE TITLE
New column type: URL

### ISSUE THREAD

**Issue by daviewales** [saulpw/visidata#2031]
It would be nice to set the type of a column to URL, and have the column values wrapped in [OSC 8](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda) escape codes.

Currently some terminal emulators (e.g. Windows terminal) automatically detect links.
So when a URL column is full-width, then I can ctrl-click to open the links in my browser:
![image](https://github.com/saulpw/visidata/assets/2499066/9242988e-523c-42f7-ab39-9787875597fd)

But when a URL column is partial-width, the URL autodetection only sees the first few characters of the URL, so doesn't work:
![image](https://github.com/saulpw/visidata/assets/2499066/99b8268c-a412-4218-a796-c5cc3b549634)

If the column values were wrapped in OSC 8 escape codes, they could be made to function as full links, even when only partially visible.
A lot of terminal emulators [now have support for OSC 8](https://github.com/Alhadis/OSC8-Adoption/).

**Comment by frosencrantz** [comment]
VisiData relies on Python Curses which is typically ncurses on Unixish systems.  I am not sure, but it looks like ncurses does not support OSC 8.  The link you provided does not mention ncurses.  It looks like Textual supports it.

It would be  a useful feature, if there was support.

**Comment by daviewales** [comment]
Is it possible to output raw escape codes in curses?

**Comment by saulpw** [comment]
ncurses doesn't support OSC8, and you can't output raw escape codes with it (I tried; ESC is made printable as `^[`).  Outputting raw escape codes to stdout as a hack is evil, but it might work for non-display functionality; but if it needs to actually be displayed on the screen it would need to coordinate with the curses library to keep track of what's shown or not, in order to update properly.

That said, I just added a small amount of code so that the `onclick` VisiData display attribute can take a url (instead of its usual command longname), which will cause `vd.launchBrowser` to be called with the url when it's clicked.  This commit also adds a `displayer_url` which just yields the text string as both an onclick attribute and the text itself, so you can click on it for the desired effect (including launching a browser with the correct URL even if it's been truncated).

You have to set the `displayer` column attribute manually on the columns sheet for now, but give it a try and see if it does what you need, and feel free to make a `type-url` command or something that does this more easily.

**Comment by daviewales** [comment]
Finally got a chance to test this.
It took me a minute to figure out I need to add 'url' to the 'displayer' column on the columns sheet:
<img width="719" alt="Screen Shot 2023-10-06 at 8 27 33 pm" src="https://github.com/saulpw/visidata/assets/2499066/6f036908-8da7-4417-8771-0e78d8341bbc">

I also had to set `$BROWSER`, as this isn't defined by default on macOS.
(I set it to `BROWSER=open`, which works perfectly.)

Very neat!

I've added a simple `type-url` command to my `~/.visidatarc`:

``` python
@BaseSheet.api
def type_url(sheet):
    sheet.cursorCol.displayer = 'url'

BaseSheet.addCommand("", "type-url", "type_url()")
```

Would you consider including this in visidata itself?

**EDIT**:

Shorter version of 'type-url' command, and additional 'open-url' command, which will open the current cursor value in `$BROWSER` regardless of the display setting:

``` python
BaseSheet.addCommand("", "type-url", "sheet.cursorCol.displayer = 'url'", "set column to open URLs in $BROWSER on mouse click")
BaseSheet.addCommand("", "open-url", "vd.launchBrowser(sheet.cursorValue)", "open current cursor value in $BROWSER")

```

**Comment by saulpw** [comment]
Okay, I've added it!  Thanks for adding the helpstrings, that made it easy to mostly cut-and-paste.  (One minor nitpick for future reference: these commands should be added to `Sheet` instead of `BaseSheet`, since they use the `cursorCol` concept, which is introduced as the TableSheet/Sheet, and isn't on all BaseSheets.)

**Comment by daviewales** [comment]
Thank you!
