### ISSUE TITLE
"guessed "dir" filetype based on contents" is annoying

### ISSUE THREAD

**Issue by cool-RR** [saulpw/visidata#2065]
Is the "guessed "dir" filetype based on contents" message really helpful? Starting `vd` on a folder is the 99% use case for me. I don't need VisiData telling me that it was just scratching its head every time I open it.

**Comment by anjakefala** [comment]
@cool-RR There is a `git` filetype, which is why that guessing information is there. It's to let people know if it was opened as a git repo or dir repo. That has bitten me once before.

***

For questions on why a feature exists, it would feel better to me to ask on Discord or libera or discussions instead of opening a bug report. We are significantly investing into triaging right now, and it feels demotivating to get issues opened which could have been questions in a chat channel, or collected into multiple questions on a single discussion.

**Comment by cool-RR** [comment]
Sorry about opening this as an issue.
