### ISSUE TITLE
[input] Some minor imperfections 3

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#2075]
Some more minor imperfections that I’ve been meaning to suggest.  Like Issue #1243 and Issue #1329

- [x]  Confirmation dialog yes / no it would be great if they were clickable with a mouse.  They look like buttons, but are not clickable.
- [x]  Repeat from Issue #1243  Choosemany() doesn’t provide a history based on type. It is using general history (untagged)
   * This is going to be fixed by a solution to #1027 with a better chooser.  Even when there is a better chooser it would be useful if there is an input option that the input is tagged with a type.  I don’t think that would be too hard to add now.  From chooseMany() -> input() there could be a “type=” parameter.  Right now the problem is that input from joins and aggregators mix together in history, so up arrow doesn’t work as well as it could if the `type` parameter was passed to input().
- [ ] Add a ctrl-r command for input like the shell it allows you to search for previous input that you have entered.
- [ ] Allow percentage input for `random-sample` (or even other things like `resize-col-input`). Currently you need to enter calculate the value yourself if say you only want 10% if the values.  This makes parsing the input more complicated since you need to handle % values and specific counts.

Maybe these last two are more than minor, and the second one has already been deferred for a better solution.

**Comment by saulpw** [comment]
Hi @frosencrantz, thanks for suggesting these.

I just added clickability to the confirm dialog.  It's a hack for now, in place of the big work I need to do for #1027, which I'm really hoping I can do before 3.0.

Adding a `type` option for chooseMany/chooseOne history is a proper oversight, and it should be pretty straightforward to do for jointype and aggregators.  Thanks for the reminder ping on this one.

I don't think "Ctrl+R" reverse search like the shell is either an imperfection, nor a small feature, though I agree it would be useful.  It should be its own wishlist item (which would be Kondo'ed right now as we push towards VisiData 3.0).

Likewise the percentage input for certain commands would be quite useful, but a feature improvement rather than an oversight.  It should be fairly easy to implement however.  If you were to make a new wishlist issue that listed the commands you thought would use this, and what e.g. `10%` would mean 10% of (for random-sample, number of rows, for resize-col-input, current width I think?) that would go a long way towards making it happen.

If you create separate issues for the latter two items, I'll implement type for the choosers and we can close this multi-purpose issue.

**Comment by frosencrantz** [comment]
Thanks @saulpw!   I was able to test the yes/no buttons and it works great.   I had forgotten I had already reported it.  I thought I had mentioned the ctrl-r, but could not find it.

I created new wishlist issues #2081 and #2082
