### ISSUE TITLE
Feature request: update expressions when renaming a column

### ISSUE THREAD

**Issue by pacien** [saulpw/visidata#2088]
Currently, renaming a column using `^` or through the sheets sheet does not
update expressions in other columns referencing it.

Manually updating all the expressions is quite tedious and error-prone.

It cannot be done using a simple search&replace either, since the name might
also be present in strings for example, so some awareness of the python syntax
seems necessary.

It would be nice for the symbols in those expressions to be automatically
updated when renaming a column.

**Comment by saulpw** [comment]
Hi @pacien, thanks for the suggestion.  I can see why this would be frustrating when you want to rename a column.  As you mention, this would require parsing and manipulating the expressions of dependent columns, which is something we don't current do (ExprColumns use Python `eval()` with a clever locals dict).

It's also tricky, because sometimes I *want* to replace some column in an expression with a new column, and I can just rename that new column to the old name and it will prevail (if the old column is hidden, at least).  Would we have two different rename commands, one that does the work of checking and updating dependent expressions, and the current simple one which doesn't?

In any event, this is more work than I'm willing to take on for the time being.  If you or someone can share a snippet of Python code which does the work to parse, substitute, and reconstitute an expression, we could make a separate `rename-col-cascade` command or add an option that makes `rename-col` do the same.

Kondo'ed for now.

**Comment by pacien** [comment]
Turns out that the `ast` library included with Python can do that:

```python
import ast

class Renamer(ast.NodeTransformer):
    def __init__(self, find, replace):
        self.find = find
        self.replace = replace

    def visit_Name(self, node):
        if node.id == self.find:
            node.id = self.replace

        return node

original = ast.parse("'a' + int(a) * 50")
modified = Renamer('a', 'b').visit(original)
print(ast.unparse(modified))
```

A catch is that it does not preserve the formatting of the original expression,
but that's probably a very minor issue, especially if this is done via a
specific command which is expected to do some rewrite.
