### ISSUE TITLE
[xlsx] edit excel workbook in place

### ISSUE THREAD

**Issue by kalyan860** [saulpw/visidata#2132]
Most often, I want to make quick edits on excel workbooks containing 2 to 3 sheets. I want to edit the workbook in place without having to save to a new excel file everytime. I know that there is a way to save all sheets of an excel file using gCtls-S. However, doing that makes you lose all formatting data inside of excel and the order in which sheets are saved is unrelilable. 

As most people using tabular data use excel, excel(or any spreadsheet application) integration is most important to visidata.

**Comment by saulpw** [comment]
Hi @kalyan860, thanks for the suggestion, I can see how it would be useful.  However, this would require a larger change in the xlsx loader to commit changes via `z Ctrl+S`, instead of exporting them fresh with `Ctrl+S`.

I spent my recent xlsx energy to show cell color formatting (#1718), but we'll definitely consider this next time.  And of course if someone wants to put their own efforts toward it we'll definitely entertain a PR.

Kondo'd for now.
