### ISSUE TITLE
Testing for performance regressions

### ISSUE THREAD

**Issue by reagle** [saulpw/visidata#2147]
[Elsewhere](https://github.com/saulpw/visidata/issues/1068#issuecomment-1833071717) @saulpw asked me to identify which commit might introduce a suspected performance regression. I've never used git bisect (and I'm not sure how to run it across different installs) but I did want to see how far I could get with something reproducible.
 
With the original 225MB file I see a 1 second (7%) decrease between the last tagged version and the latest dev version. Granted, that's not a very big deal, but it might be of interest, and more consequential with larger files.

```
❯ wget https://github.com/datablist/sample-csv-files/raw/main/files/people/people-2000000.zip
❯ 7z x people-2000000.zip
❯  for i in {1..5}; do cat people-2000000.csv >> people-1gb.csv; done
❯ wget https://reagle.org/joseph/2023/vd-test/sort.vdj
❯ chmod +x sort.vdj

❯ pip3 install git+https://github.com/saulpw/visidata.git@v2.11.1
...
❯ time sort.vdj
sort.vdj  14.24s user 0.36s system 98% cpu 14.823 total
❯ time sort.vdj
sort.vdj  14.07s user 0.36s system 99% cpu 14.528 total

❯ pip3 install git+https://github.com/saulpw/visidata.git@develop
...
❯ time sort.vdj
saul.pw/VisiData v3.0dev
Support VisiData: https://github.com/sponsors/saulpw
opening sort.vdj as vdj
sort.vdj  14.96s user 0.40s system 98% cpu 15.549 total
❯ time sort.vdj
saul.pw/VisiData v3.0dev
Support VisiData: https://github.com/sponsors/saulpw
opening sort.vdj as vdj
sort.vdj  15.19s user 0.40s system 99% cpu 15.665 total
```

**Comment by saulpw** [comment]
Thanks, @reagle!  I'm not going to worry too much about that 7% decrease, because if we're going to focus on performance, we'd make some larger architectural changes and aim for a 10x improvement (which should be possible--sorting 2m rows should not be that big of a deal).

If you're interested in figuring out where that performance decrease happened, `git bisect` would be the way.  It's not that difficult--you'd install from a git checkout with `pip3 install -e .` (`-e` so that it's editable), mark the current commit as "bad" with `git bisect bad`, git checkout the v2.11.1 tag (it might have to be a slightly different commit that's a direct ancestor of develop HEAD) and do `git bisect good`, and then git will check out one commit at a time and let you run the test and mark whether it's good or bad.  After some 8-10 rounds of this, git will announce which commit appears to be the culprit.

It might be useful for you as an exercise, as git bisect is a very useful tool.  I have a hunch that the culprit will be doing something meaningful, like handling some edge case or errors in a consistent way, that we won't want to revert, and it won't be worth it to twist ourselves into knots and adding a bunch of code trying to get some 5% of performance back.  But you never know, it might be something that seems innocuous, and when we dig into it, it's an oversight that we can remedy with a simple cache, and has a 5% performance improvement across the board.

**Comment by reagle** [comment]
Okay, I'll close for now but keep it in mind should I wish to try bisect.

**Comment by reagle** [comment]
BTW: I tried the latest dev version on both 3.11.6 and 3.12.1 and loading and sorting a 1.8G tsv has the following differences:

- 3.11.6 = 30s
- 3.12.1 = 39s

Interesting to see a 30% slowdown across versions.
