### ISSUE TITLE
Press Tab to enable command palette numbers hotkeys

### ISSUE THREAD

**Issue by cool-RR** [saulpw/visidata#2154]
I'm really enjoying the new command palette. It did take some trial and error to figure out that the way to use the numerical shortcuts keys is by hitting ctrl-number. Maybe instead of 1, 2, 3 it should show ^1, ^2, ^3?

Also now I'm noticing these ctrl-number shortcuts are only working for 1-3, and not for 4 and above. Am I doing something wrong?

**Comment by reagle** [comment]
@cool-RR I'm not having the same experience. Below, if I want to move right, I hit `6`, not `ctrl+6`, which I think is what you are saying?

<img width="333" alt="SCR-20231204-ojks" src="https://github.com/saulpw/visidata/assets/596814/b958886c-6269-4731-ab72-b87f11474c32">

**Comment by saulpw** [comment]
So, the numerical shortcuts are just the number, like `1`.   `Ctrl+1` might work because there is no such control character, and so it's just like pressing `1`.   However, I think this mechanism has to change, since it's also used for aggregators, and this prevents certain aggregator names (like `q4` for quartiles) from being typed.  So I'm thinking of making it be `Alt+1` etc; this change would happen soon, before v3.0.

And this may be not be the ideal workflow anyway, since as @geekscrapy points out, people are used to selecting with the arrow keys and pressing `Enter`.  (But this conflicts with the history mechanism so won't happen for v3.0.)

**Comment by cool-RR** [comment]
Given the discussion in #2155 , it's possible that I'm affected by the old version I use, so let's ignore the symptoms I've had and focus on the discussion in Saul's last comment.

I would be bummed if the official hotkeys were `Alt+1` etc because I already use these to switch between virtual desktops. But if they're in addition to just plain `1`, then I have no problem with that.

**Comment by saulpw** [comment]
Okay, so we've kept the hotkeys as numbers, but now you have to press `Tab` first.  You can also `Tab` down the list and press `Enter` on highlighted  item.
