### ISSUE TITLE
Headers lost when saving txt file

### ISSUE THREAD

**Issue by p-levy** [saulpw/visidata#2173]
Hi, first thanks so much for this great tool, I love it. 

When I try to save (`ctrl+S`) after having edited a TSV file (for example removing some columns with `-`), my output file doesn't contain the original header (column names) anymore. Any clue why? Is there a way to save and keep the header? 

Thanks!
Pierre

**Comment by anjakefala** [comment]
Hey @p-levy!

Could you provide your version of VisiData, a sample file that has the issue, and the steps you took? And please share any options that you may have set.

Thanks!

**Comment by p-levy** [comment]
Hi Anja, 

Thanks for your fast answer. Here's a bit more info. 

```
$ vd --version
saul.pw/VisiData v2.11
```

This is a sample file. 
[test_sample.txt](https://github.com/saulpw/visidata/files/13702872/test_sample.txt)

The steps I took are:
1) `vd test_sample.txt`
2) Remove `col1` using the `-` key
3) `ctrl+S` to save the file under name `test_sample2.txt`
4) close with `q`
5) `vd test_sample2.txt` 
6) observe that the header is gone (first row is considered header now)

And that's pretty much it. No other options set. 

Thanks!
Pierre

**Comment by saulpw** [comment]
Ah, I see what's going on here!  The `txt` format is not the same as `tsv`.  It loads successfully because there are many tsv files with the `.txt` extension, but to VisiData the `txt` filetype is for text files.  If you want to save it as tsv anyway, pass `--save-filetype=tsv`.

One heuristic we might think about using, is to save txt like tsv if you're saving multiple columns, and remove the header if you're only saving a single column.  It's a bit magical but a one-column "tsv" is a rare case.

**Comment by p-levy** [comment]
Hi Saul, 

Indeed it works when I save the output as `.tsv` ! Amazing ! Thanks !
