### ISSUE TITLE
[statusbar] crash in recentStatusMessages

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#2174]
**Small description**
recentStatusMessages crashing at line 162

**Expected result**
No crashes

**Actual result with screenshot**

I don't have a stack trace for you, I'm having some issues recreating, but hoping that the description might be helpful, in case someone else sees it.  I have seen it multiple times.

The issue is on statusbar.py line 162 in recentStatusMessages:

```
RunteimError: OrderedDict mutated during iteration.
```

**Steps to reproduce with sample data and a .vd**

It seems to happen when trying to do a select on a frequency table with lots of rows representing lots of rows in the source sheet.
I've seen it mostly on playback when starting VisiData.

**Additional context**
Please include the version of VisiData and Python.  Latest develop branch and Python 3.11.5

I know this is a bad report since I provide neither the full stack trace or the good case to reproduce.  
I will mention that I started to see this somewhat recently, maybe a couple weeks.  There

**Comment by midichef** [comment]
I have run into this several month ago, in a very artificial situation, debugging by making tens of thousands of status messages via `vd.status()`. (It was after plotting every pixel in a `GraphSheet` with lots of points.) In my case it happens because the list of status messages gets so long that new status messages come in before the old list has finished being iterated over.

Making a separate copy of `vd.statuses` via `copy()` in `recentStatusMessages()` did not fix it. Making the copy took long enough, that I got the same problem, where new status messages came in before copying could finish.

**Comment by frosencrantz** [comment]
The code is here: 

https://github.com/saulpw/visidata/blob/develop/visidata/statusbar.py#L160-L164

I was thinking that maybe a copy could be made. so glad you know that won't help.  Maybe it could just be wrapped in a try/except in the RuntimeError or maybe instead of using OrderedDict it uses a different data structure like a list or Queue?

**Comment by saulpw** [comment]
This must happen when the statuses are displayed in the draw thread, while a new status message is added in different thread.  I can see why copying `vd.statuses` would reduce but not eliminate this issue.

When @frosencrantz used "crash" in the original title, I realize he meant that the program aborts (due to uncaught RuntimeError).  That's the key thing we want to address.  I don't think it's worth it to fix the underlying race condition (though if copying vd.statuses reduces its occurrence then we should do that anyway, it's simple enough), but bombing out of a live session is unacceptable.

So I've added a general `vd.callNoExceptions()` function, which catches all exceptions and logs them as status messages instead, and all the drawing calls are wrapped with this now.  With `--debug` it will reraise the exception and abort still, or you can trigger the same behavior and see the stack trace with `Ctrl+Q` (useful if the status drawing code is itself broken).  But this kind of error should just be a blip in the status messages, and not be disruptive to actual usage.

**Comment by frosencrantz** [comment]
Do you mean `Ctrl+E` will still show these execeptions?  Not `Ctrl+Q`?  Also, I feel like exceptions wrapped in`vd.callNoException()` get tossed in the bitbucket, unless `--debug` is specified.  Should all of those exceptions still be shown as status messages?

**Comment by saulpw** [comment]
@frosencrantz `Ctrl+E` will show them within VisiData and is the preferred method, as always.  I probably shouldn't have made a point of mentioning `Ctrl+Q` since it's a developer tool (debugging errors when the error page itself is unviewable for some reason), but I couldn't help myself.

As for `vd.callNoExceptions`, the exceptions are still logged with `vd.exceptionCaught`, so they will show up as status messages, and are viewable via `Ctrl+E`.  Maybe it should be renamed to `vd.callCatchExceptions`.  I had a hard time deciding on a name and just went with the same pattern as `checkCursorNoExceptions`, so that `NoExceptions` just means "no exceptions will be raised outside of this method".

**Comment by frosencrantz** [comment]
Thanks for the explanation @saulpw.  I'll watch a little closer for the exceptions, because it feels like they are being lost. After the commits in this issue, I still saw the original error from  crash vd, but I was running with `--debug`, so that is expected.  I'll see if I can find this error without the debug flag.
