### ISSUE TITLE
": regex" is problematic for big files

### ISSUE THREAD

**Issue by aborruso** [saulpw/visidata#219]
The number of output columns of `: regex` is determined by example row at cursor.

Than if I have a table with 20000 records and I have a field/column with inside a separator, in some way I must know the row number of the cell with the maximum number of separators, go there and than apply `: regex`.

I think that It would be better to determine the number of output columns, based on maximum number of separators inside that column.

I hope that it's not a stupid idea.

Thank you

**Comment by saulpw** [comment]
Yes; this is also a problem for `capture-col` (`;`) and `expand-col` (`(`).  It is not reasonable to do it over all rows, because some sheets will have millions of rows and by design we don't want to automatically scan over all rows for a column creation command like this.

However, one thing we could do pretty easily, is use all `visibleRows`, which are all the rows currently visible on the screen.  Would that be better?

Alternatively, there could be version you could put in your .visidatarc, which would start a background thread to check all rows and add new columns as it finds them.

**Comment by aborruso** [comment]
Hi @saulpw visidata is for me a great tool, and above alle a great idea.

But this one is a topic for which I have some doubt and I'm writing here because I love vd and its developers.

A column is by default an important structural element and the size of column is strictly related to the total rows number. 
Split column is a common task in spreadsheet, in pandas, in R, in OpenRefine, in miller, ecc. and by default it is applied over all rows (in some cases it is the only way (you cannot apply only at certain lines). And for me it has sense, because if you change something related to columns, you are changing data structure; using "vd split" way to do it, you could have a part of a sheet with a structure and another with a different one, using the "vd split" way you often could find out that you do not have done the right split process.

Speed is important but I think that for split columns it is a cost that must be paid, and also it's an expected cost.

I will try do add it to .visidatarc, but probably I'm not able to do it. 
I think that vd should have inside it the possibility to do a pure full split (as option and keep the current default mode).

Thank you

**Comment by cwarden** [comment]
I solve this by adding a numeric column using an expression that returns the size of the column to be split/expanded, then sort by this new column before splitting or expanding.

**Comment by aborruso** [comment]
Thank you @cwarden
