### ISSUE TITLE
Unintuitive command selection in palette

### ISSUE THREAD

**Issue by reagle** [saulpw/visidata#2219]
First, congrats on releasing 3.0 for 2024! 

Following #2154, I was using the new system for year end bookkeeping and, perhaps I'll get used to it, but something felt off in some interactions. For example, when combining two sheets, I type `&` and `ap` to start "append" but I see no visual sign that `append` is the current candidate; I find myself hitting `tab` to autocomplete it (and then hit `enter` to invoke it), but `tab` moves the row selector. Perhaps having a highlight on the current candidate would be enough?

<img width="323" alt="SCR-20240101-lelo" src="https://github.com/saulpw/visidata/assets/596814/82076c1c-0e54-4d1f-8226-3611309f0e22">

Also, for the colored columns in the palette, why is it: color, shortcut, color, background, color? I'd expect one color for keys and another for commands. Also note that long keys (such as BUTTON1_RELEASED) would look better with this simpler approach too.

<img width="280" alt="SCR-20240101-lcpi" src="https://github.com/saulpw/visidata/assets/596814/9a00f351-19cb-4e70-9c9a-a255c29f3c2a">

These are initial impressions I'm capturing on first usage, perhaps I'll get the hang of it and close, or I'll be able to substantiate my impression more concretely.

**Comment by saulpw** [comment]
This is good feedback, @reagle.

> when combining two sheets, I type & and ap to start "append" but I see no visual sign that append is the current candidate;

It's intentional that you have to press `Tab` to move the cursor to the list of matching commands, so you can press `Up`/`Down` without it invoking history, and also so you can press the numeric quick shortcuts.  One thing we can do though, is show `Enter` as the quick shortcut key for the top item before you press `Tab`.

> Also, for the colored columns in the palette, why is it: color, shortcut, color, background, color? I'd expect one color for keys and another for commands. Also note that long keys (such as BUTTON1_RELEASED) would look better with this simpler approach too.

We should give `BUTTON1_RELEASED` a better name anyway; `LeftRelease`? `ReleaseMouseL`?  But also I agree, we can make this look better regardless.  I think a separate color for keys and commands makes sense.

**Comment by reagle** [comment]
Thanks for the response @saulpw . On the interface issue, perhaps the thing that is off for me is after I press `&` it looks like I'm being given the command palette (with its logic of completion, selection, numbers) but it isn't -- until I hit tab. Instead, I am what I'll call the command parameter selection mode. `&` is the command and `append` etc. is the parameter.

Would it be better to go directly into palette interface logic as soon as `&` is hit, or would that confuse people expecting to hit `tab` or wanting to use `up/down` for history? I'm thinking its probably useful to maintain both (as is) but the command completion interface could have a more distinct visual cue (e.g., another shade of green from the palette and sidebar)?

**Comment by gennaro-tedesco** [comment]
When scrolling through the command palette entries with `Tab` is `Enter` supposed to invoke the current entry (where the cursor tab is on)? The behaviour that I see at the moment is that `Enter` executes the current command in the command palette even if incomplete, instead of executing the entry the cursor is on: is this intended behaviour?

To clarify let's assume:
1. I am typing `o` `p` `t` to browse the options sheet
2. the fzf algorithm shows many entries matching the characters 
3. I manually scroll to a certain entry (the command palette is still filled only with `opt`) 
4. I hit `Enter` on the entry I am on
5. the executed command is still `opt` only (thus throwing an exception of `no such command`)

**Comment by reagle** [comment]
@gennaro-tedesco I too noticed this but I suspected incomplete commands were making their way into the history as I experimented with this issue (and pressed `ESC` more than I would). It's good to know history is getting incomplete commands by way of successful (completed) command invocations.

**Comment by saulpw** [comment]
> Would it be better to go directly into palette interface logic as soon as & is hit, or would that confuse people expecting to hit tab or wanting to use up/down for history?

We had that originally, but had to change it because the 1-9 digit shortcuts interfered with typing aggregators like `p25`.

**Comment by saulpw** [comment]
The other issue is that the parameter for `aggregate-col` can be multiple aggregators, and so if you press `Enter` there, you want it to take the existing set of aggregators, and not the currently selected aggregator from the palette.

It might be that we're asking the command palette to do too much.  But, it seems we do want similar things when choosing a jointype or aggregators: fuzzy search, help text, quick shortcuts, along with the ability to just type it out.

**Comment by saulpw** [comment]
It should now accept the top item with `Enter` even before `Tab` is pressed.  `Tab Enter` should give the same result. This is currently not indicated in the UI but seems intuitively reasonable.

Secondly, the input command palette is used in two ways: to select a single input (a longname or jointype); and to select multiple aggregators.  

This also should now be fixed so that in the first/single case, once `Tab` has been pressed, `Enter` will select the current item under the cursor, even if different text has been typed.  In multiple mode, additional aggregators can be added with `Space`, and then `Enter` will select all the inputs so far, and also the current item but only if it was partially typed out already.

**Comment by reagle** [comment]
Thank you; I suspect this will make things easier, but it'll take me some time to grok. Two small followups:

1. I think a different color or framing would help distinguish the type of input (history completion vs command palette).
2. The initial order of join types is no longer alphabetical. Now my starts: inner, outer, full, diff, append, ... Is this intentional, or perhaps determined by my specific history?

**Comment by saulpw** [comment]
2. It's sorted by your frequency of use, but only for the current session right now.  In my mind this would be persisted.  So this ordering you're seeing is probably ad hoc.
