### ISSUE TITLE
[cosmetic] have the sidebar overlap the command palette

### ISSUE THREAD

**Issue by anjakefala** [saulpw/visidata#2241]
![Screenshot from 2024-01-07 22-19-10](https://github.com/saulpw/visidata/assets/7489659/ee3de614-5b5e-4cf4-ae1f-223faf3e2b52)

Currently, the command palette overlaps the sidebar.

**Comment by gennaro-tedesco** [comment]
Along the same lines as [this comment](https://github.com/saulpw/visidata/issues/2202#issuecomment-1875173660): is it possible to toggle the sidebar off completely (sometimes it is a little invasive). It seems that the option `options.disp_sidebar = False` does not do, or is it not intended to completely hide it all the times?

**Comment by anjakefala** [comment]
@gennaro-tedesco `b` should do it for the current sheet!

I think the reason `options.sidebar` is not doing the trick, is because Sheet-options override general options sometimes, and the `disp_sidebar` check happens for the Sheet-option. I'll copy-paste this into that thread.

The current workaround for you is to play with `options.disp_help = 0`. I'm not sure if `disp_help` will stick around conceptually, but for 3.0.x, you can use it to turn off the sidebar by default.

**Comment by gennaro-tedesco** [comment]
`b` does indeed toggle the sidebar off, however only for the current invocation. Display any other action that would require the sidebar would toggle the sidebar back on (and the user would have to press `b` all the times). `options.disp_help = 0` does not affect the sidebar either.

I understand this is just minor nitpicking, however I wanted to mention this behaviour in case you happen to do some work on the sidebar and may consider this too :)

**Comment by saulpw** [comment]
With `options.disp_sidebar=False`, the sidebar is only be shown for input help and status messages.  Input help can be disabled with `vd.options.disp_help=0` with the above change.  There is no way to disable the sidebar entirely for status messages, but any command will clear the status sidebar, including `Ctrl+L`.

We do need a better knob to control how the sidebar works, but that's for #2202.  This issue is specifically for the "cosmetic" issue where the sidebar is quite unhelpfully obscured by the command palette.
