### ISSUE TITLE
Check Singularity Image for using Visidata on HPC clusters

### ISSUE THREAD

**Issue by paulklemm** [saulpw/visidata#225]
Thank you so much for this tool, it's making my life as a bioinformatician working with genetic data so much easier.

To be able to use it on our HPC cluster I made it into a Singularity image. Singularity is a containerization tool built for HPC where you do not need superuser privileges.

The image is straightforward, can you please check if I installed everything properly as you would expect: https://github.com/paulklemm/visidata-singularity/blob/master/Singularity

For me it already works fine.

**Comment by anjakefala** [comment]
This is so exciting @paulklemm! I was a bioinformatician in my previous life, and I wished visidata existed back then. ^^

On initial glance, everything looks fine. I will take a more detailed look soon. =) Thanks!

**Comment by anjakefala** [comment]
:wave: @paulklemm 

There were only two things that stood out to me:
1. You are installing python3-dateutil using apt instead of pip3! I am curious about why?
2. You are currently installing the dependencies for all of the data format loaders, which may not be necessary depending on your use case. =) Excepting dateutil, every other dependency is optional. You can see a reference here: http://visidata.org/man/#loaders for the data formats visidata supports, and the dependencies required for loading them.

But this is totally fine as-is. 

Thank you for coming by and sharing this with us. :blush:

**Comment by paulklemm** [comment]
Thanks @anjakefala for looking at the code.

> You are installing python3-dateutil using apt instead of pip3! I am curious about why?

You're right, I will install dateutil with pip3.

> You are currently installing the dependencies for all of the data format loaders, which may not be necessary depending on your use case. =) Excepting dateutil, every other dependency is optional. You can see a reference here: http://visidata.org/man/#loaders for the data formats visidata supports, and the dependencies required for loading them.

For my use case I only need the packages for loading Excel files. I installed the dependencies for other loaders to make the image viable for other users as well.

Thank you guys for developing this great tool, it is heaven-sent. By the way, I found the [Jeremy Singer-Vine VisiData Introduction](https://jsvine.github.io/intro-to-visidata/) and [Saul's video demonstrations](https://www.youtube.com/playlist?list=PLxu7QdBkC7drrAGfYzatPGVHIpv4Et46W) most helpful to get started with the tool. Great resources that you can expand on 😊.
