### ISSUE TITLE
Help wanted: how to use describe sheet to select columns?

### ISSUE THREAD

**Issue by aborruso** [saulpw/visidata#226]
Hi,
I have a very messy sheet, in which I need to delete some columns. 
A way that would be very comfortable for this sheet is to open the describe sheet and select some columns (with just a few clicks) based on the count of null values per field.

Is it possible to select columns starting from describe sheet? If yes how to?

Thank you

**Comment by saulpw** [comment]
Yes, you can use the same select operations on the describe sheet as you can on other sheets.   Then you can use the `g-` operation (inherited from the ColumnsSheet) to hide the columns.  Using `gd` will not work because the DescribeSheet makes a copy of the columns list, excluding the hidden columns.

**Comment by aborruso** [comment]
Thank you very much
