### ISSUE TITLE
Some undefined keystroke

### ISSUE THREAD

**Issue by aborruso** [saulpw/visidata#228]
Hi,
I have these undefined keystroke

![image](https://user-images.githubusercontent.com/30607/49886541-37a63d80-fe3a-11e8-8abc-2eb0375076d9.png)

I need to set especially the rename-sheet one. How to do that and fix it?

Thank you

**Comment by aborruso** [comment]
I want to add that however the space key is always the solution, a very comfortable way to find the command you are searching.

**Comment by anjakefala** [comment]
Hi @aborruso! =)

From this page: http://visidata.org/docs/customize/

# Creating command aliases for existing commands

   a) To create a global keybinding, add `bindkey(keystroke, longname)` to your .visidatarc.

b) To set the binding for a particular sheet type, add `<Sheet>.bindkey(keystroke, longname)` to your .visidatarc, where `<Sheet>` is a SheetType.

So to set a keystroke for `rename-sheet`, you could add:

```
bindkey('w', 'rename-sheet')
```

to your .visidatarc. Be careful because bindings defined in your .visidatarc will overwrite default ones.

Additionally, `rename-sheet` is also accessible by mouse. =) Just right-click on the name of the sheet in the bottom left corner of the status bar.

Let me know if any of this is unclear, so I can update the documentation!

**Comment by aborruso** [comment]
Hi @anjakefala very clear, thank you.

> Additionally, rename-sheet is also accessible by mouse. =) Just right-click on the name of the sheet in the bottom left corner of the status bar.

With right click, using vd 1.5 and Linux WSL on Windows I have 

![image](https://user-images.githubusercontent.com/30607/49925302-c48fdc00-feb8-11e8-953b-ef2441c4affc.png)

**Comment by saulpw** [comment]
@aborruso that's interesting...on Linux we get a `BUTTON3_PRESSED` first.  Looks like WSL only gives the RELEASED action.  So that option may not work for you :/

**Comment by aborruso** [comment]
@saulpw no I have also pressed, but nothing happens

![image](https://user-images.githubusercontent.com/30607/49930688-64ebfd80-fec5-11e8-8585-4fd727700ec1.png)

**Comment by saulpw** [comment]
That is very weird...do any of the mouse commands work for you?  (left click, scroll-wheel?)

**Comment by aborruso** [comment]
@saulpw scroll-wheel down works, to scroll down a table
