### ISSUE TITLE
Partially off-topic: how to create the dpkg of vd?

### ISSUE THREAD

**Issue by aborruso** [saulpw/visidata#231]
Hi,
for me it's impossible to use the pip way to install vd (not able to solve [this](https://github.com/saulpw/visidata/issues/192#issuecomment-435650576)), the only that works for me is this one http://visidata.org/install/#dpkg.

Now there is the 1.5.1 release and I cannot use it. Is there some README that I can use to build on my own the dpkg of vd?

Thank you

**Comment by anjakefala** [comment]
Hi!

=D

The issue is that the essence of a debian package is its bureaucracy.

So, It is a little bit convoluted: https://github.com/saulpw/visidata/blob/stable/dev/checklists/release.md#debian . The essence is that you can you use `debuild` along with our debian config stuff here: https://github.com/saulpw/visidata/tree/stable/dev/debian .

You may have to 'update the changelog' but you should hopefully not have to sign the package.

**Comment by anjakefala** [comment]
If you have trouble with it, our debian repository will be uploaded sometime in the next while. =) I will leave a message here when it is.

**Comment by aborruso** [comment]
I think it's hard for me, but I'll try, thank you

**Comment by anjakefala** [comment]
I think so, too. ._.

I will definitely ping you when the debian is publicly ready!
