### ISSUE TITLE
[dev] Column cache "async" isn't dynamic

### ISSUE THREAD

**Issue by justin2004** [saulpw/visidata#2325]
the command `addcol-expr` (with default keystroke `=`) is dynamic in that if you derive a new column and then change the source column the derived column will update (as expected).

however, when you use the Column cache "async" option the dynamic behavior doesn't happen.

e.g.

```bash
$ cat ~/.vdrc_test 

class AsyncExprColumn(ExprColumn):
    def __init__(self, name, expr=None, **kwargs):
        super().__init__(name=name,expr=expr,cache="async", **kwargs)

Sheet.addCommand('=', 'addcol-expr-async', 'addColumnAtCursor(AsyncExprColumn(inputExpr("new column expr="), curcol=cursorCol))', '')

$ cat apple.csv 
name,size
gala,44
pink lady,54

$ vd --config ~/.vdrc_test apple.csv
```
and in the sheet if i set the size column to be numeric then run `=` with expr `size+1` it works the first time.
but if i change the size value for a row then the `size+1` column does not update.

![image](https://github.com/saulpw/visidata/assets/16325158/18d7669b-06bc-4ea4-9583-5a95d9902421)

i don't think asynchronous implies static, right? can't it be async and dynamic?

**Comment by saulpw** [comment]
That's right, `cache="async"` means to cache the column (make it non-dynamic), but do the caching asynchronously (in other threads).  This is meant for long-running operations so that they're only done once and don't freeze up the interface.  `z'` should reset the cache manually if you want the results to change.

**Comment by justin2004** [comment]
thanks @saulpw . i didn't know about `z'`. 

though it feels like caching `on` and async `on` could be orthogonal. that is, in this case i want cache `off` and async `on`. that is, asynchrony isn't a cache strategy it is an execution strategy.

**Comment by saulpw** [comment]
Well, that wouldn't work how you want either, because VisiData recalculates its cells on every draw cycle.  For a quick demonstration of this, try `=random()`.  It settles down after a second or so, but then will restart on every command, including movement.  If we allowed "cache off and async on" as you suggest, it would spawn dozens of threads for each command.

Of course, we could have it recalc only when the sheet is modified.  But the sheet is also considered modified more often than you would think--for instance, when you hide a column.  So by default we assume calculations are not expensive, and if they are expensive, then they are expensive enough to be cached until the user triggers a cache reset.

**Comment by justin2004** [comment]
> because VisiData recalculates its cells on every draw cycle.

i noticed that the first time i derived a new column with a function that made a REST call over the wire. yikes!

but i memoized the function and that worked well. that was before i saw the cache Column option.

maybe i can get the behavior i am looking for by triggering a `resetCache` on some cues.
