### ISSUE TITLE
text loader calls strip() on lines

### ISSUE THREAD

**Issue by justin2004** [saulpw/visidata#2328]
today i used vd to browse an s3 bucket and then i opened a smtp file (that was in the s3 bucket) as plain text and, from vd, saved the smtp file as `email.txt`.

then hours later (while i was having trouble getting the `email` library to read that file and walk over the attachments in the email) i realized that the leading spaces in an smtp file are significant and the vd txt loader calls `strip()` on the lines:
https://github.com/saulpw/visidata/blob/develop/visidata/textsheet.py#L35

is that desirable in all cases? i was relying on vd to give me the actual content of the file but i did not expect `strip()` to be called on the lines.

since that behavior isn't configurable should i just make my own version of `TextSheet` that doesn't do that?

**Comment by saulpw** [comment]
Well, this is interesting.  I expected this `strip()` to be from the very first iteration of TextSheet, an arbitrary choice that seemed sensible at the time.  But instead it's a very recent addition in 019e8c42485f067803d525d4f3eb3035e4f0ea11.  From surrounding commits it looks like it was probably intended to strip leading spaces when displaying guides.  (These leading spaces were there because the guide text was quoted in code.)

I believe this .strip() should no longer be necessary, since @anjakefala migrated the guides to their own .md files in b8a8b5b1c8f84d01a86473d09583d9dcf1a2fa04.  So I think we can remove it now anyway.  Sorry for the inconvenience.

**Comment by justin2004** [comment]
@saulpw , thanks
