### ISSUE TITLE
Significantly slower selection of matching error cells in v3.0.2 vs much older version

### ISSUE THREAD

**Issue by NickOveracker** [saulpw/visidata#2335]
**Small description**
Yesterday I installed an old version of vd with a very outdated version of pip. I don't remember the original version number, but it wasn't version 3. The interface and plugin list matched the tutorial screenshots.

Today, I updated pip and installed the latest version of VisiData, v3.0.2.

I'm not at liberty to share the full dataset, but I can share a single screen of it below.

![vd_scrsh](https://github.com/saulpw/visidata/assets/6864226/b82f3d2d-8cd5-4abe-b759-41baa0412d0e)

**Expected result**
The cmdlog should have executed completely within a few seconds.

**Actual result with screenshot**
The "select rows matching current cell in column" commands took a very long time to execute. For the commands executed in the screenshot below, the first several commands took around 6 seconds, and the final "select" command took 91 seconds to complete.

The cell was a Python error cell for a calculated column. I was selecting all cells with errors in order to determine the most common sources of errors.

![vd_scrsh2](https://github.com/saulpw/visidata/assets/6864226/74f86f96-03f3-4e43-b4bd-1cd06ebe1766)

**Steps to reproduce with sample data and a .vd**
The following sample dataset and cmdlog are sufficient to reproduce the issue.

[faa-wildlife-strikes.csv](https://github.com/saulpw/visidata/files/14468661/faa-wildlife-strikes.csv)
[faa-wildlife-strikes.vdj.txt](https://github.com/saulpw/visidata/files/14468663/faa-wildlife-strikes.vdj.txt)

**Additional context**
VisiData v3.0.2
Python 3.8.0

**Comment by NickOveracker** [comment]
The more I think about it, the less sure I am that the revision number wasn't 2 instead of 1. In any case, I followed the tutorial with it, and both the overall interface and pre-packaged plugin list matched whatever version was in the tutorial screenshots.

**Comment by anjakefala** [comment]
Hi @NickOveracker! Thanks for providing a repro. Unfortunately, I wasn't able to reproduce the performance drop you saw.

Batch mode
develop: vd -p 2335.vdj --batch  4.39s user 0.24s system 100% cpu 4.627 total
v2.11: vd -p 2335.vdj --batch  4.77s user 0.20s system 100% cpu 4.966 total

Live mode
develop: vd -p 2335.vdj  6.77s user 0.27s system 87% cpu 8.066 total
v2.11: vd -p 2335.vdj  6.44s user 0.29s system 94% cpu 7.094 total

It doesn't seem like we had a performance drop with the v3.0 bump. 

I duplicated the size of the sample data, so that it's closer to the number of rows in the data in your screenshot (~142K)
develop: vd -p 2335.vdj --batch  8.93s user 0.35s system 100% cpu 9.277 total
v2.11: vd -p 2335.vdj --batch  9.89s user 0.46s system 99% cpu 10.343 total

And I'm seeing an improvement in performance in v3.x. I'm definitely not seeing the 91 seconds you saw. I wonder if VisiData was needing to compete for computing resources with something else running on your machine?
