### ISSUE TITLE
system crash opening large (compressed) file

### ISSUE THREAD

**Issue by tompropst** [saulpw/visidata#2384]
**Small description**

My system will consistently become unresponsive some time after opening a large data file in `bz2` compressed JSON

Some requested data is not available given the outcome of the issue

**Expected result**

Maintain system control regardless of whether or not `vd` is functioning

**Actual result ~~with screenshot~~**

System will hang indefinitely

**Steps to reproduce ~~with sample data and a .vd~~**

*I cannot provide the exact data file as it contains sensitive information. If needed, I can try to create a sanitized data set however it will be quite large.*

1. Launch `vd`
2. Navigate to the location of a large data file
    - My case specifically had a 76.5MB `bz2` compressed JSON data
    - The file would expand to 2.7GB of JSON
    - *I have to mention I was thrilled to see that `vd` will open the compressed file at all*
3. Open the large file
4. Observe that the file appears to open however part way through processing all the rows, everything stops and the system is completely unresponsive

My system is admittedly not up to this task however I would expect either a failure to attempt to load the file or if possible, a partial load of the file.

System:

* Ubuntu 22.04
* Lenovo Thinkpad with Intel I5 processor
* 16GB of memory

~~Please attach the commandlog (saved with `Ctrl-D`) to show the steps that led to the issue.~~

**Additional context**
Please include the version of VisiData and Python.

* VisiData 3.0.2
* Python 3.10.12

**Comment by midichef** [comment]
I run the same OS as you, Ubuntu 22.04, so I looked into this problem. On my system, it's not specific to visidata. Any program that uses more RAM than I have, makes my system unresponsive.

It is not straightforward to configure your system to handle being out of memory. You can change how much swap space your system has, and you can change OS parameters like "swappiness". But from what I can tell by reading Stack Overflow, there's no simple best solution for every use case.

So instead I would recommend that you cap the amount of RAM that visidata can use, by making a shell script that wraps around visidata and running that instead of `vd`. You could call it `vdcapped`, and it would have these lines:
```
#!/bin/sh
# vdcapped - run visidata with a limit on how much memory it can use
ulimit -v 15000000  # limit processes to 15GB of RAM
vd "$@"
```
When visidata uses more than 15GB, the vd process will end, with `MemoryError` stack traces. That way you can continue using your system.

Note, I first tried running `ulimit -v 15000000` in my shell login file, to cap the memory used by all my processes, not just visidata. But that caused Chrome to crash on startup. So I don't recommend you do that.
