### ISSUE TITLE
[multiline] wordwrap for non-single-width characters (CJK)

### ISSUE THREAD

**Issue by duofinal** [saulpw/visidata#2416]
**Small description**
  Only english text works correctly when using multiline command (wrap text)

**Expected result**
  Wrap text should work for all languages

**Actual result with screenshot**
- [sample.csv](https://github.com/saulpw/visidata/files/15496265/sample.csv)
![image](https://github.com/saulpw/visidata/assets/1624712/9147269e-05ea-4f50-a668-bb7b7c6b0eb5)

**Steps to reproduce**
  open a file -> execute multiline command (v or View -> toggle display -> multiline)

**Configuration**

- Does this issue reproduce without any plugins or configuration (using the `-N` CLI flag)?
  Yes
- Does this issue reproduce with either the [latest release](https://www.visidata.org/releases/), or with the [develop branch](https://www.visidata.org/install/#update-visidata-from-an-existing-installation)?
Latest release v3.0.2 

**Additional context**

- What platform and version are you using (Linux, MacOS, Windows)?
 Ubuntu 22.04
- Which version of Python?
 3.11.5
- Which terminal are you using (for display and input issues)?
  iTerm2 with macOS and use the ubuntu remotly

**Comment by saulpw** [comment]
Can you provide sample data like that used in the screenshot?

**Comment by duofinal** [comment]
yes i've updated issue

**Comment by midichef** [comment]
I looked into this a bit, for Python 3.10.12. The trouble seems to be the use of `textwrap.TextWrapper._wrap_chunks()`. The wrapping calculations there use `len()` for strings, where visidata would use their display width `dispwidth(s)`. As a quick check, I seem to get proper wrapping when I use a modified version of `_wrap_chunks()` for `sheets.py`.

```
def dispwidth_wrap_chunks(self, chunks):
    len = dispwidth
    # the rest of the function is unmodified from the original _wrap_chunks()
    ...
textwrap.TextWrapper._wrap_chunks = dispwidth_wrap_chunks
```
So one solution would be to subclass `textwrap.TextWrapper` to override `_wrap_chunks()` with a version that uses `dispwidth()` instead of `len()`. Then replace `textwrap.wrap()` with `wtw = WideTextWrapper(); wtw.wrap()`. Overriding like that is [a solution that textwrap puts forward](https://github.com/python/cpython/blob/a8f1152b70d707340b394689cd09aa0831da3601/Lib/textwrap.py#L22-L23):
>  If you want to completely replace the main wrapping algorithm,
    you'll probably have to override _wrap_chunks().

**Comment by saulpw** [comment]
Several other projects subclass TextWrapper to override _wrap_chunks(), in order to handle variable width characters:

- [sphinx-doc/sphinx](https://github.com/sphinx-doc/sphinx/blob/f0dc8239cd291176f2421d08f2b3c096cb5785c1/sphinx/writers/text.py#L266)
- [paaguti/python-tabulate](https://github.com/paaguti/python-tabulate/blob/817e3065fa72e865f63026774b2eec186a7a17ea/tabulate/__init__.py#L2601)
- [facebook/sapling](https://github.com/facebook/sapling/blob/3b72c4df969c6c0f75a5f885fa8d5d27018d6766/eden/scm/sapling/util.py#L2748)
- etc

Here is the Python PR (open since 2021) that could fix it: https://github.com/python/cpython/pull/28136

It's not perfect, so it's not been merged.  I suggest we throw our weight behind that, and/or help it become more perfect.  In the meantime, if someone wants to take that code into VisiData immediately, in `visidata/_textwrap.py`, such that if/when the Python PR is merged, we can use the Python implementation for newer versions and then ultimately delete our interim implementation, then we can merge that to close this issue and do some field testing for the Python PR and prove its mettle.

**Comment by midichef** [comment]
It looks like [the latest version of jquast's `wcwidth`](https://github.com/jquast/wcwidth/releases/tag/0.6.0) solves this problem.  `wcwidth.wrap()` appears to be a drop-in replacement for the `textwrap.wrap()` that we currently use, that wraps wide characters properly.
