### ISSUE TITLE
[question] vdsql duckdb in memory

### ISSUE THREAD

**Issue by jknaus** [saulpw/visidata#2449]
Is it possible to connect to an in-memory duckdb instance with vdsql?
If yes, what would be the correct command to do this?

**Comment by midichef** [comment]
I do not think it is possible, due to how duckdb works. In my testing, on Ubuntu, it does not appear that an in-memory duckdb database can be accessed from another process.

If you are on a Unix-like system, an alternate solution is to have duckdb use a file in /dev/shm, as [described for sqlite on Stack Overflow](https://stackoverflow.com/a/24996109). A file there will store the file contents in RAM, not on disk, so in that sense it is like an in-memory database. But because it is a file, its contents can be read by other duckdb processes.

I have attached the code I used to demonstrate that in-memory duckdb data can't be shared across processes, and that /dev/shm data can.
[ducktest.py.txt](https://github.com/user-attachments/files/17039501/ducktest.py.txt)
Run it in two different windows, as `ducktest.py maker` and `ducktest.py reader`. That will show that files in /dev/shm do allow data to be shared. Then change `use_shared_memory_file` to `False` and see that in-memory databases do not allow data be shared.
