### ISSUE TITLE
Use value_counts()/describe()/etc for derived sheets of PandasSheet

### ISSUE THREAD

**Issue by azjps** [saulpw/visidata#250]
I haven't done timings, but for a medium-sized `pandas.DataFrame` of ~1 million rows, computing a frequency or describe table for a column of a `PandasSheet` takes a significant amount of time (I'd estimate tens of minutes). It would be nice if `pandas/numpy` vectorized operations were used such as `DataFrame.value_counts()` and `DataFrame.describe()`, since this computation should be very fast to compute for a DataFrame of this size:

```python
In [11]: df.shape
Out[11]: (968981, 73)

In [12]: %timeit df.int_column.value_counts()
58.8 ms ± 1.73 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [13]: df.int_column.value_counts()
Out[13]: 
103296875000    57661
103187500000    55473
103218750000    53819
103234375000    53511
# ...
```

(Happy to work on a PR but would probably need a couple of pointers.)

**Comment by saulpw** [comment]
Hi @azjps, thanks for the suggestion!  I think it would be great if pandas were better supported.  The current [PandasAdapter](https://github.com/saulpw/visidata/blob/develop/visidata/loaders/_pandas.py) is really just a glorious hack, so I'm glad it's working as well as it is. 

It wouldn't be that difficult to make an optimized PandasFreqTable, which would be a little less exciting than the regular FreqTable because it wouldn't be able to provide feedback when calculating, and you wouldn't be able to dive into or select or modify the source rows (unless there is a pandas method that returns a list of the rows or row indexes instead of just the counts?).  But if all you need is a quicker non-interactive summary, I can see this being a great addition.

If you're interested in submitting a PR, check out [how to create a loader](http://visidata.org/docs/loaders/).  Basically you'd start with:

```
PandasSheet.addCommand('F', 'freq-col', 'vd.push(PandasFreqTable(sheet, cursorCol))')

class PandasFreqTable(Sheet):
   def reload(self):
       # populate self.columns and self.rows according to aggregators and groups
```

and then write the reload() function.  See [freqtbl.py](https://github.com/saulpw/visidata/blob/develop/visidata/freqtbl.py) for how it does the columns, and you'd use pandas to create the rows.  I can't drive it myself but I'm happy to pair with you and/or provide and support you would need.
