### ISSUE TITLE
data doesn't fill available space in multiline mode

### ISSUE THREAD

**Issue by scottedwards2000** [saulpw/visidata#2506]
**Small description**
if I set options.default_height =20 for instance and then use multiline model ('v') i get more space per row, but the data still cuts off with "..."

**Data to reproduce**
csv data:

provisioning_trigger,digital_card_art_uri
auto_provisioned,https://assets.asdfasfd.com/card-art/combined-image-asset/a74e2cc6-0cb9-464a-a135-bd0f4cd3e159.png
auto_provisioned,https://assets.asdfasfd.com/card-art/combined-image-asset/a74e2cc6-0cb9-464a-a135-bd0f4cd3e159.png
auto_provisioned,https://assets.asdfasfd.com/card-art/combined-image-asset/a74e2cc6-0cb9-464a-a135-bd0f4cd3e159.png

**Steps to reproduce**

open file and T (transpose) and v (multiliine)

**Expected result**

given the extra-high rows, we should be able to see the full url on all columns

**Actual result with screenshot**

<img width="1145" alt="image" src="https://github.com/user-attachments/assets/74001736-0a05-4f1c-b160-8f8aec19ab33">

[If there is an error message, please include the full stack trace shown with `Ctrl+E`.]

**Configuration**

- Does this issue reproduce without any plugins or configuration (using the `-N` CLI flag)?
it does require the addition to .visidatarc above

- Does this issue reproduce with either the [latest release](https://www.visidata.org/releases/), or with the [develop branch](https://www.visidata.org/install/#update-visidata-from-an-existing-installation)?
yes

**Additional context**

- What platform and version are you using (Linux, MacOS, Windows)?
mac

- Which version of Python?
3.9.6

- Which terminal are you using (for display and input issues)?
built in macos Terminal

**Comment by saulpw** [comment]
Okay, so this was a deliberate choice to use `break_long_words=False` in [textwrap.wrap()](https://docs.python.org/3/library/textwrap.html).  See https://github.com/saulpw/visidata/blob/develop/visidata/sheets.py#L28.

I've made it so that `disp_wrap_` options are passed through to textwrap.wrap().  So now you can add `--disp-wrap-break-long-words=True` (or set in visidatarc of course), to get the behavior you want.  Other options from textwrap are also available.
