### ISSUE TITLE
Column using slow function as expr causes extreme slowness

### ISSUE THREAD

**Issue by juggernauthk108** [saulpw/visidata#2513]
I created a CSV with single line that has only 1 column called `location`. The only row in it is called "Paris".

Contents of ~/.visidatarc file

```
> `from geopy.geocoders import Nominatim
> def geocode(location):
>         return str(Nominatim(user_agent="geo").geocode(location).latitude)+","+str(Nominatim(user_agent="geo").geocode(location).longitude)`
```

Executing 

> =geocode(location)

 makes a new column with long,lat but this crashes the session

**Comment by juggernauthk108** [comment]
<img width="1300" alt="Screenshot 2024-09-03 at 12 46 29 AM" src="https://github.com/user-attachments/assets/3c4c30fa-3cde-45e3-8b15-10f4ed789ced">

sample snippet

**Comment by saulpw** [comment]
It's not caching the result so it's doing every location over and over again. Add a `@functools.lru_cache()` above the def.

**Comment by saulpw** [comment]
Also, this isn't crashing, since it never bombs out.  If it didn't respond at all, that would be "hanging".  However, it's still running and responding, albeit very slowly.

**Comment by juggernauthk108** [comment]
@saulpw thanks for quick reply. This fixed the issue. Want to understand if I am not writing the plugin file correctly or it is Visidata internals that I dont understand. Just to future proof myself should I have to do expensive operations per row in huge data-set.

Also, anyway to background a new column process if its taking longer?

**Comment by saulpw** [comment]
VisiData recomputes all cells on the screen every redraw, which avoids the classic spreadsheet recalculation issue.  With modern computers this isn't a problem for most things.  However, slower calculations need caching somewhere, and we put that either on the column or the slow function (as above).  For really expensive operations, you'll have to make a custom column (not hard) with `cache="async"`, so that every calculation spawns a new thread to calculate and cache the result in the background.
