### ISSUE TITLE
saving to XML: LookupError: unknown encoding: 'UTF-8-SIG'

### ISSUE THREAD

**Issue by reagle** [saulpw/visidata#2520]
> [!NOTE] mentioned on discord, @saulpw stated:
> I've been struggling with utf-8 vs utf-8-sig; it seems like we want to use -sig for reading but not-sig for writing.  The BOM should be completely unnecessary in utf-8 but some software adds it anyway, and this is encoding is supposedly the proper Python way of handling it.

I open an xml file fine, edit, but when I try to save I receive an answer:

...
/Users/reagle/.local/pipx/venvs/visidata/lib/python3.12/site-packages/visidata/loaders/xml.py", line 88, in save_xml
    vs.root.write(str(p), encoding=options.encoding, standalone=False, pretty_print=True)
  File "src/lxml/etree.pyx", line 2097, in lxml.etree._ElementTree.write
  File "src/lxml/serializer.pxi", line 616, in lxml.etree._tofilelike
  File "src/lxml/serializer.pxi", line 658, in lxml.etree._create_output_buffer
LookupError: unknown encoding: 'UTF-8-SIG'
``
/

**Comment by midichef** [comment]
I did some googling, [this comment on Stack overflow from 2019](https://stackoverflow.com/a/57756025) says like the `encoding` used by `lxml` needs to be an encoding accepted by libxml2/libiconv. That is, `utf-8` instead of `utf-8-sig`.

The latest `lxml` documentation supports that:
https://github.com/lxml/lxml/blob/6d5d6aed2e38e1abc625f29c0b3e97fc8c60ae3b/src/lxml/parser.pxi#L1592

I can't be 100% sure their remarks still apply, though. Because I can't reproduce the success of their test code on Ubuntu 22.04, even though the particular `OSF*` encoding is listed in the output of  `iconv -l`:
`lxml.etree.parse(io.BytesIO(b'<test/>'), parser=lxml.etree.XMLParser(encoding='OSF00010004'))`

And some things in that comment are no longer true. For example, `utf8` (with no `-`) is accepted by lxml as an encoding now, though they said in 2019 that it was not.

**Comment by saulpw** [comment]
Would setting `XMLSheet.options.save_encoding = 'utf-8'` be a quick fix for this issue?

**Comment by reagle** [comment]
I don't know if you were asking me, but for what it's worth, I added that in my .visidatarc, and it didn't work (got XMLSheet error).

**Comment by midichef** [comment]
@reagle Saving as XML should work with no .visidatarc changes needed, once saulpw's fix is in `loaders/xml.py`.

**Comment by reagle** [comment]
Confirmed fix! Thank you.
