### ISSUE TITLE
How do I transform column values in place with g* on v3.x?

### ISSUE THREAD

**Issue by reagle** [saulpw/visidata#2526]
Perhaps this is related to #2524, but `g*` is not working for me either.

I'm following the directions in the [docs](https://www.visidata.org/docs/columns/) "[How do I substitute text in my column]" (note the location to benchmarks.csv is broken; this heading is in brackets, and there is no section identifier).

https://asciinema.org/a/SJVLbVEruc5GViyUXwWCZJAU4

**Comment by anjakefala** [comment]
Ah! We should update the documentation for how to use `g*`.

Now, instead of using the `/`, you `tab` between `search` and `replace`. Beside search, you write the pattern to look for, and beside replace the string to replace it with. 

![Peek 2024-09-21 22-12](https://github.com/user-attachments/assets/7075f706-dd0d-479f-8eef-67d398595341)

**Comment by reagle** [comment]
Thank you, I was never able to get the substitution commands with `/` to work and now I know why. BTW: The documentation and manpage still have the slash.

**Comment by anjakefala** [comment]
This has now been documented in the new RegexGuide: https://github.com/saulpw/visidata/blob/develop/visidata/guides/RegexGuide.md#examples
