### ISSUE TITLE
delete-selected/save-sheet on DirSheet Deletes Only One File

### ISSUE THREAD

**Issue by cwarden** [saulpw/visidata#261]
Selecting multiple files on a DirSheet and using `delete-selected` to delete them marks them as deleted.  `save-sheet` then prompts to really delete all of the deleted files, but answering yes only deletes one file.

**Comment by anjakefala** [comment]
Ahh, good catch! =D

This was fixed in https://github.com/saulpw/visidata/commit/98e222c9d134241f0f6c3de062c394567d372ee4 and will show up in the next release or patch. 

****

Essentially [commit](https://github.com/saulpw/visidata/blob/98e222c9d134241f0f6c3de062c394567d372ee4/visidata/shell.py#L200), which is the powerhouse within DirSheet's `save-sheet`, is async. The clearing of [toBeDeleted and addedRows](https://github.com/saulpw/visidata/blob/98e222c9d134241f0f6c3de062c394567d372ee4/visidata/shell.py#L118) was happening before commit completed.
