### ISSUE TITLE
[pandas develop] Adding a column to a PandasSheet does not work

### ISSUE THREAD

**Issue by migueldvb** [saulpw/visidata#264]
Adding a row to a pandas dataframe in a separate thread works well as in this example.

```
import pandas as pd
import visidata as vd
from random import randint
import time


@vd.asyncthread
def changedata(df):
    while True:
        df.loc[len(df)] = [randint(0, 9), randint(0, 9)]
        time.sleep(1)

d = {'col1': [1, 2], 'col2': [3, 4]}
df = pd.DataFrame(data=d)

changedata(df)

vd.run(vd.PandasSheet('pandas', source=df))
```

However adding a column is not currently working as shown by the example below. This functionality is described [here](http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#setting-with-enlargement) and has been added to pandas around v0.13. The reason I encountered this problem is because joining two dataframes in a separate thread with the `asyncthread` decorator does not show all the columns as `vdtui` is lauched before the merging of dataframes takes place.

```
@vd.asyncthread
def changedata(df):
    while True:
        df.loc[:, df.columns[-1]+'*'] = [randint(0, 9), randint(0, 9)]
        time.sleep(1)

d = {'col1': [1, 2], 'col2': [3, 4]}
df = pd.DataFrame(data=d)

changedata(df)

vd.run(vd.PandasSheet('pandas', source=df))
```

**Comment by anjakefala** [comment]
Hi @migueldvb!

This was really fun to try out. :blush: The reason why this works for rows, but not columns, is actually an interesting one.

## Current workaround
If you want to reload the dataframe with asynchronously added columns, you can currently do so by pressing `^R` (`reload-sheet`). 

## Source of issue
It is due to decisions made in column and row setting in [PandasSheet's reload](https://github.com/saulpw/visidata/blob/develop/visidata/loaders/_pandas.py#L22). To create the rows, VisiData [indexes into the dataframe directly](https://github.com/saulpw/visidata/blob/develop/visidata/loaders/_pandas.py#L14). To create the columns, [it loads the dataframe, and checks columns once](https://github.com/saulpw/visidata/blob/develop/visidata/loaders/_pandas.py#L39). 

We are currently experimenting with indexing into the columns directly, and seeing how that plays out with other aspects of VisiData. If you want to try your hand in fixing this, you are welcome to propose a solution!

**Comment by migueldvb** [comment]
Thank you for explaining the issue. Reloading the current dataframe is working well. However I have found another problem that may be related with checking the columns once when the sheet information is loaded. If a view to some columns in the dataframe is provided to `vd.PandasSheet`, for example when the dataframe includes many columns that are not supposed to be displayed, later on when the shown columns are updated the changes do not take effect. The code snippet below does not work as intended.


```
@vd.asyncthread
def changedata(df):
    while True:
        df.loc[0, "col1"] = randint(0, 9)
        time.sleep(1)

d = {'col1': [1, 2], 'col2': [3, 4], 'col3': [5, 6]}
df = pd.DataFrame(data=d)

changedata(df)

vd.run(vd.PandasSheet('pandas', source=df[["col1", "col2"]]))
```

Here `df[["col1", "col2"]]` should give a view to the array as well as `df.loc[:, ["col1", "col2"]]` that does not work either.

**Comment by saulpw** [comment]
Gosh, I just don't know, @migueldvb.  It must be making a copy, because if you pass the 'view' into changedata instead, it does work (and the changes persist after `run()` return).  I have to admit, I'm not a big pandas user, so maybe someone else can chime in as to why it is not working as expected.

**Comment by azjps** [comment]
This is expected behavior from `pandas`, it rarely returns a view and usually will make a copy since it is difficult for `pandas` to know when it is permissible to return a view (especially considering `BlockManager`). More information in: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy, for example can verify with something simple like:
```python
In [1]: import pandas as pd

In [2]: df = pd.DataFrame({"a": [1, 2], "b": [3, 4]})

In [3]: df2 = df[["a", "b"]]

In [4]: df.loc[0, "a"] = 5

In [5]: df
Out[5]:
   a  b
0  5  3
1  2  4

In [6]: df2
Out[6]:
   a  b
0  1  3
1  2  4

In [7]: pd.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.2.final.0
python-bits: 64
OS: Linux
OS-release: 4.4.0-17134-Microsoft
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: C.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.24.1
numpy: 1.16.2
```

**Comment by saulpw** [comment]
Looks like this is expected behavior from pandas.  Workaround as per @anjakefala above is Ctrl+R to reload the sheet.
