### ISSUE TITLE
selected-or-all-row operations can lead to unexpected results in batch mode

### ISSUE THREAD

**Issue by cwarden** [saulpw/visidata#265]
If you have a cmdlog that selects rows then performs an operation on the selected rows, you'll get unexpected behavior when the select operation doesn't match any rows because the second operation will affect all rows.

For example, using `setcol-expr` after `select-col-regex` will update all rows if the regex doesn't match any rows.

**Comment by saulpw** [comment]
After much consideration this weekend, the `selectedRows or X` idiom has been largely converted to `selectedRows` (though not for everything--notably `show-aggregate` and the type converters on the ColumnsSheet) in order to make the output during batch mode consistent with interactive mode, for the same commands on the same input data.

Note that develop now has a breaking change for some scripts, as we renamed the following commands:

 - `edit-cells` (`ge`) to `setcol-input`
 - `fill-nulls` (`f`) to `setcol-fill`
 - `paste-cells` (`gzp`) to `setcol-clipboard`

These longnames made a lot more sense to us.  If it's a bother for you (or anyone) to change your .vd scripts, let me know, and we'll come up with a smoother deprecation plan until we release the complete API in 2.0.

**Comment by saulpw** [comment]
@cwarden Let us know if we missed anything or if this is giving you any more issues.

**Comment by cwarden** [comment]
These changes are working well for me.
