### ISSUE TITLE
Increase precision for floating point

### ISSUE THREAD

**Issue by h-g-s** [saulpw/visidata#275]
Hi, I already learn that pressing % I set a field to float, but only two decimal places are visible. How I increase the precision to see more decimal places ?  Sorry if this is included in the documentation, could not find it.

**Comment by anjakefala** [comment]
Hi! This is a good question, and could be better explained in our documentation. 

If you press `C`, that will take you to the current sheet's **ColumnsSheet**. You will there see attributes for each column.

The `fmtstr` attribute allows you to set the style display formatting for a particular column, including the displayed decimal precision for float types. Please note that this just affects display value. Whenever VisiData does calculations, they are always done on the full underlying value.

The default is set to `%.02f`. You can change this to e.g. `%.03f` to have 3 decimal places displayed. If you want to change the attribute for a bunch of columns in bulk, you can select each one you want to modify, move your cursor to the `fmtstr` column, and then press `ge` to bulk edit.

**Comment by h-g-s** [comment]
Works perfectly, thanks !

**Comment by gennaro-tedesco** [comment]
Is it possible to set such option globally in `~/.visidatarc`, and if so, what is the corresponding grammar?

**Comment by saulpw** [comment]
In current develop branch (soon to be v2.0), you can set `options.disp_float_fmt = '%.07f'` or whatever you like.

**Comment by gennaro-tedesco** [comment]
Has this been merged? I see 
```
visidata --version
saul.pw/VisiData v2.1
```
but nevertheless the option seems to have no effect whatsoever. Or am I wrong?

**Comment by anjakefala** [comment]
@gennaro-tedesco This has been merged.

Can you let me know what exactly have you tried that you see no effect for?

**Comment by gennaro-tedesco** [comment]
As per instructions I have added to the `~/.visidatarc` the option `options.disp_float_fmt = '%.07f'`. Moreover I have made sure that the columns in question are manually set to float type (by pressing %) and what I observe is that with or without such option (or such option possessing any value) the representation of the floating points is unchanged.

**Comment by anjakefala** [comment]
I am sorry @gennaro-tedesco, I cannot reproduce! =(

Things look fine for me.

One thing to test is if you go to the Column Sheet (`C`), and change the fmtstr for a typed float column, does that change things for you?

If it does, then the issue is with the loading of your `.visidatarc`.

You can further test passing in the `--disp-float-fmt="%.07f"` through the commandline.

**Comment by aborruso** [comment]
It works also for me, I have `saul.pw/VisiData v2.1`

**Comment by gennaro-tedesco** [comment]
If I

1. pass `--disp-float-fmt` via command line
2. manually % the column in question

then it does work. If instead I change the column type via the `C` sheet or use the `~/.visidatarc` then it does not. I will try a fresh install of the latest version since you are confirming that it should work.
