### ISSUE TITLE
Visidata doesn't resize when the terminal size changes

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#280]
In the code it looks like the KEY_RESIZE is a no-op.

I use visidata in a tmux pane, which will get resized. I would like for visidata to change it's own layout based on the current window size.

There doesn't seem to be a bug already filed for this issue, which seems odd.

**Comment by saulpw** [comment]
Hi @frosencrantz, KEY_RESIZE is a no-op because the window is automatically redrawn after every action, using the current size of the window.  So this should already work, and I'm surprised that you're having issues.  I use VisiData within a tmux pane all the time and have never had any issues.  Can you clarify what you're seeing, and maybe include an animated screenshot?  Also which version you're using (though that shouldn't matter, since resize behavior has been working from the beginning).

**Comment by frosencrantz** [comment]
Here is what I'm seeing. (Sorry for the long response time, it might take me some time to respond).

For long data, longer than the initial screen length:
  - Making the window longer, vd doesn't use the extra space.  Keeps initial size
  - Making the window smaller than the initial size causes the top rows of the table to be pushed off the top, so you can't see the headers.

For short data, shorter than the initial screen length we still lose rows off the top of the screen including the header line.

For narrow data (the data is narrower than the initial screen width):
  -- Make the window wider, vd doesn't use the extra space.  Keeps initial size.
  -- Make the window narrower (but still wider than the data) the status line will wrap one line, and cause the header row to scroll off the top of the screen.
 -- Make the window narrower (than even the data)  more lines lost off top, data lines now wrap overwrite next line down

After resizing the window, it usually requires running redraw (Ctrl-L) to clear issues on the screen.

It seems like visidata will never use additional space than the initial screen size.  If the screen size is restore, visidata works fine.  If the screen is made larger than the original size, visidata, is fine, but doesn't use the extra space. 


I'm seeing this with the last release from github, the last from develop head, and from version 1.0.

**Comment by saulpw** [comment]
Okay, thanks @frosencrantz.  We definitely don't see this; resizing for us is fluid and immediate with only the occasional need to Ctrl+L to remove some extra detritus on the screen.

Can you provide the following information?

- which OS and version are you using?
- which terminal program?
- which version of tmux?
- are tmux and visidata both running locally or are you ssh'ing into another computer?

If you have any other details you think might be relevant to solving this mystery, please do share them.

**Comment by frosencrantz** [comment]
I'm using python 3.6.5.  I use both ssh and not-ssh.  I can use a local xterm and still have the issue.
My system is using ncurses (6.1-20181013-2).  I'm using a Linux system based on Debian.

How would I tell visidata to show the dimensions of the screen in the status bar, on the left side.  It feels like visidata doesn't have the correct screen size.  I was able to try visidata on a completely independent Linux system, and it appears to resize properly.

**Comment by saulpw** [comment]
With develop HEAD, you can put this in your `.visidatarc`:

```options.disp_status_fmt = '{vd.windowWidth}x{vd.windowHeight} {sheet.name}| '```

**Comment by frosencrantz** [comment]
That was useful.  I have a workaround, in my .visidatarc:
```
def fix_size():
   (c,r) = os.get_terminal_size()
    curses.resizeterm(r,c)

globalCommand('zZ', 'real-resize', 'fix_size()')
```
I tried making KEY_RESIZE a globalCommand, but that didn't work.  I didn't try to figure that out yet.

**Comment by saulpw** [comment]
Hm, that is very interesting.  I wonder why your terminal is acting differently than ours.

The reason that KEY_RESIZE doesn't work as a global command, is that it's overridden on BaseSheet.  I think we're actually going to get rid of globalCommand and put them all on BaseSheet (since there should always be an active 'top' sheet anyway).  Currently KEY_RESIZE is bound to the `redraw` command which does `scr.clear()` and then `scr.refresh()`.  Try this instead of globalCommand:

```BaseSheet.addCommand('KEY_RESIZE', 'redraw-resize', 'fix_size()')```

It might be that your fix_size() function should be incorporated into BaseSheet.refresh() anyway.  I'd want to understand what's going on and why this is different, and make sure it doesn't have any negative side effects for other platforms.

Thanks for reporting this and keeping us in the loop!

**Comment by frosencrantz** [comment]
That works. 

Curses is broken in my environment, within visidata it doesn't know the correct screen size after resizing. (Why? Not sure.)  It sends  KEY_RESIZE but doesn't appear to update what it thinks the size of the screen is.   This workaround is great for me, but might not make sense to add to the code if others are not seeing this issue. 

One thing I noticed when testing this was, when actively resizing (via mouse) the window visidata was running in would cause it to briefly flash the table in the original table size,  as if it still thought that was the screen size.  It would quickly refresh with the correct size, but suggests it still has some memory of that size even with this workaround.

I won't track down the breakage, unless it has more problems.  If I learn more I'll update this issue.

Thanks for the help with the issue!

(Do expect some future feature requests...  I'm a big fan of this tool.)
