### ISSUE TITLE
strange behavior with fixed input source and empty column

### ISSUE THREAD

**Issue by aborruso** [saulpw/visidata#298]
Hi,
when I open this fixed table

    curl -sL "https://www.metoffice.gov.uk/pub/data/weather/uk/climate/datasets/Tmin/ranked/UK.txt?fbclid=IwAR26RJZPfZYJd4GJ5bn4zmAHlXkGmDj4UPxujCIgLWFW5ErgM9AWkmpG_IM" | tail -n +8 | vd -f fixed

and then run in the first empty column `gz=range(10000)`,  I have not as output a column with increasing progressive numbers. But why? What's wrong in my procedure?

Thank you

**Comment by anjakefala** [comment]
This is fun! Here is some more information with what is happening.

![Screenshot from 2019-06-16 11-55-50](https://user-images.githubusercontent.com/7489659/59566398-d1d78000-902d-11e9-8b75-68d6dfaae3b1.png)

![Screenshot from 2019-06-16 11-56-07](https://user-images.githubusercontent.com/7489659/59566400-dac85180-902d-11e9-8959-20dc7e53258f.png)

And some more information on procedures, but I think this is an issue beyond procedures:

Which version of VisiData do you have?

If you are on the ~cutting edge~, you will have to select all of the columns with `gs` first. Since the work on this issue https://github.com/saulpw/visidata/issues/265, we have transitioned the bulk of the commands to be `for selected rows` only.

**Comment by aborruso** [comment]
Hi @anjakefala I have 1.5.2.

If I run `gs` I have the same wrong output.

**Comment by anjakefala** [comment]
@aborruso, congrats, your issue has earned a bug label. =D

**Comment by anjakefala** [comment]
Eureka! I have figured out the issue.

Edit one of the cells in the `Year` column. Place a number that is longer than the value within the current cell (say type in '123456'). Only the first 4 character of the number you typed in will show up. This is because the current implementation of the FixedWidthSheet *maintains* a fixed width.

So when you are doing `range(1000)`, it is properly calculating the range, but everything after the first char is getting chopped off. 

The current workaround is to first use `g'` to create a frozen copy of the entire sheet whenever you are working with FixedWidth data that you want to modify somehow. Same values, but it does not have a fixed width source anymore. 

I am going to wait for @saulpw  to see how we want to approach this. Thanks for bringing this to the forefront. =D

**Comment by anjakefala** [comment]
Hi @aborruso! 

It seems like your best bet is to content with the workaround. =( When a FixedWidthSheet is related to a source, we need to respect the hardcoded limits set by those columns.

Having said that, we now adapted FixedWidthSheets to use deferred columns, which we had forgotten about! Thanks. <3
