### ISSUE TITLE
Add unit tests and enable continuous integration

### ISSUE THREAD

**Issue by scls19fr** [saulpw/visidata#3]
Hello,

You might add some unit tests (at least integration tests) and enable continuous integration (Travis for example).

Kind regards

**Comment by saulpw** [comment]
Thanks for the suggestion.  I'm not quite sure how I would do unit or integration tests, given that it's just a single interactive script.  Do you have any suggestions for how continuous integration might work for something like this?

**Comment by TMiguelT** [comment]
Firstly you should probably refactor your code into a bunch of separate modules. Then you'd write unit tests for each 'pure' function/method in each module that can easily be tested. Pure meaning no side effects, because the functions that draw to the screen are a bit more difficult to test.

For the integration tests and tests that cover the input/output, consider something like [`expect`](http://expect.sourceforge.net/), which is a unix tool that is designed for this exact purpose - simulating input and output for console applications. You can use autoexpect to start visidata, make some changes, and then expect should be able to replay those actions as part of a test, and then test if the results (in the form of terminal display, as well as final CSV output) are correct.

Hope that helps!

**Comment by TMiguelT** [comment]
Actually, it seems that there's a python version of expect that might be better (easier to write tests using it etc.): https://pexpect.readthedocs.io/en/stable/index.html

**Comment by saulpw** [comment]
After giving it some consideration, I don't think automated tests would be worth the overhead at this stage of development.  Maybe after 1.0 when the interface has matured and is ready to be hardened.
