### ISSUE TITLE
Set default cmdlog filename based on current filename

### ISSUE THREAD

**Issue by pigmonkey** [saulpw/visidata#312]
I frequently use visidata to load a CSV file, do something simple like set the type for each column, and then want to save those types so that visidata remembers them the next time I open the same file.

Pressing `^D`, visidata proposes that I save the cmdlog to `cmdlog-1.vd` (or another integer, if `-1` already exists). Of course I can change this to whatever I want, but I really wish visidata would propose a default name based on the name of the file that I'm viewing. For example, if I am viewing `mydata.csv` I would prefer visidata to propose `mydata.csv.vd` for the cmdlog. This would save me a lot of keystrokes when operating on a directory full of CSV files, where files with names like `cmdlog-1.vd` aren't very helpful in a directory listing.

**Comment by saulpw** [comment]
Hi @pigmonkey, I agree that the default cmdlog naming scheme is not very good.  I like the idea of your proposal, but I'm worried it might not work very well for derived sheets, whose names can get quite long and opaque; although, in trying to come up with a 'simple' example, the names all made some kind of sense for naming the cmdlog to get there, so maybe my worries are misplaced.  I think we'll change it and see how it feels.

In the meantime, you might save yourself some keystrokes after pressing `Ctrl+D`, by pressing `Ctrl+K` (kill to end of line) and then using tab-completion instead of typing out the whole filename.  Though if you have a whole directory of similarly-named .csv files this might be just as bad :)

**Comment by saulpw** [comment]
Although as I go to implement this, I realize that while the .vd file will be more aptly named, the default will always be in the current directory, and there's not an easy way around this, as the source of derived sheets is another sheet.

**Comment by pigmonkey** [comment]
So if I open a sheet in a subdirectory:

    $ cd ~/
    $ vd ~/foo/mydata.csv

And then I use `Shift+F` to get a frequency table of a column, I end up with a derived sheet with a name like `mydata_$columname_freq`.

Are you saying that the default cmdlog name would be `~/mydata_$columname_freq.vd`, rather than `~/foo/mydata_$columname_freq.vd`?

**Comment by saulpw** [comment]
Yes, exactly.  (and also not `.csv.vd` as you had suggested earlier).

**Comment by pigmonkey** [comment]
I think this is fine.

Keeping the cmdlog in the same directory as the original sheet (`~/foo`) would be preferable when the cmdlog was simply for the original sheet, but I understand that the concept of the original sheet directory doesn't necessarily apply to derived sheets. At least for my use case, I can get into the habit of `cd`ing into the directory of the sheet before opening it. Even if I fail to do that, I think this change would still be a step better than `cmdlog-1.vd`.

I have no strong preference concerning maintaining the original sheet's extension (`mydata.csv.vd` vs `mydata.vd`).

**Comment by saulpw** [comment]
Added in b428fd9c643cb8307ab87234c339a13860c59e26.  Thanks for the suggestion!
