### ISSUE TITLE
Is the column separator color only supposed to work for the header row?

### ISSUE THREAD

**Issue by mightymiff** [saulpw/visidata#321]
I would really like to see the option to change the color of the column separator for separators in the body of a table, in addition to the headers.

Current setting: `options.color_column_sep     =  '130 darkorange3'    # color of column separators`

**Comment by anjakefala** [comment]
Hi @mightymiff!

This is a bug. The layering of the colorizers is a bit complex, but I am going to tackle this.

Thanks for providing your visidatarc. =) It will help me ensure this fix works for your needs.

**Comment by mightymiff** [comment]
Thank you @anjakefala, I appreciate it.

**Comment by anjakefala** [comment]
Hi @mightymiff! I am going to reopen this one because it is a good way for me to understand how colorizing works in the code. It is tricky, so it may not end up being easily feasible, but I would like to keep this issue open for as long as I am trying. =)

**Comment by anjakefala** [comment]
Hi @mightymiff,

I had a really fun evening learning about how the coloring system works in VisiData. I am hoping to push my notes on that tomorrow. For now, here is my pushed attempted fix so that the separator colour now applies to regular rows. Thank you so much, this was a useful/fun issue. ^^

Give it a whirl!
