### ISSUE TITLE
Configuration Possibilities

### ISSUE THREAD

**Issue by mightymiff** [saulpw/visidata#324]
Getting to know VisiData this week, there were a few of things I wanted the program to do that it isn't currently doing for me that it might be able to do, so I figured I'd ask about it in here. I hope that is alright.

1. Ability to page up and down, and also possibly to be able to specify page size in number of rows in one's `.visidatarc`.  Currently possible?
2. Can keybindings be updated from within the `.visidatarc`?   The default navigational keys are all mostly alright by me, but if I wanted to bind the desired page-up/ page-down functionality to `PgUp` and `PgDn` in addition to `<C-u>` and `<C-d>`, for example, could I currently do that from within that document?
3. Is there any way to display column numbers?  If so, great--care to explain how I can do it?  If not, the ability to toggle (with they keybinding of my choice) row and, to a lesser extent, columns number would be personally desirable.
4. This one is also about key remapping, but as I mash keys learning how things work, I'd like to replace the `d` and `q` mappings with `D` and `Q`, or something like that so as to not delete rows and quit the program on accident.
5. I do not see mention of undo/redo functionality.  Does it not currently exist?

Thanks for all your hard work on this project.  It is mighty impressive.

EDIT:  I got started reading Jeremy Singer-Vine's excellent documentation so I have a better sense of some the above, though am still curious about column numbers and key remapping.  Also, VisiData is far more fully featured than I was expecting.  As I get familiar with the options, two more things came to mind, so I am adding them to my list above.

**Comment by saulpw** [comment]
Hi @mightymiff, thanks for your recent engagement, it's nice to see you start to get into VisiData.  Here are some answers:

1. In v1.5.2, the page up/down amount was the number of rows on the screen.  However, with the new ability to have multiline rows, there is no easy number that fulfills all the intuitive requirements, and it's still a blocking issue for v2.0 in my mind.  (I may revert to the 1.5.2 behavior and just accept that page up/down with multiline rows will make it so there are some rows you will never see). There isn't an option to specify the page size otherwise.

2. Yes, see http://visidata.org/docs/customize.  Basically add `bindkey(keystroke, longname)` to your .visidatarc.

3. There is no easy way to display column numbers directly.  You could go to the `C`olumns sheet, press `gs` to select all columns, then `gz=range(1,100000)` to set the column names to numbers.  For row numbers, there is the `rownum` plugin in develop (available in next version).

4. `Sheet.bindkey('d' '')` works in the develop branch to disable a binding. I think v1.5.2 might work without the `Sheet`.  You can add new bindings as above in (2).

5. The develop branch has Shift+U for undo and Shift+R for redo.  It's beta and will also be in v2.-1 (next version).

You might also want to join us on freenode #visidata.  Thanks for dropping by!

**Comment by anjakefala** [comment]
I would just like to slip in a friendly addendum to @saulpw's comment that `D` is currently mapped to `open-cmdlog` which is a pretty important command. It is a log for the command history for the current session. It can even be saved and replayed. http://visidata.org/docs/save-restore/

So, I would recommend you remap open-cmdlog to another character when you bind delete-row to `D`. :blush:

**Comment by mightymiff** [comment]
Many thanks @saulpw for taking the time to so patiently respond to my questions, even when they are explained elsewhere.  It is great to hear that most everything that I wanted is already available or in-the-works.  Thank you also for making and sharing VisiData with the world! 

Also, thanks @anjakefala.  Yes, I will do my best not to brick important functionality.

I was happy to learn that `<C-g>` works as expected, so at least it isn't hard to know exactly where I am in a long document.

I'll be sure and add #visidata once I dust off WeeChat.  Anyway, I think this is mostly all I need to know to get off and moving on my own, so I'll stop clogging up your issue board.  @anjakefala, I am not really sure of the standard procedure for closing issues.  Would you like me to close them all myself?

**Comment by anjakefala** [comment]
Since you are in thesis-hell, I think you should definitely seek some joy where you can, and be the one who gets the thrill from closing issues.

It is such a satisfying feeling.

**Comment by anjakefala** [comment]
Silliness aside, closing the issue indicates that you are either satisfied with the response to your original post or retract it as something you wish others to engage with. The only time I would discourage it is if someone already wrote that they are working on something in response to the issue. Then it is kinda pulling the rug out from under them.

**Comment by mightymiff** [comment]
@anjakefala, got it!  Closing now, though I may leave one open so as to extract extra satisfaction on some future day of my choosing to get me through the day.
