### ISSUE TITLE
Fixed format can truncate data, but not strip spaces.

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#331]
**Fixed format can truncate values, and not strip spaces**

**Expected result**
Three things seem incorrect here:
1) Non-space values are lost.
2) Some cells have leading or trailing spaces.
3) The leading column is empty.  First column should have a value.

**Actual result with screenshot**
If you get an unexpected error, please include the full stack trace that you get with `Ctrl-E`.

**Steps to reproduce with sample data and a .vd**

```
$ (echo  "WXYZaXYZbXYZc" ; echo "WXYZdWXYZeWXYZf" ; echo "WXYZgggZhhhZiiii") | sed -e "s/[A-Z]/ /g" | vd -f fixed --fixed-rows=3 -b -o r3.csv -                                                                      
$ (echo  "WXYZaXYZbXYZc" ; echo "WXYZdWXYZeWXYZf" ; echo "WXYZgggZhhhZiiii") | sed -e "s/[A-Z]/ /g" | vd -f fixed --fixed-rows=2 -b -o r2.csv -
$ grep "" * | sed -e 's/ /+/g'
r2.csv:,a,b,c,
r2.csv:+,d,+e,+,f
r2.csv:+,g,hh,i,i
r3.csv:,a,b,c
r3.csv:+,d++,+e+,++f
r3.csv:+,ggg,hhh,iiii
```

**Additional context**
Latest version

**Comment by anjakefala** [comment]
Thanks for the great reproducing in the above bug report! I do not think the leading blank column is an issue. The sed output has leading spaces, and I think vd reasonably interpreted it.

The data loss is definitely a problem. I wonder why that is happening.. I think we should at least investigate that.

**Comment by frosencrantz** [comment]
There should have been a note explaining to make it easier to see the spaces the input contains capital letters that represent spaces. Different letters make it easier to see the count.  The output has pluses that represent spaces.

Agreed, the data loss is the most serious issue.

The extra spaces in the output is also bad, since it interferes with using other commands in Visidata, for example you can't fill null values, since there are no null values, values contain spaces.

The leading spaces are just left-hand filler of the first data column.  In this case fixed is generating an empty first column.  The fixed format does not create a spaces-only column before any other column than the first. (?)

**Comment by saulpw** [comment]
I agree that data loss is the most egregious of the issues here.  It turns out that guaranteeing no data loss means that the other issues must continue to persist, by design.

Basically, the columns were smallest fit; `columnize()` assumed that if a certain column was always a space in the first `options.fixed_rows`, that it would always be a space in all the rows.  If there turned out to be a non-space character in that column later on, it would fall through the cracks between the columns.

So now, columnize makes columns that are maximum fit; combined they cover the entire width of the input, so no data should ever be lost, even if there are no spaces between fields on subsequent rows.  However, this does mean that the leading spaces column will persist (after all, there could be values there after `fixed_rows`), and it makes item 2 a bit worse, as virtually all cells will have trailing spaces now.

To solve the issue of extra spaces, you could make a type `stripstr` that strip()s the spaces (put this in your .visidatarc):

```
stripstr = lambda v: str(v).strip()
vdtype(stripstr, '-')  # associate column type indicator in header
Sheet.addCommand('gz~', 'type-stripstr', 'for c in visibleCols: c.type = stripstr')
```

Then this `type-stripstr` command will set all cols to the stripstr type, which will show them without spaces.  Since the check for null must use the value before it is typed, you'd have to then `freeze-sheet` (and the frozen sheet copies typed values, for just this reason), and then `fill` should work (assuming you have `options.null_value = ''` also).

**Comment by frosencrantz** [comment]
Thanks for fixing this.  I haven't fully tried it out yet. 

I understand that breaking lines by maximum fit would cause extra spaces surrounding data when they are pulled from the input.  But why not run .strip() on the data when saving it to a cell?

If that is not possible, it seems like your suggestion for .visidatarc might work.  Is there a way to configure Visidata  to perform those extra steps automatically either when loading the data or after all the data has been loaded?

**Comment by saulpw** [comment]
Mostly performance reasons, though the spaces might have meaning in some context also.  It's foundational to VisiData that data isn't 'saved' into cells when loaded; instead, whenever a cell value is needed, the column is called upon to interpret the row and produce the cells.  So, types are the best way to do the kind of post-processing you want currently. (I have an idea to expand the column type into a more generic transformation pipeline, but that is a ways off).

As for doing things on load...do you know how to save and replay .vd scripts?

**Comment by frosencrantz** [comment]
Is there a way to conditionally replay .vd scripts? Like is it possible to add something to visidatarc and have it replay when I load a fixed data file?  Vim has a way to [trigger](http://vimdoc.sourceforge.net/htmldoc/autocmd.html#autocmd-events) automation based  all sorts of events. Such as a loading a filename with a particular pattern.

My thoughts on vd scripts...   I've learned to avoid vd scripts when possible.
- there is no commitment to keep vd scripts stable, working
    - granted I'm running from develop head, but we are past 1.0
    - this is not on the roadmap, so not even a possible promise
- I've needed to debug previously working ones.
- I've needed to add delays for ones that previously didn't
- It's hard to edit, even in visidata.

This has left me feeling like scripting language by csv file is not right.
Still a big fan of Visidata, but not this aspect.

I dream about more declarative ways for fixing, formatting visidata tables, or [configuring Visidata options](https://github.com/saulpw/visidata/issues/322#issuecomment-514900676).

For fixing data I'll use other tools (perl, sed, awk, mlr, sql, pandas)  to first massage data into a format I want before I put it into Visidata.  And part of this is just avoid having to retype the same keystrokes over an over.
