### ISSUE TITLE
VisiData version 2.0 installation

### ISSUE THREAD

**Issue by aborruso** [saulpw/visidata#335]
Hi,
is it necessary/better to uninstall the 1.5.2 and remove `.visidatarc` file?

Thank you

**Comment by anjakefala** [comment]
You can have two different config files (say ~/.visidatarc and ~/.testrc), and then pass the config option every time you want to reference the second one.

E.g. `vd --config=~/.testrc`

You can have them both installed if you are employing virtual environments, which I think you had figured out? Otherwise, replacing one with the other may be easiest.
