### ISSUE TITLE
[develop] Saving DirSheets doesn't delete files

### ISSUE THREAD

**Issue by Mikee-3000** [saulpw/visidata#340]
**Small description**
Opened a directory in Visidata, deleted a file and saved.

**Expected result**
File deleted from the file system

**Actual result with screenshot**
No result, no error. 
![dirsheet](https://user-images.githubusercontent.com/13318998/63549161-c752ce80-c527-11e9-95d1-5268f50a98bd.gif)

**Steps to reproduce with sample data and a .vd**
In a terminal, open vd with `vd` (no args). Delete the file with `d`. Save with Ctrl+S

Cmdlog:
```
sheet	col	row	longname	input	keystrokes	comment
			open-file	.	o	
		キ.,test.md	delete-row		d	
			save-sheet		^S	
```

**Additional context**
VD: 2.-1dev, OS: Linux

**Comment by frosencrantz** [comment]
OT: What are you using for your screenshots @Mikee-3000?

**Comment by Mikee-3000** [comment]
[Peek](https://github.com/phw/peek) for the recording
[Screenkey](https://www.thregr.org/~wavexx/software/screenkey/) for the key display
Unfortunately Peek crashes when I try to save to gif, so I save it as mp4 and use `ffmpeg -i infile.mp4 outfile.gif` to convert it.

**Comment by saulpw** [comment]
Hi @Mikee-3000, thanks for reporting this bug, which points to some deeper problems with interactions between the DirSheet and deferred modifications on other sheets.  I think it may not be possible to have it work well both ways: the DirSheet (and other deferred modification sheets) want deleted rows to stick around (but colored/marked deleted) until the changes are committed. But data sheets want deleted rows to disappear straightaway.  So either we remove the deferred modification functionality from most sheets, like it was pre-2.0, and/or we move the DirSheet editing functionality out into its own tool (`vls`, maybe?).  I think this might make more sense ultimately, since data sheets and filesystem editing are kind of two radically different use cases, even though you want to use many of the same data management features for both.

**Comment by anjakefala** [comment]
This is now fixed on the develop branch. We are experimenting with moving the Write-mode of the DirSheet into its own tool [vls](https://github.com/saulpw/visidata/blob/develop/bin/vls). 

It does not have its own setup.py yet. To play with it, install the latest [of VisiData v2.x](http://visidata.org/v2.x/) (it is a dependency), then take the vls script and place it in a `bin` that is findable by `PATH`. 

Then type `vls` and it should be the DirSheet that we know and love.

We are still considering how this will play out, so if anyone has any thoughts please share them! I will open up a new issue for Discussion.
