### ISSUE TITLE
Feedback: When will visidata-2 be available?

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#345]
The visidata.org site is asking for beta tester feedback.  It would be helpful if there was an estimate listed of when 2.0 will be available, so feedback can be provided in time.

There are now nine open bugs that are in 2.0?  Will some of those be fixed?  And will there be more time to test?

**Comment by saulpw** [comment]
Good idea, @frosencrantz, we'll add that soon.  For you and others who may read this issue, our goal is to get a proper 2.0 out by the end of the year (~4 months).  There will be other 2.-x pseudo-releases before then, as the next version gets (hopefully) increasingly stable.  We're taking our time with this one, so that we can have a stable 2.0 API defined and on its way to being documented.  We want to make sure plugin and app authors can write and release their extensions with confidence that they will continue to work with future versions.

**Comment by frosencrantz** [comment]
@saulpw and @anjakefala 

What are the current plans for the next release?

Also, what are the plans to promote the new release?  I hope the new release helps increase interest and usage of Visidata.

Jeremy Singer-Vine's tutorial is quite helpful.  It helped me learn how to use Visidata.  Is Jeremy's tutorial still correct with the new version?  I've recently re-read it, and it seems to still work.  There were a couple minor things that seemed out-of-date, things like installation instructions and help output that were aged.

**Comment by jsvine** [comment]
Hi @frosencrantz, and thanks for the kind words! I plan on updating the tutorial once 2.x is the main public-facing version. If you notice particular things that tripped you up in the transition from 1.5.2 to 2.x, I'd be very interested to hear about it, so I can account for those things in the update. Feel free to drop an issue at  https://github.com/jsvine/intro-to-visidata or [contact me 
directly](https://www.jsvine.com/).

**Comment by frosencrantz** [comment]
@saulpw / @anjakefala   what are the next steps for doing a visidata2 release?  I believe having a new version available in packaged form would help increase people using visidata.   Also, a new release is something that could be used to help promote visidata.  There are a **lot** of great new features people would enjoy.

It looks like the defermods changes are now in.  There are still some open issues, but not all of them need to be fixed before release.  I'm wondering what is the simplest path to doing a new release.  I'm not saying release today, but asking what needs to be done before release, and what could wait.
