### ISSUE TITLE
Reviewing the design of --skip for 2.0

### ISSUE THREAD

**Issue by suhrig** [saulpw/visidata#347]
Hi Saul,

I am not sure if I understand the meaning of the `--skip` option. When I create a text-file with this content:

```
col1	col2
1	1
2	2
3	3
4	4
```
Then `vd` always shows the same table, regardless of the argument given to `--skip`. I would have expected it to not display the first two lines when set to `2` for example. Is this what should happen or am I mistaken?

On a related note: I work in bioinformatics and it is very common for files to have an arbitrary number of comment lines (prefixed with `#` or `##`) at the start of the file before the actual data, which is mostly tab-separated. Is there a way to tell `vd` to auto-detect and skip comment lines at the beginning of a file? Sometimes the column headers are on the last comment line before the actual content starts, sometimes the column headers are on the first line of the content. What would you recommend is the best way to load such files into `vd`? Does this require implementing a new loader? Can this be done with a plugin?

Here are two fictional examples of what such files look like:

```
# a comment line
# another comment line
col1	col2
1	1
2	2
3	3
4	4
```

```
##a comment line
##another comment line
#col1	col2
1	1
2	2
3	3
4	4
```

Thanks,
Sebastian

**Comment by saulpw** [comment]
Hi @suhrig, the `skip` option should work as you describe, but it's tricky to support uniformly across many different loaders transparently. It looks like it's broken now since a performance enhancement for the tsv loader.  This is definitely a bug I want to address and hopefully in a more generic way that doesn't impact performance.

For your second question, there isn't a way to ignore lines based on comments yet.  That seems like a good feature to have, although I have to say, this makes things very complicated:

> Sometimes the column headers are on the last comment line before the actual content starts, sometimes the column headers are on the first line of the content.

What file formats have you seen that include comments?  Any besides txt/tsv?

We could consider adding an option like `comment_prefix` that ignores lines that start with that character (if set; by default it would be unset).  Would this only ignore comment lines at the start of the file, or throughout it as well?  And that still wouldn't properly deal with column names on that last comment, although your second example is accurate, you could set the comment_prefix to `##` and just accept that the first colname would be `#col1`.

**Comment by suhrig** [comment]
> This is definitely a bug I want to address

Thanks, good to know I can stop trying to get this to work. I'll wait for the fix then.

> What file formats have you seen that include comments? Any besides txt/tsv?

They are all TSV files essentially, though they may have different file endings, e.g. `.gtf`, `.gff`, `.vcf`

Here is the VCF file format as an example:
https://samtools.github.io/hts-specs/VCFv4.2.pdf

> Would this only ignore comment lines at the start of the file, or throughout it as well?

They are all at the beginning (=file header).

> although your second example is accurate, you could set the comment_prefix to ## and just accept that the first colname would be #col1

Yes, that would be fine.

However, there are even more complicated cases where the header files are not even prefixed with a `#`. GFF files, for instance, can have multiple `track` and `browser` lines at the beginning of the file, see https://genome.ucsc.edu/FAQ/FAQformat.html#format3. I understand that from a parser point of view these file formats are a complete nightmare, but unfortunately many file formats are like this in bioinformatics. Here is how I use to deal with such files and I would like to hear your opinion whether such an approach would be possible in visidata, too: Could one implement a "smart" header detection that looks for the first line containing a column delimiter symbol (tab) and use this line as the column headers and ignore all preceding lines? This would work regardless of the comment line prefix (`#` vs. `##`) and would also ignore "malformatted" metadata lines (`browser` or `track`). I can understand if you don't want to implement such an approach in visidata for the general public, because you believe it's too "hacky" or too much of a niche use case. In this case, I would be willing to invest some time to implement a loader or plugin myself. I would just need some hints what would be the best way (loader vs. plugin vs. other approaches I am not even aware of) and possibly a pointer to a piece of code that solves a (remotely) related problem and that I can adapt/use as a starting point.

Many thanks in advance,
Sebastian

**Comment by saulpw** [comment]
I updated the viewtsv example (see above commit), and went ahead and implemented your smart header detection, which is really quite elegant.  I wonder if we even need `skip` with it?  For now you can use it as a plugin and see how well it works for you.

**Comment by suhrig** [comment]
Awesome! Exactly what I needed. I have been playing around with it for a while noticed some minor issues when using it stand-alone (no automatic decompression, no piping). I think I can fix them on my own. Using it as a plugin already solves some issues. I will need some more time to test in under real-life conditions.

> I wonder if we even need skip with it?

I do believe that `skip` exists in its own right. And since it is already implemented, it does not hurt to keep it. There might be situations where people want to skip a fixed number of lines, e.g., the autodetection fails in situations where there are comment lines in the beginning of the file and those comment lines happen to include the delimiter (think of a CSV file with a comment line in the beginning that also has a comma).

I also believe that having the possibility to filter lines by comment prefix is helpful regardless of the autodetection. It would be best, if the option accepted a regular expression (if you don't think that this makes it to user-unfriendly). With a regex, you could also filter the `track` and `browser` lines found in BED files, for example. BTW, even though the comment lines of the file formats I talk about are exclusively at the beginning, I think it would be better to remove them throughout the whole file, i.e., if a line somewhere in the middle of the file starts with `#` (or whatever comment prefix is configured), it should be removed.

**Comment by saulpw** [comment]
> BTW, even though the comment lines of the file formats I talk about are exclusively at the beginning, I think it would be better to remove them throughout the whole file

Anything we have to check for every line of a file will be a performance degradation, and I don't want to make performance worse for 99% of cases (and it might be 100% since we have never seen a file like this).

As for `--skip`, it's apparently only partially implemented, and buggy at that, so I was hoping for an opportunity to ditch it completely before we commit to it for 2.0.  But you're probably right, that it will cover other cases and will still be useful.  Right now I'm thinking that it maybe should only be for csv/tsv/fixed, and not for all text files.  Or, maybe it should mean 'rows' that should be removed from the top (before setting colnames, where that's relevant), but then that would mean a redesign of how loaders must be structured, to always incorporate that option.

**Comment by anjakefala** [comment]
The `--skip` parameter is not exclusively applied to TsvSheets, anymore.  =) 

It has been moved to the stock `reload()` in `Sheet` https://github.com/saulpw/visidata/blob/develop/visidata/sheets.py#L261. It will skip through the first *n* rows yielded by `iterload()`. 

If a loader does end up overwriting `reload()`, it should define `--skip` behaviour, if appropriate.

**Comment by saulpw** [comment]
(but most loaders should override `iterload()` instead)
