### ISSUE TITLE
Idea/question - continuously load new rows? Like tail -f but with the histogram view

### ISSUE THREAD

**Issue by samLozier** [saulpw/visidata#366]
If there is a better place to post this, I'm happy to move it. I'm new to Visidata this week having first heard about it on podcast.__init__ but am already finding it really useful for quick exploration of a file. I particularly like the histogram view and have been using it to explore log files, which prompted this idea. 

When opening the histogram view for a given column, I can 'watch' the calculation/sorting happening. It made me wonder if vd can be used like 'tail -f' to dynamically load new rows and summarize the data as it comes in? It would make a great little dashboard for troubleshooting small programs. In my case I have a scraper that's pumping out tons of data, but I'm really only interested in a histogram of the response type for the last 1000 rows so I can see if i'm getting an unexpected number of 404's. 

My apologies if this already exists. I didn't see it mentioned in the docs, could have missed it. 

Thanks for the great tool!

**Comment by saulpw** [comment]
Hi @samthaman, thanks for the suggestion.  It doesn't exist yet, and it would be pretty straightforward to with text formats.  (Other formats may need to have their individual loaders and Python modules rewritten.) 

- `visidata.path.RepeatFileIter` could be changed to block until further input if `options.follow` is set.  And since all text loaders are already asyncthread (or should be), then that would get you the first order effect like `tail -f`.

- then it would be a separate change to the frequency table to have new rows on the source sheet automatically placed in bins.  The frequency/pivot table reload() could override the source addRow() if `options.follow` is set.

I think this would make `vd --follow` work as you'd want.  It's a neat idea, you want to try your hand at it?

**Comment by samLozier** [comment]
@saulpw Thanks for the encouragement. It might be beyond my current skills, but I'll take a look and see if I can move it forward at all. At the very least it's good to hear that you think it'd be reasonably straightforward to implement.

**Comment by saulpw** [comment]
This actually already works:

    tail -f filename.log | vd

The loader runs in perpetuity, so when additional lines are added to filename.log, they show up in the source sheet.

The frequency table would work as you request, if the source sheet weren't already loaded.  To have the source sheet continue loading, and seamlessly handoff from iterating over the existing rows and to the new rows, seems do-able but outside my grasp at the moment.  I'll add it to the "someday" roadmap and maybe an idea will strike on how to implement it.

**Comment by unhammer** [comment]
I noticed the wishlist about `--follow` on the freqsheet, but why tie it to the freqsheet? I would've expected something like this to run the commands in shiftF.vd and then on more data just re-run the commands "from the top":

`tail -f loglog.log | vd --header 0 --play shiftF.vd`  
(but when I try that in 1.5.2-1 on Ubuntu at least it doesn't actually run the commands in shiftF.vd)
