### ISSUE TITLE
Feature request: go back

### ISSUE THREAD

**Issue by sfranky** [saulpw/visidata#380]
It would be great if I could go back to the same cell/column/row via a binding. It's super helpful when having to edit specific interdependent columns, and possibly copy paste information from one to the other. I know I can already go to specific column numbers, and hence switch between e.g. 3 and 5, but going *back* would allow me to quickly switch between the two with the same keystroke.

edit: one could argue that in the described case one would need to go back and *forward*, so again two key bindings. Granted, but the point is, it would be great if I didn't have to remember the column numbers. Imagine a scenario where I have two sheets open, where these two columns are in different positions.

**Comment by saulpw** [comment]
Hi @sfranky, this is a good suggestion, I've wanted something like this too. Maybe something like vim's `Ctrl+I`/`Ctrl+O`.  But the design space for this is pretty huge, and it's not obvious what method would be the most intuitive or straightforward or elegant to use.

Maybe you could experiment with some possibilities and see if you can come up with something workable that's not too complicated?  Like maybe `m` to add the current sheet/row as a marked location, and then `\`` to cycle through the marked locations.  I could offer up some other options but it's difficult to design something like this without knowing how you would actually want to use it.

For now, I'm closing this issue without prejudice, since we decided recently to limit our open issues to bugs and small concrete feature requests as we get closer to releasing v2.0.  If this feature means a lot to you, the reward for the 'True Believer' level on my Patreon is meant to satisfy just this kind of request.  You could bump to that level for a month, and we would talk about your exact use cases and work together to create a small plugin that does what you need.

**Comment by sfranky** [comment]
Ok i'll try to propose a way this could work, in the future. It's not a big deal, and the things coming up for the v2.0 release are certainly much more exciting! I have to tell you, I was ecstatic when I first used v2.-1, the deferred changes and the undo/redo are a game changer !! Thanks again for this great piece of software !!
