### ISSUE TITLE
Is it possible to write to a specific column when another column has been edited?

### ISSUE THREAD

**Issue by sfranky** [saulpw/visidata#382]
Upon filling in some cells in a specific column, I would like for the respective cells on _another_ column to be filled with a specific value. Is this currently possible through a command or a python function?

Thanks!

**Comment by anjakefala** [comment]
Hey @sfranky, can you expand on this with a concrete example?

Is it you want to attach a formula to a column, which is dependent on another column?

Example: Column `Total` to be computed from Column `Unit` * Column `Price`?

**Comment by sfranky** [comment]
Hi! I'd like to write to a column other than the one I'm executing the command on. So, for example, I'm on column C, I make an edit on a row or selection of rows, and I want column A to have its respective rows written with something (either automatically [ideally], or with a keybinding). e.g. if column A's name was "Changed", the value would now change to "True"

[edit: made last sentence less confusing]

**Comment by anjakefala** [comment]
Ah! Essentially, for column A to track changes in Column C.
VisiData currently has `expr-col`. This modifies a column based on a formula which may reference the *current calculated values* in other columns. That is not quite what you are looking for, if I understand correctly. You would like a column's modification *history* to trigger the changes.

What you want is doable, but it all involves some coding. The plugin https://github.com/saulpw/visidata/blob/develop/plugins/defermods.py (which is on `develop` not `v1.5.2` yet), colours cells when they are modified. If I was trying to build this, I would reference that code and https://github.com/saulpw/visidata/blob/develop/visidata/expr.py.

For now, I am going to close this issue because we are limiting our open issues to bugs and smaller feature requests. If you want to talk through working on the plugin, I welcome you to join us in #visidata on https://freenode.net/. =)
