### ISSUE TITLE
[defermods] Plugin savings automatically to provided source, without prompt

### ISSUE THREAD

**Issue by anjakefala** [saulpw/visidata#384]
**Small description**
When defermods.py is installed, and `^S` is pressed, VisiData will automatically save to the given source sheet without prompting with a file-input.

**Expected result**
VisiData should provides the file-input prompt for sheets that are not always saveToSource.

**Steps to reproduce with sample data and a .vd**
Install and load the defermods.py plugin. Change one cell (note that the source data is going to be overwritten). Press `^S`. It will save automatically to source. If confirm_overwrite is set to True, it will prompt if you want to save the change, but not prompt for which file you want to save to. 

**Additional context**
Current `develop` branch

**Comment by anjakefala** [comment]
@sfranky, this should fix the above bug. Defermods and trackmods' logic is in the same file, and I inevitably confused the two.

For now, I think it is ready for you to play with!

**Comment by sfranky** [comment]
many thanks for your help Anja!
Maybe I don't exactly understand how it works, but I think there is a
problem.
Is the following the expected behaviour?

I select a few rows, I press " , I edit a column with some values. I see
they are marked as changed.
If I go back to the original sheet, they are not updated, as they do
without the plugin.
If, on the other hand, while on the subsheet, I press save, [I'm asked to
write a name] and then cancel with ESC, then the changes are updated in the
original.
Are there any other actions I should be taking that I'm not?

[edit:removed the above quote]
[edit2: to make a point a bit more clear, i would have expected that both the edits and the marks remain after leaving the subsheet, without saving. This would be consistent with the standard behaviour.  But maybe I should put this as a different issue?]

**Comment by anjakefala** [comment]
@sfranky That is not fixed yet! We have another issue for that: https://github.com/saulpw/visidata/issues/383

**Comment by sfranky** [comment]
I actually forgot I had committed this issue in the past, sorry about that !!
