### ISSUE TITLE
new "visidata" tag on Stack Overflow

### ISSUE THREAD

**Issue by aborruso** [saulpw/visidata#400]
Hi,
I finally got over 1500 points in stack overflow, and I'm allowed to create new tags.

Now we have "visidata":

- https://stackoverflow.com/questions/tagged/visidata
- https://stackoverflow.com/tags/visidata/info

@saulpw  @anjakefala I do not know if you have any idea about it. In example you could write a note on the website: "to have some help on using visidata, you could use stackoverflow and "visidata" tag; to open a bug issue, to propose a feature request, to ask questions about visidata development, please use the official repo issues page".

It's only a proposal. If you prefer to have only "one place", the official repo, I understand you.

In any case, I think it can be useful to have the tag in stack overflow, because I think it should become even more used and known, more and more popular.

Thank you

**Comment by saulpw** [comment]
That's great, @aborruso, thank you!  I hope you didn't have to pay too high a price for it :)

I don't check StackOverflow very often, but if you and people on SO are willing to answer questions about VisiData that's really awesome.

I'll leave this issue open as a trial way to direct people to StackOverflow for "how-to" kinds of questions. If questions and answers start to proliferate there then it would probably become a great repository of tips and tricks pretty quickly.

For anyone who is stopping by, here are our current communication channels:

- Github Issues for bugs (not feature requests)
- IRC (freenode #visidata) currently for chat and interesting questions
- Twitter @VisiData for shameless promotion and silliness

We need a place to direct Feature Requests so that people can discuss them and flesh them out. The right design is basically trivial to implement, but requires a lot of effort in terms of designing, testing, documentation, packaging, etc.  If that all happened by community effort, I'm sure there would be a lot more plugins and features to enjoy :hammer_and_wrench:
