### ISSUE TITLE
[wishlist] Problem opening xlsx files exported by SQL Developer

### ISSUE THREAD

**Issue by tkossak** [saulpw/visidata#404]
**Small description**
Problem opening xlsx files exported by Oracle SQL Developer 19.2.1.247. When I run `vd test_sqldev_19.2.xlsx` i get:

![image](https://user-images.githubusercontent.com/3728245/69325962-4bae0e00-0c4b-11ea-9c8c-30696b96c8c7.png)

(only 1 column and 0 rows loaded)

**Expected result**
It's enough to open this file in Libre Calc, save it (without any changes) and now it works (2 columns, 4 rows loaded):

![image](https://user-images.githubusercontent.com/3728245/69326190-ae9fa500-0c4b-11ea-93cc-7797617a2515.png)

**Steps to reproduce with sample data and a .vd**
Download sample xlsx file, exported using sql developer: [test_sqldev_19.2.xlsx](https://github.com/saulpw/visidata/files/3874032/test_sqldev_19.2.xlsx)

Run `vd test_sqldev_19.2.xlsx` and observe the error (and that it loaded only 1 column, 0 rows).
Command log: [cmdlog-1.vd.log](https://github.com/saulpw/visidata/files/3874034/cmdlog-1.vd.log)

VisiData version: saul.pw/VisiData v1.5.2
os: Linux Mint x64

**Comment by anjakefala** [comment]
Hi @tkossak!

I had an interesting finding. When I treated the file you posted as an **xls** filetype (`vd test_sqldev_19.2.xlsx -f xls`), it successfully opened.

Does `-f xls` successfully load other xlsx files that you have exported?

**Comment by tkossak** [comment]
Yes, when I added `-f xls` it successfully opened other files exported by SQL Developer. I also noticed it's not only SQL Developer that generates such files, but also some of our web apps  export to xlsx in such a way, that vd only opens it when I pass `-f xls`. Maybe it's a bug in these applications, but maybe we can add backup opening method for vd: if xlsx fails, then it can automatically try xls, what do you think?

**Comment by anjakefala** [comment]
Hi @tkossak!

That is a reasonable behaviour request. There is a current wishlist item for "file sniffing" from another user that I think this could also apply to. 

I will mark this as "wishlisted", and close this issue (since there is currently an existing workaround).

There is a way to amp the priority on wishlist items! If you would like to prioritise this feature, Saul has a category ("True Believer") on his patreon just for that sort of thing. =) https://www.patreon.com/saulpw/.
