### ISSUE TITLE
[develop] Install plugin dependencies in an accessible location

### ISSUE THREAD

**Issue by tsibley** [saulpw/visidata#448]
**Small description**
I tried to install the vds3 plugin via the Plugins Sheet by pressing `a`.

**Expected result**
Plugin is installed successfully.

**Actual result with screenshot**
![image](https://user-images.githubusercontent.com/79913/72830885-8bd34200-3c36-11ea-8542-4ff8fa05a11c.png)

Note permission denied error at the bottom. Pressing `^E`, `g^E`, and `z^E` all said there were no errors, so plugin install errors may not be flowing into the error sheets.

**Steps to reproduce with sample data and a .vd**
Open Plugins Sheet.
Press `a` while the vds3 row is focused.

https://tsibley.net/paste/2020-01-21cYAYoPL1-plugin_store.vd

**Additional context**
Version is `saul.pw/VisiData v2.-3dev`, installed a moment ago from `develop` with `pip3 install --user --upgrade .`.

I believe the issue here is that VisiData is trying to install the plugin's declared `pydeps` (just `s3fs`) into the system Python library path. On my Ubuntu system, my normal user does not have write permission to `/usr/local`. My understanding is that on macOS, often the normal user _does_ have that permission. VisiData itself is installed into my Python user lib (`~/.local/lib/`).

One possible solution is to detect where VisiData is installed and install plugin deps into the same place. [Here's an example](https://github.com/nextstrain/cli/blob/ad5602346723f58d72f1410a42d6dff3e33b5d4c/nextstrain/cli/util.py#L55-L57) of detecting if a Python module is installed into the user site or not (that I wrote for another project).

Another possible solution is to always install plugin deps into `~/.visidata/` (that is, outside the normal Python lib paths) and then make sure VisiData adds the custom lib path to `sys.paths` before plugin load during startup. The benefit of this solution is that plugin deps are isolated from the rest of the Python install.

**Comment by anjakefala** [comment]
@tsibley, this is such a wonderful overview of the bug, the complexities of how it came about, and some possible approaches to resolving it.

Thank you :blush: :tada:

**Comment by saulpw** [comment]
I like the idea of installing the deps into the .visidata dir, especially because it's configurable.

**Comment by ajkerrigan** [comment]
Thanks for this report @tsibley - it covers a case some of us have hit or resolved in a few different ways. Thanks for putting this together! 👍 

In the meantime, handling the dependency install manually (a `--user` install of `s3fs` from outside of the VisiData plugin tool) feels a bit tedious but should work. Another option is creating a managed, isolated VisiData environment with a tool like [pipx](https://github.com/pipxproject/pipx) where the dependency installs would work out of the box.

> I like the idea of installing the deps into the .visidata dir, especially because it's configurable.

I like this idea too, though one wrinkle is that if we have multiple VisiData installations (some combination of stable, 2.x, development...) it could cause clashes if plugin deps get installed to a central location.

A hybrid option is possible - instead of installing deps to say `~/.visidata` they go to `~/.visidata/<slug>` where `<slug>` is unique per VisiData install. That could be tricky to manage, but it seems like there are tradeoffs involved with any approach to this problem.

**Comment by saulpw** [comment]
We can use `--visidata-dir`, so let's not use a `<slug>`.  Would it be more palatable if a `VISIDATA_DIR` envvar could be set?  maybe `VD_CONFIG` too?

**Comment by saulpw** [comment]
@tsibley Let me know if this commit ee76691 provides what you wanted.  We can also still add VD_CONFIG etc if they would help.

**Comment by saulpw** [comment]
sorry, wrong issue.

**Comment by anjakefala** [comment]
Hi @tsibley!

We would love to know if this works for you. Here is the information.

1. There have been two environment variables added. `VD_CONFIG` and `VD_DIR`. This can be used to alter the default location of the config and dir (`~/.visidatarc` and `~/.visidata`, respectively).
2. Plugin deps are now installed to `VD_DIR/plugin-deps`.
