### ISSUE TITLE
[wishlist] Allow rows and columns to span over duplicate values (or empty values)

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#537]
Provide a switch to allow cells to span multiple columns when the value in neighboring cells have the same value.  This can be helpful when a cell's width is too narrow to show the value this is duplicated over multiple columns.  It can also helpful to see when a value changes.

Some additional options would be to allow value to span over to neighboring cell if the cells to the right are empty.  This is common in spreadsheets.

Likewise it would be useful to be able to do this when the cells in a column have repeated values.

Assuming this would be post vd2 feature if added.

**Comment by anjakefala** [comment]
Sorry, @frosencrantz, I know you really want to optimise the terminal real-estate, but I doubt something like this will ever get implemented in vdcore...

This feels like a VIsiData anti-thesis to me. I welcome @saulpw to correct me. But from my impression, there are too many intersecting parts that assume the tabular structure visually. (e.g. type notes).

**Comment by frosencrantz** [comment]
Using that example, why do type notes make this a difficult thing to do?

**Comment by anjakefala** [comment]
@frosencrantz Please, accept my nos. 

It takes a toll to have "no"s consistently challenged or confronted. Especially, during this time.

****

What happens visually if one column is typed, and the other is not? The question is rhetorical.

 It is an example of all of the little decisions similar to that one, that we would have to make, write code for, and test in order to implement something like this. 

There are things for which we would bite the bullet, and make all of those little decisions for, but I do not think this will be one of them.
