### ISSUE TITLE
[wishlist] row tagging

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#540]
Have there been any thoughts on tagging rows?

I'd love to see it utilize the number keys with 't/s/u' etc.
So for example 's1' would apply tag 1 to a row, and 't2' would toggle tag 2 on the row.

Other suggestions:
- tags have an associated row colorizer
- custom tag values
- rows can have multiple tags
- tags have priorities (helps with above)
- rows with tag X can be selected, copied to a new sheet, etc.
- showing the tags would be optional if a colorizer is used

If this is realised, it would probably be beneficial for tags applied on copied/sub sheets to be applied to the original, like frequency sheet does

**Comment by saulpw** [comment]
That's an interesting idea, @geekscrapy .  I was thinking the other night about "marking" locations (like vim with `m`), so that you could easily jump the cursor to the sheet/row/col/cell).  If it's designed properly, I think most of the ideas you had could be implemented within that framework too (though I don't understand "tag priorities" that you mentioned).  Some of these would make it pretty powerful indeed.

Probably this should start off as a plugin, and it wouldn't be too hard to make.  As always the bigger challenge is documenting and promoting new features like this; I'd be willing to put some work into this one if you're willing to write the documentation page and blog post announcement to get people excited for it.

Closed for now as per wishlist policy.

**Comment by geekscrapy** [comment]
@saulpw not sure about the vim functionality (I'm a nano user for my sins) but from what I've just read it looks something like I'm thinking!

Priorities: if the tags are user defined, and colour assigned, what happens when a user applies more than one tag to the row? The tags would need to be prioritized so that the highest priority tag color is shown.

A couple of other things that I thought of to track that might be interesting:
- it might be good to expose the tags to = as well
- select by tag
- have a sheet which shows all tagged rows (this might be odd if sheets have different columns) (but would be awesome), or maybe a sheet per tag

I just chucked these in for consideration, a sub wishlist 🤪

Also, I'd be up for a bit of documenting 👍

For background, my use case is this:

I have several sheets which contain logs (windows event logs, Apache etc.) and I'd like to be able to tag certain rows that look suspicious (so I'd have a "suspicious" tag), but then as I get more confident with the activity I'm seeing I'd want to start tagging with the "bad" tag. I'd then go back to the suspicious tagged rows and upgrade them to "bad" or maybe even "good" if I've figured out they are ok.  So, eventually I'll have a bunch of rows tagged in each sheet, so ideally I'd like to see all those rows in one sheet with all their respective columns (obviously, there are ways currently, but I'm _wishing_ 😅) (that actually made me think of a new type of sheet....see #544 !).
In terms of the tags themselves I'd be able to define them in .vdrc like so:

```class tags(Enum):
    BAD: (1, "red")
    SUSPICIOUS: (2, "orange")
    GOOD: (2, "green")
    INTERESTING: (3, "bold")
```
So the name is displayed, and the tuple represents (priority, colorizer_format). This could easily be a dict.

That's it for now
