### ISSUE TITLE
Pressing F1 on Mac OS raises "random population size:" prompt

### ISSUE THREAD

**Issue by jsvine** [saulpw/visidata#55]
I'm using VisiData `0.61` on Mac OS Sierra. When I take the following steps...

1. Run `vd mydataset.csv`
2. Press `F1`

... I get the sheet options page, but I'm also prompted for "random population size:"

![screen shot 2017-06-22 at 11 11 55 am](https://user-images.githubusercontent.com/534702/27441522-c87548f8-573b-11e7-8340-9eeae765abb8.png)

**Comment by saulpw** [comment]
I don't have a MacOS system so I am not able to reproduce this.  If you can figure out what the root cause is, we can try to fix it for you.  In the meantime, `z?` is a workaround that I added because F-keys can be weird on other systems.  In fact I'm thinking about removing the F1 key for help entirely for this reason.

**Comment by jsvine** [comment]
Thanks! `z?` does the trick.
