### ISSUE TITLE
[wishlist] Save session state exactly

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#551]
The idea is that vd can be quit and reopened with all settings, rows, sheets etc. as they were before closing.

This would have been useful a couple of times recently when I had to reboot or pass share analysis with a colleague. I ended up saving the interesting rows out as CSV, but I actually wanted to save the steps I took to get there as well.

Appreciate I could dump the command log, but that seems a bit more clunky than being able to just save the state.

**Comment by saulpw** [comment]
If the command log doesn't work for you for this purpose, then in truth it would be easier to make a utility that saved the entire state of any process and allowed it to be restored.  Which would be pretty cool, but outside the scope of VisiData.

Removing the wishlist tag because this doesn't seem very feasible for VisiData feature with its current architecture.

**Comment by saulpw** [comment]
Maybe I'm being too closed-minded here.  If someone can dream up a way to make it work, it would be a cool feature and we'd look into merging it in.
