### ISSUE TITLE
should not allow quit while save is in progress

### ISSUE THREAD

**Issue by shadiakiki1986** [saulpw/visidata#554]
**Small description**
Sometimes I would be saving a file, and then I press q to quit, but don't notice that the file saving is still in progress, so the csv file ends up being truncated.

**Expected result**
Do not allow quit until done

**Steps to reproduce with sample data and a .vd**
Open a large csv, save, press q while it is saving

**Additional context**
Please include the version of VisiData.
1.5.2

Related to https://github.com/saulpw/visidata/issues/389

Not sure if there needs to be a new release to get this fix

**Comment by anjakefala** [comment]
Thanks for the report @shadiakiki1986!

This is already in the `develop` branch. =) We added it in before closing that issue. The fix is linked within the issue.

 It does require a code change, so this will be part of VisiData 2.0, once it is released. You are of course welcome to install the `develop` branch, or apply the code change to your local version.
