### ISSUE TITLE
[wishlist] Commands for scroll-to-top, bottom, left right

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#559]
There is currently a zz command to scroll the current row to the middle of the window. 
Vim has the 'z-Enter' and 'z-' commands which will scroll the current line to the top or bottom of the window.

This feature request is to add similar commands to scroll the current cell to the top, bottom, right and left of the screen without changing the cell the cursor is pointing to.

**Comment by saulpw** [comment]
`scroll-leftmost` and `scroll-rightmost` are already available, but unbound.  Feel free to bind them as you like. `scroll-top` and `scroll-bottom` are trivial and can be derived from `scroll-middle`:

        Sheet.addCommand(None, 'scroll-top', 'sheet.topRowIndex = cursorRowIndex', 'scroll current row to top of screen')
        Sheet.addCommand(None, 'scroll-bottom', 'sheet.topRowIndex = cursorRowIndex-nScreenRows', 'scroll current row to bottom of screen')

`scroll-bottom` will have more challenges due to multi-line rows.  The problems are actually the same as with other paging, so it has to be addressed with multi-line rows functionality directly.
