### ISSUE TITLE
VisiData gets stuck loading files containing NULL bytes

### ISSUE THREAD

**Issue by jsvine** [saulpw/visidata#56]
When VisiData tries loading a file containing a NULL byte, it seems to get stuck mid-progress. For example, when you load [this file](https://github.com/saulpw/visidata/files/1095371/null-byte-example.csv.txt), you get only this:

![screen shot 2017-06-22 at 11 56 00 am](https://user-images.githubusercontent.com/534702/27443639-c8986832-5741-11e7-91d4-c1d81fa93047.png)

... and the `sheets` view says this:

![screen shot 2017-06-22 at 11 52 21 am](https://user-images.githubusercontent.com/534702/27443541-6af19348-5741-11e7-91b1-d36df0a72446.png)

**Comment by saulpw** [comment]
With this fix, it now looks like this: 

![vd-screenshot-nullbyte](https://user-images.githubusercontent.com/236498/27497379-49f237b4-5828-11e7-88be-52347bcc10a5.png)

Ideally, the row would be parsed as best as possible and flagged as unclean to VisiData, but the `csv` module in the Python standard library raises a generic `csv.Error`, and VisiData does not yet have a way to explicitly label error rows.  So is the best solution I can think of right now, which allows VisiData to continue loading, and still shows that some data went unparsed.

**Comment by jsvine** [comment]
Nice! One question/idea: What VisiData instead just stripped out all NULL bytes before processing?

I can't think of a scenario in which I'd want to retain a NULL byte, but perhaps I'm overlooking something.

**Comment by saulpw** [comment]
The main reason is performance.  I use VisiData to explore 10GB+ datasets, and examining every row for a NUL character (and removing them) before parsing would substantially increase the load time and possibly the memory usage.  The try/except probably increases the load time a bit too, but I did not measure it here because that would require a "rearchitecture" back to a less-optimized version of load_csv, and I agree that VisiData should not abort loading data due to one corrupt byte.

Also I'm very wary of any kind of automatic data filtering, even of NUL characters in text files :)

**Comment by jsvine** [comment]
Entirely makes sense. Thanks for the fix, and for providing this insight!
