### ISSUE TITLE
[wishlist] Expand -P to cover all longnames

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#560]
It seems like the vd -P command flag is close to what I want.  But it didn't work when running a command from a plugin.

Kondo as quietly as wanted.

**Comment by anjakefala** [comment]
I am a bit confused!

The feature exists on `develop`, the case you wanted just did not seem to work.

That seems more like a bug report? 

I think what is happening here is that some subset of commands are not being loaded before `-P` is running.

**Comment by frosencrantz** [comment]
This is what I'm seeing for a command added in a plugin loaded from the .visidatarc file, I run:

`vd -P longcommand data.json`

Visidata reports: `no binding for longcommand`

The command is defined as: `Sheet.addCommand('', 'longcommand', 'vd....', 'help...')`

There is no stack trace from ^E

I'm using the latest version from the `develop`.

**Comment by anjakefala** [comment]
Yah! That sounds like a bug. Nice catch. I will re-label this when I am done gaming for the day. :angel:

**Comment by anjakefala** [comment]
Okay! Some debugging info.

I found the catch. `globalCommands()` exist when vd tries to execute the `-P` longname. Sheet bound commands are not available at that point.

**Comment by frosencrantz** [comment]
Nice debugging!  Glad you were able to figure out the real problem.

**Comment by anjakefala** [comment]
So, preplay (`-P`) was originally designed because we wanted an efficient way to open the **PluginsSheet** upon start-up. It runs before the source sheet is even loaded. Because it runs so early, it was chosen that it would only execute commands that are bound to the **BaseSheet**. So commands that do not require having a standard tabular sheet. They can be run on **Canvas**es as well. 

So, it really is a preplay.

We could possibly change it so that it runs later, and can also run **Sheet** commands, but I am going to qualify that as a wishlist item, and instead document what it exactly does properly. It was an experimental feature quickly put together for a very specific use-case, and I am not sure if we should prioritise expanding it at this time.

If this gets added to the roadmap, we will re-open!
