### ISSUE TITLE
[wishlist] Postgres: Allow inserting / deleting rows

### ISSUE THREAD

**Issue by dufferzafar** [saulpw/visidata#579]
I looked at the code, and we already do this for SQLite. 

Shouldn't be hard to do for Postgres as well. Might take a stab at this over the weekend.

**Comment by dufferzafar** [comment]
Relevant SQLite source: https://github.com/saulpw/visidata/blob/develop/visidata/loaders/sqlite.py#L66-L85

If I made similar changes for Postgres. Should they go in the postgres loader? or should there be a separate module? since most of the code would be duplicated - as the SQL syntax is same.

@saulpw How would I run visidata from source?

**Comment by dufferzafar** [comment]
There seem to be other differences between the [postgres.py](https://github.com/saulpw/visidata/blob/develop/visidata/loaders/postgres.py) and [sqlite.py](https://github.com/saulpw/visidata/blob/develop/visidata/loaders/sqlite.py) files as well.

The sqlite loader seems to use a different API.

Which of these is the preferred way of doing such things?

Also, if I want to add more information to the initial postgres [tables sheet](https://github.com/saulpw/visidata/blob/develop/visidata/loaders/postgres.py#L78-L88) like adding the size (in MBs) of each table etc. is it okay to modify the existing loader? or should I create a custom loader for it?

**Comment by anjakefala** [comment]
If you want to take a crack at improving the postgres loader that would be awesome! I am afraid we most likely will not have the bandwidth to do it ourselves.

@dufferzafar sqlite.py is integrated with [defermods.py](https://github.com/saulpw/visidata/blob/develop/visidata/defermods.py). This is so that you can have "deferred changes". The changes you made to an sqlite file are colour coded, and then committed to source with `z Ctrl+S`. This is why there is a `putChanges()`. `putChanges()` is the code for the commit to source.

If you want deferred changes, then you will have to keep an eye on `defermods.py`. Basically, you will need to set `defer = True` in postgres, and have your code that writes modifications to source in a `putChanges()`. Read through the sqlite.py code carefully.

To set up a VisiData development environment:

    git clone the repository.
    git checkout the develop branch.
    Set the PYTHONPATH environment variable to the toplevel visidata directory (export PYTHONPATH=. if running visidata from directory itself). This ensures that you are executing the code in the current checkout, instead of the global install (without needing to uninstall VisiData).

In terms of whether to do it in the loader itself, or whether to pull the code into a separate module/plugin, I am not sure about the answer to that question should be. I think since you want to get started on it this weekend, make changes to the existing loader for now. If @saulpw then decides he would rather have the postgres changes moved to a separate plugin, I think that will not be a very complicated transition. We can guide you about that when the time comes.

**Comment by anjakefala** [comment]
Hi @dufferzafar! I am going to wishlist + close this issue. If you do end up picking it up, feel free to open a PR + tag. =)
