### ISSUE TITLE
[v2.-4dev/DirSheet] unhide-cols freezes interface with large files in dir

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#596]
When using `unhide-cols` on a `DirSheet` with large files the interface stalls. No user input is available, including `Ctrl+C`.

I saw this when I was looking at a directory with a file of 613718317 bytes.

**Comment by anjakefala** [comment]
If you are feeling in a deductive mood, did you want to try commenting out various Columns to try to narrow in on which one is causing the freezing? My gut instinct is that it is one of the hidden ones.

The code is in `visidata/shell.py`. =)

**Comment by saulpw** [comment]
That seems like it may be due to the `filetype` column, which runs `file --brief`on the file to get some basic information.  It's `cache=True`, but I'm guessing for those files that `file` takes awhile to return. So it should probably just be `cache="async"` anyway (which spawns a new thread for each cell).  Let me know if this fixes your problem (or doesn't).
