### ISSUE TITLE
[question] maintain columns selection passing from SHIFT+I to SHIFT+C

### ISSUE THREAD

**Issue by aborruso** [saulpw/visidata#608]
Hi,
I have a very bad CSV table, in which I want to remove all the columns that have only 2 distinct values.

It would be great that after selecting them via SHIFT+I sheet, and opening again the source table and then click SHIFT+C, the columns were still selected, so that they can be deleted.

Thank you

**Comment by saulpw** [comment]
This is not possible as you've stated, but have you tried using `g-` on the Describe Sheet to hide the selected columns?

**Comment by aborruso** [comment]
Hi @saulpw and thank you. I know I can use `g-` and it works great.

But I have made this as feature request, because in some way visidata should work in this way. Oone of its many excellent features is that everything is connected, passing from one sheet to a derived one.
And it would be great if there was also a "memory" of selected columns, from SHIFT+I to SHIFT+C and viceversa.

Thank you

**Comment by saulpw** [comment]
It is purposeful that the DescribeSheet works "like" the ColumnsSheet but does not use the list of Columns for the current sheet.  This way you can sort the columns on the DescribeSheet without affecting the order of the columns on the source sheet.

The only sheet that connects its selected rows with another sheet, is the FrequencyTable; and while that's been very useful, I've sometimes regretted it, as a neat hack that makes other things more difficult.  And the DescribeSheet is not actually connected to the ColumnsSheet at all; in fact, every time you press Shift+C, a new ColumnsSheet is created. So it would be quite a hack to make the DescribeSheet act as you suggest, and automatically select columns on newly created ColumnsSheets.

**Comment by saulpw** [comment]
Hang on, @aborruso, I think I have a solution.  Try this, from the source sheet:

- `Shift+I` to go to the Describe Sheet
- `Shift+C` to open its Columns Sheet
- `gs` to select all its columns
- `gy` to copy them to the clipboard
- `qq` back to the main sheet
- `Shift+C` to open the source's Columns Sheet
- `Shift+C` again to open *its* ColumnsSheet
- `p` to paste the DescribeSheet columns onto it
- `q` back to the ColumnsSheet
- et voila, you can now arrange the Columns using the DescribeSheet values.

This works because the rowtype for both Describe and Columns Sheet is `columns`.
