### ISSUE TITLE
[v2.-4dev] NameError: name 'mouseX' is not defined when replaying commands

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#637]
**Small description**
I saved the command log for a session in order to be able to save the progress I had made on modifying a file without exporting it again (basically so I would be able to keep keycols, py objects etc. rather than converting to text). I attempted to use `--play` against the original file however I got the following error, and the play command halted:

```
Traceback (most recent call last):
  File "/Users/Documents/pyv/py3/lib/python3.7/site-packages/visidata/basesheet.py", line 127, in execCommand
    exec(code, vdglobals, LazyChainMap(vd, self))
  File "release-mouse", line 1, in <module>
    import math
NameError: name 'mouseX' is not defined
```

**Expected result**
To be able to open the same source file, replay old commands and be back where I saved the command log

**Steps to reproduce with sample data and a .vd**
all.vd
```
sheet	col	row	longname	input	keystrokes	comment
	SqliteSheet	header	set-option	0		
	UsvSheet	delimiter	set-option	␞		
	UsvSheet	row_delimiter	set-option	␟		
	override	disp_date_fmt	set-option	%Y-%m-%d %H:%M:%S		
			open-file	a.csv	o	
a	c	0	release-mouse		BUTTON1_RELEASED	slide current row/column to mouse cursor release position
```

a.csv
```
a,b,c
1,2,3
```

**Comment by geekscrapy** [comment]
Obviously the `.vd` file is truncated, the last line is the one causing the issue

**Comment by saulpw** [comment]
Hi @geekscrapy, mouse commands on the canvas are not supported in replay currently.  This is a known issue and I'm not sure exactly how to fix it.  What's your actual use case here?  Are you trying to set the visible bounds, or trying to select a region with the cursor?

**Comment by geekscrapy** [comment]
To be honest, it was my first real go with --play!

So my situation was that I'd done a lot of transformation with my data (splitting, setting col types, setting aggs, joining tables etc, I had about 1M rows and about 100 cols....).

It was my way to get a duplicate session in another term, and allow me to run wild and play with the data and also retain the original data without the risk of deleting and messing something up!

I did notice that it was fine when I deleted this row. I didn't appreciate how the cmdlog actually worked before (based on colnames), but once I knew this, I got it working!

What's the issue with just ignoring/not logging these rows?

**Comment by saulpw** [comment]
> What's the issue with just ignoring/not logging these rows?

The replay will be busted if you select a region with the mouse and then 'd'elete, for example, because the cursor won't be the proper region on replay. I should probably just hack something together to store the coordinates on the cmdlog, since a better inspiration hasn't struck yet.  If that doesn't work for some reason we'll just add it to the nonlog list.

> I didn't appreciate how the cmdlog actually worked before (based on colnames), but once I knew this, I got it working!

I don't quite understand what you mean by "based on colnames".  Did you have to edit the cmdlog beyond deleting that one line?

**Comment by geekscrapy** [comment]
> I don't quite understand what you mean by "based on colnames". Did you have to edit the cmdlog beyond deleting that one line?

What I meant was that it appears that other lines of the command log look to use the column name as the way to identify the column to act upon? Or have I misinterpreted it?

**Comment by saulpw** [comment]
Ah, yes, exactly, and also the sheetname and sometimes row key/number.  In my mind they form a trio, sheet/row/col, even though I can see how in most .vd's the `col` column is the interesting one.

**Comment by saulpw** [comment]
This commit makes replay of canvas commands possible, but there is still an issue: if the replay is played without replay_wait, any commands on the canvas (select, delete) will not work, but the rest of the replay will proceed as though they did.  These commands don't work, because they rely on draw()'s plot of the pixels, and during a fast replay it doesn't get drawn.  If a wait is added (.5s seemed to work for me), then it does get drawn, and the replay works as expected.
