### ISSUE TITLE
[v2.-4dev] expanding a large list freezes interface

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#643]
**Small description**
I had a list that I accidentally tried to expand (500k items....). I couldn't cancel with Ctrl+C and no feedback was given to the user

**Expected result**
To not freeze the interface and be given feedback to when it might finish (progress)

I also wonder, are columns added iteratively or are they added at once all-together once the calculation has finished?

**Comment by anjakefala** [comment]
Hey @geekscrapy! @saulpw pushed a fix that makes expanding async, and thus cancel-able. Could you let us know how it feels for you?

**Comment by saulpw** [comment]
Yes, it should be async.  VisiData should never freeze and you should always be able to press `Ctrl+C` at least to stop its current activity.  But you're right, columns are added iteratively, so if you stop expand before it's done, you'll have to use `contract-col` instead of `U`ndo.

Progress is also harder to measure with expand, so no progress meter for now.
