### ISSUE TITLE
[livesearch plugin] Livesearch plugin doesn't fully clear screen during search

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#646]
**Small description**
The livesearch plugin no longer fully clears the screen during search.

**Expected result**
Rows not matching the current search term are not shown

**Actual result with screenshot**
Shown here https://asciinema.org/a/TG75hDQ1LhCZ4YEVf6JHTLVwY

**Additional context**
Please include the version of VisiData. Latest version from develop.

**Comment by saulpw** [comment]
I've verified that this bug does happen, but haven't been able to figure out why.

**Comment by saulpw** [comment]
I believe this is due to the searching func being async.  It can't draw the screen itself because it's in a different thread, but the screen isn't being redrawn after it's finished.  This is a larger problem that I've managed to hack around in other places, but I haven't able to fix this particular issue in a reasonable timeframe.

Since I'm not attached to this particular feature (which is why it's a plugin in the first place), and the plugin seems not very useful with this issue unfixed, I'm thinking that instead of spending any more time on this issue, we should instead deprecate the livesearch plugin and remove it from the plugins list.  You and anyone else can keep using it of course, but it won't be supported in the future (by me anyway).  I'd be happy to help anyone who wants to fix the issue and take over as maintainer.

**Comment by frosencrantz** [comment]
Thanks for investigating.  Sorry to hear it is difficult to fix.  I think it is still a useful feature, and understand it's current future.
