### ISSUE TITLE
[selection] Selecting None row causes header to be colored

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#650]
**Small description**
I created a small plugin which allows a user to define regex (with named capture groups) on the command line which opens a file with the capture group names as the column names. However when I do freq analysis on a column and tag the single None row, and go back to the original sheet the header has changed from blue to orange!

**Expected result**
The header row stays the same color with the row selected.

**Actual result with screenshot**
![image](https://user-images.githubusercontent.com/11225502/88667718-cee50500-d0f2-11ea-8796-2c97ca676457.png)

**Steps to reproduce with sample data and a .vd**
- Import the following plugin into .rc: https://gist.github.com/geekscrapy/a74efe2940262fd95823d41eedb3bde1
- Use the following command line:
`vd -g -f relog --regx=apache https://raw.githubusercontent.com/elastic/examples/master/Common%20Data%20Formats/apache_logs/apache_logs`
- Perform freq analysis on `http_ver` column.
- Select the `None` row
- Quit the freq sheet
- The header row has now changed color!

NB I've not debugged why the row is None, but I suspect it's just a regex parsing error. But I don't think this has anything to do with this bug?! I'll update if I find out otherwise!

**Comment by saulpw** [comment]
Interesting!  The issue is twofold:

The way the colorizering is designed, each colorizer is can be passed None for the row (meaning the header), or None for the column (meaning the separators).  Effectively a None row "is" the header row.  This way you can color a whole column (or row) by simply ignoring the row (or column) arg.  However, it does mean that colorizers need to be aware of it and check for None specifically.  This is not your problem, but it explains why the header is colorized when given a None row.

The real problem here, is that a row can't be None.  In fact, the main requirement for a row, is that it must have a unique rowid; you can't use integers or strings or small tuples which might be empty.  **If multiple rows have the same rowid, then selection will not work properly.**  And None will have the same rowid (see `id(None)` in the REPL), and there's nothing we can do about that.  So once you fix this issue and make sure that no row is None, this will stop happening.

If this caused you a lot of headache trying to diagnose, we can maybe put some rails on e.g. `addRow`, to issue a warning if it is passed a None (and maybe int and str and other non-unique types).

**Comment by geekscrapy** [comment]
I do remember the duplicate rowid quirk now... Doh!

Another way to catch it would maybe to check if the rowid has already been inserted? I.e. "there are x duplicate rows" during addRow? Many ways to do it I guess 🙂!

Tbh I didn't notice when making the loader, but I probably would've gotten confused if I actually worked with the data a bit

Thanks for the great explanation! 😊

**Comment by geekscrapy** [comment]
Also, I just refreshed my brain regarding id(None) .

I would say, as None is a singleton it would definitely be good to throw a warning when this is inserted with addRow. I didn't appreciate that None was a singleton, I just presumed it was another object...
