### ISSUE TITLE
[loading] sheets are not available for join until viewed or deliberately reloaded

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#656]
**Small description**
I attempted to open multiple files (xml) from the command line, and wanted to use `append` to join them to one larger sheet.
I went to the SheetsSheet selected the sheets with `stoggle-row`, and selected `append` from the `&` options.

**Expected result**
A sheet combined with all rows from the selected sheets

**Actual result with screenshot**
Only the first (top) sheets rows were present. I believe this is due to the fact that the other sheets effectively didn't have any rows as I hadn't opened/gone into them yet. From SheetsSheet the row counts were still 0.

Highlighting it mainly as it was unexpected behaviour and took a few attempts before I realised what was happening.

**Comment by anjakefala** [comment]
Thanks for the report, @geekscrapy! I have documented this behaviour =) https://www.visidata.org/blog/2020/unloaded/

I argue that this is not a VisiData limitation, because it does allow users to be a lot more secure with loading multiple large files, but this is something that trips people up, and is expected by design, so I am going to add that tag.

**Comment by saulpw** [comment]
Thanks for reporting, @geekscrapy.  @anjakefala is right, the default behavior is important to keep multiple large files from tanking the processor, but I've also been bitten by this, so I'm considering how we might tweak it so that in the average case with small files, it 'just works'.  Maybe something like loading the first N rows and then pausing until the sheet is shown.  This would be tricky to get right though, so for now we'll leave it closed and make it a wishlist item.

**Comment by geekscrapy** [comment]
Yup, I see the logic!

However, maybe a warning wouldn't go amiss? "You tried to join unloaded sheets". Maybe followed by a "do you want to load them?"

I would say though, if you want to join the sheets you'd have had to select them on purpose, for me I didn't care how big the sheets were, I just wanted them joined. The bigger issue for me was I was second guessing if I had all the expected rows, and if I'd actually done it correctly. And if you have some mixed sized (in rows) sheets you might not know exactly how many rows you are expecting to be joined (I didn't know as I hadn't loaded the sheets 🙃) catch 22....!

Also, if you do end up joining massive sheets, can't you just ctrl+c?

**Comment by yphillip** [comment]
The documentation for https://www.visidata.org/docs/join/ might need to be updated now to explicitly say that sheets need to be loaded before joining. I got tripped up by this just now as I recently upgraded from Visidata v1.5.2 to v2.0.1.

**Comment by yphillip** [comment]
Further following up on the join documentation (apologies if this should be it's own issue), I'm no longer able to select key columns with `g!` from the global columns sheet (`g Shift+C`) as described in https://www.visidata.org/docs/join/. Now it just says `no rows selected` at the bottom in yellow when I do `g!`. Going into individual sheets and selecting key columns with `!` still works though.

**Comment by saulpw** [comment]
These commands now only operate on selected rows, and will fail if no rows are selected.  Select some rows (columns) first, and then do `g!`.

**Comment by yphillip** [comment]
Ah I see now. It worked. Thank you.

**Comment by anjakefala** [comment]
Docs updated! They will be updated in the website on the next release (which is very soon).

Thanks for bringing this to my attention. =)
