### ISSUE TITLE
[cli options v2.-4] --opt=value replaces `-` with `_` in value

### ISSUE THREAD

**Issue by forensicdave** [saulpw/visidata#657]
**Small description**
Weird one - I can open up utf-16 encoded file with Visidata 2.3:   v'd --encoding=utf-16 file.csv' is Good. But updating to 2.4 and it fails.
It also fails in the develop branch.

**Expected result**
Should open the file ok. (have attached sample utf-16 csv file)

**Actual result with screenshot**

I've attached a sample utf-16 file.

Reproduce by:
pip3 install git+https://github.com/saulpw/visidata@v2.-4.0
visidata --encoding=utf-16 sample.csv
(for me: ~/.local/bin/visidata --encoding=utf-16 sample.csv   )

Gives me this error:
![image](https://user-images.githubusercontent.com/7690349/89696971-6cdf9780-d95d-11ea-9a35-2d659fbca846.png)

Stack trace:
![image](https://user-images.githubusercontent.com/7690349/89697000-854fb200-d95d-11ea-8745-932122452c1d.png)

If you get an unexpected error, please include the full stack trace that you get with `Ctrl-E`.

**Steps to reproduce with sample data and a .vd**
Please attach the commandlog (saved with `Ctrl-D`) to show the steps that led to the issue.
See [here](http://visidata.org/docs/save-restore/) for more details.

Command log:

![image](https://user-images.githubusercontent.com/7690349/89697031-a6b09e00-d95d-11ea-8d4c-c92f4a969f3f.png)

**Additional context**
Please include the version of VisiData.

This happens on visidata 2.4 and above but not 2.3

Sample utf-16 csv is attached (it has been renamed as .txt to allow upload)

Thanks guys too - this is an amazing piece of work!!

[sample.csv.txt](https://github.com/saulpw/visidata/files/5044345/sample.csv.txt)

**Comment by saulpw** [comment]
Thanks for filing this bug, @forensicdave!  It has to do with the CLI options parsing, which was redone in 2.-4. (Note the `-` in the version number, which indicates this is a 2.0 prerelease; there will probably be a 2.3 and 2.4 in the future so it's important not to confuse them).

Your bug report has all the information I need, such that I barely needed to look at the code to know what was wrong.  Note that in the .vd file you included (as an image; in the future please include as an attached file so we can download and use it), the input for the option is `utf_16` with an underscore, whereas it should be `utf-16`.  The options parser works by replacing all `-` with `_` in option names, but there's a bug where if you use the `X=Y` form, the replacement is done in both X and Y.  This bug should be fixed with the above commit, but in the meantime, you should be able to use `--encoding utf-16` without the `=`, and it should work fine.

**Comment by forensicdave** [comment]
Thanks so much Saul - apologies for the image - love your work it is just
brilliant! Best regards and wishes!
