### ISSUE TITLE
[types] floatsi parser

### ISSUE THREAD

**Issue by anjakefala** [saulpw/visidata#661]
It would be great if VisiData had a type which:
* correctly interpreted cell values which contain the International System of Units, and was able to treat them as numerical data
* allowed conversion from raw bytes to human readable values with unit prefixes

This would be especially fun for working with data piped in from `ls`, `df`, `du`, `free`, etc.

**Comment by saulpw** [comment]
This is a good idea, @anjakefala, I've wanted this myself many times.  I added a `type-floatsi` (bound to `z%` for now), that displays a normal float with their SI prefixes.

Parsing is also a good idea, but let's make it a wishlist item for now.  It may be able to happen naturally if we make a 'units' module that can parse and/or convert various unit and currency symbols/abbreviations.

**Comment by anjakefala** [comment]
Sounds good!

**Comment by geekscrapy** [comment]
RE @anjakefala original post. Interested in how this might work, as I have a similar idea I want to do.

How would vd determine the type of format to convert to? Choice selector like aggregator choice, or maybe based on the `col.name` or sheet type?

**Comment by frosencrantz** [comment]
Thanks for adding this @saulpw !

I tried this new feature, but had some difficulty at first because I misunderstood how it worked.

I tried:  `df -h | vd -f fixed`

Thinking Visidata would be able to parse and understand the human format of values, but that is not what this change does.
So the correct way is to send it in without the -h, and then have Visidata look at the number and then it will generate
the SI units.  That worked just fine.

The GNU coreutils sort already has a a flag to sort by SI units, the --human-numeric-sort/-h flag.

Glad to see the new feature, and someday it would be nice if it could understand values generated by `df -h`

**Comment by saulpw** [comment]
Okay, now floatsi will parse "SI numbers" like "10M" (no units yet though).  Thanks to @frosencrantz for the easy `df -h | vd -f fixed` use case, and y'all can thank @anjakefala for sponsoring this wishlist item via Patreon.

**Comment by anjakefala** [comment]
Thank you!!! :blush:

**Comment by frosencrantz** [comment]
Tried this, works great!  Thanks @saulpw and @anjakefala for sponsoring and suggesting.
