### ISSUE TITLE
JSON list/dict expansion only expands items present in current row

### ISSUE THREAD

**Issue by lxcode** [saulpw/visidata#663]
When analyzing Twitter JSON, there is an "entities" object that can variably contain urls, hashtags, or user mentions. When expanding columns in this data, only the types included in the current row are expanded. 

For example, if the "entities" column of the selected row has hashtags present but no urls, new columns are created for hashtags. Columns are never created for the rows in which "entities" does contain urls.

Additionally, only the number of elements present in the selected row is expanded — for example, if there is an object with an array of 2 hashtags, only two columns are created, and rows with 4 hashtags will not have their latter two displayed.

**Expected result**

All elements of "entities" in all rows are unnested.

**Actual result with screenshot**
Expanding "entities" with the first row selected:

<img width="821" alt="Screen Shot 2020-08-15 at 13 35 34" src="https://user-images.githubusercontent.com/1959603/90321232-a172c680-defc-11ea-8a1f-ca7126e9e3e9.png">

Expanding with second row selected:

<img width="1428" alt="Screen Shot 2020-08-15 at 13 36 12" src="https://user-images.githubusercontent.com/1959603/90321231-a0da3000-defc-11ea-8485-096fe7ed573e.png">

**Steps to reproduce with sample data and a .vd**
Twitter developer agreement actually prevents me from distributing the data, but here is a sample json blob from their docs:

[sample.txt](https://github.com/saulpw/visidata/files/5079410/sample.txt)

**Additional context**
Version 1.5.2 via Homebrew

**Comment by ajkerrigan** [comment]
Hey there @lxcode - that feature has been updated a bit since v1.5.2, in part to address the inconsistent expansion behavior you mentioned. If you're up for trying your analysis using the [v2.x](https://www.visidata.org/v2.x/) release, the expand should work more like you'd expect. Let us know how it goes!

(On a related note, v2.-4.0 also introduced the `unfurl-col` command. It's a cousin to `expand-col`, but expands row-wise instead of column-wise. May be handy!)

**Comment by lxcode** [comment]
Yup, can confirm it expands all fields in the 2.x release. Thanks!
