### ISSUE TITLE
How do I update a column expression?

### ISSUE THREAD

**Issue by ksalman** [saulpw/visidata#688]
Sometimes I want to create a new column with a complicated expression and I don't get the expression just right. Instead of deleting the column and retrying, it would be nice if one could edit/update the expression that produced a column.

**Comment by saulpw** [comment]
You can do this.  Just go to the Columns Sheet and edit the `expr` column.  The name won't change but it will use the new expr for computation.  You may have to use `z'` to reset the cache on the column.

If you want to edit the expr on the status line (instead of having to go to the Columns Sheet), you can make this too.  It should be a one-liner. (`col.expr=input("new expr: ", value=col.expr)`)
