### ISSUE TITLE
Cannot remove sheet disp_date_fmt option

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#733]
I have a global setting for `disp_date_fmt` (e.g. %Y-%m-%d %H:%M:%S). When I want to override it for one particular sheet, I enter `zO` and provide my new format (e.g. %Y-%m-%d). If I then want to remove that format from the sheet at a later date (and let the global setting take precedence once again), I cannot. Setting it to "" (empty string) vd takes this as the format and the column values and interprets it as a format string (which prints nothing).

**Comment by saulpw** [comment]
Hm, I can't repro this behavior with an empty string.  Are you sure the string is empty?  You could also try `zd` to set the cell to null, and see if that helps.  But this should work.

**Comment by saulpw** [comment]
Hah, I was ignoring your actual repro, and using the columns sheet to set the fmtstr (which can be reset just fine).  The issue is that setting an option to `''` is not the same as unsetting the option (since sometimes you want to forcibly set an option to the empty string, even if it doesn't make sense for `disp_date_fmt`).  It seemed easiest to add an `options.unset()` function which does what is expected, and to add an `unset-option` command and bind it to `d` on the OptionsSheet.  So now you can press `d` on the OptionsSheet to unset the override value, or `zd` on the value cell will do the same thing.

Thanks for the bug report, and let me know if this works for you!

**Comment by geekscrapy** [comment]
Thanks @saulpw this works, but it'll take some getting used to as it's unexpected and doesn't work like the columns sheet. But, technically it makes sense, as it's a `_fmt` option.

Have you thought of showing something like "unset" in the options sheet rather than a blank cell? This would hopefully do two things, 1. allow a user to instantly determine if they have set the option rather than an empty string, 2. act as a reminder (to those that know about it) and a discovery tool (for newbies) telling them that you can unset an option with the new `unset-option` command.
