### ISSUE TITLE
When I use --filetype=fixed in combination with --play visidata parses STDIN as a single column

### ISSUE THREAD

**Issue by jaresty** [saulpw/visidata#746]
**Small description**

When I use `--filetype=fixed` and `--play=x.vd` on STDIN it reads input as a single column.

**Expected result**

I expected it to parse the columns in the same way it behaves without using `--play=x.vd` such that the columns would be separate.

**Actual result with screenshot**
![image](https://user-images.githubusercontent.com/1313844/96916958-1d3d4200-145d-11eb-9aa1-e8c2b05427fc.png)
vs
![image](https://user-images.githubusercontent.com/1313844/96917019-2d552180-145d-11eb-8014-fb6d634cecfc.png)

**Steps to reproduce with sample data and a .vd**
A similar thing can be accomplished using `ps -e | vd --filetype=fixed --play=foo.vd -`

```
> cat foo.vd
sheet	col	row	longname	input	keystrokes	comment
	-	filetype	set-option	fixed
			open-file	-	o
-	TTY		select-col-regex	pty	|	select rows matching regex in current column
-	TTY		freq-col		F	open Frequency Table grouped on current column, with aggregations of other columns
-	TTY		select-col-regex	tty	|	select rows matching regex in current column
```

**Additional context**
vd version 2.0.1

**Comment by geekscrapy** [comment]
Hey @jaresty !

It looks like your data is tab separated? Try out the following:
`ps -e | vd -f tsv --play=foo.vd -`

This should tell vd that the file type is tab separated (.tsv).

If it's not tab separated, what is the delimiter?

**Comment by jaresty** [comment]
It's not tab-separated; but what is more relevant to me is that the behavior when you pass `--play` is different from when you do not.  I was able to get columns to be recognized without passing that option, but then I could not use `--play` to reuse the command log afterwards because it didn't recognize the columns.

**Comment by jaresty** [comment]
If you run `ps -e | vd -f fixed` it works as expected.

**Comment by saulpw** [comment]
Hi @jaresty, thanks for the report.  The issue here is that `--filetype=fixed` only applies to files given on the command line, and not those opened later (like in replay).  If you add `-g` before the option, it will apply globally.  Alternatively, the .vd file could set the option before opening the file.  (This will be added automatically if you used `-g` in the session that you save the .vd file from.)

I agree that this is somewhat confusing, and it happens in a variety of cases.  The interface fix increasingly seems to be that we should invert this options parsing logic, so that options are global by default, and need to be specified differently if they only apply to a single file on the command line.  But that would be a bigger change and I want to think it through before changing the options up again.

**Comment by jaresty** [comment]
I see -- `-g` does seem to do the trick.  Thanks!  I would vote to make this behavior consistent if that is an option sometime in the future.  I'll close this issue.
