### ISSUE TITLE
Macro capability

### ISSUE THREAD

**Issue by bob-u** [saulpw/visidata#755]
> We want to hear your ideas about where VisiData can go and anything you think could be made smoother.
We consider all ideas that are feasible, but please don't be offended if we close it--we generally limit our open issues to bugs and small concrete feature requests that are part of the planned roadmap.

> If you are a subscriber at the 'Workflow Optimist' level on [Patreon](https://www.patreon.com/saulpw/), you can designate this feature as one you would like to remain open, by adding an "[optimist]" tag in the summary line.

Great program.  Few suggestions from a new user:

1. I would suggest to add word "macro" when describing replay command log in doc for more successful searches as I think macro capability is a word excel users would look for.
2. It would be nice to be able to assign cmdlog to a key/command.

**Comment by anjakefala** [comment]
Thanks for the suggestions @bob-u!

We used to have an experimental macros system. It is distinct from cmdlog because you could bind the series of commands to a key and replay commands  within a session (replay is not exactly a macro, which is why we do not use the word when describing it).

We decided to give this experiment another try, and came up with a better variant of it. I will be curious if it works for you.

- `m` (`macro-record`) begins recording macro; `m` prompts for keystroke,
and completes recording
- macro can then be executed everytime provided keystroke is used. Note, this will
override existing keybindings, we recommend binding to `1-9`.
- macros will run the series of commands on current row, column sheet
- `gm` opens an index of all existing macros, can be directly viewed
with `Enter` and then modified with `Ctrl+S`

Let us know how it feels!

[Time to implement feature request: 2 hours]

**Comment by anjakefala** [comment]
Your help would be welcome in documenting the feature on [the replay page](https://github.com/saulpw/visidata/blob/develop/docs/save-restore.md). =)

**Comment by bob-u** [comment]
Thank you for that.  This is very useful feature.  Once I install the development version on my laptop I will try it.
