### ISSUE TITLE
[async] Sheet corruption within VisiData due to commands running on partially completed async tasks

### ISSUE THREAD

**Issue by bob-u** [saulpw/visidata#759]
**Small description**
This is rather big deal and I hope this is a bug, not a feature :)  When working with large files it takes seconds or minutes for select task to finish.  Pressing " will switch to what is currently selected w/o waiting for select task to complete.
**Expected result**
I would expect for EVERY command to be *fully* applied to all data equally.  If command is interrupted in the middle of processing (by other command) - everything that it did should be reverted to prior of running the command or, preferably, command should be queued for after previous task had finished.
**Actual result with screenshot**
If you get an unexpected error, please include the full stack trace that you get with `Ctrl-E`.

**Steps to reproduce with sample data and a .vd**
open a large file
press | for regex select and type your regex , press enter
press " while regex selection is still processing
It'll result in incomplete selection
Please attach the commandlog (saved with `Ctrl-D`) to show the steps that led to the issue.
See [here](http://visidata.org/docs/save-restore/) for more details.

**Additional context**
Please include the version of VisiData.
2.01
Windows
Python 3.9

**Comment by saulpw** [comment]
Well, sorry to disappoint, but this is definitely a feature.  VisiData will happily churn through gigabytes of data if you have enough memory, and so the ability to dive into subsheets while a main sheet is still loading is a core use case for some people (including myself).  A primary use case is data exploration, and partial results in that case are still very usable.  Aborting async commands (with e.g. `Ctrl+C`) will stop processing, but will **not** revert any work already done, and this is also by design. 

We've considered preventing additional modifications (anything undo-able) while a long-running modification is working, which is probably still a good idea, but the `dup-sheet` command isn't a modification and wouldn't be prevented from running even under this scheme.  Queueing commands is a whole other ball of worms that I'm not interested in getting into.  At best we could provide a warning or so.

Note that in replay/batch mode, all commands are serialized, so this issue only comes up in interactive mode.  There should always be a "working..." indicator in the lower right status when threads are executing some async task on the current sheet.

**Comment by bob-u** [comment]
I am not talking about intentionally aborting async commands.  I expect for when I run a command - it does the task completely so I would definitively expect " command to be unavailable  while selection is in progress.

1. select data with regex
2. press " before selection finished
3. result is partial selection dependent on when in the selection process you pressed " - I fail to see how such outcome could be useful?
