### ISSUE TITLE
[2.x] cache-col does not immediately evaluate all values in column

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#773]
**Small description**
_Appreciate this maybe by design, but it caught me out!_

I used `cache-col` to get around the "limitation" in #756 (thinking I was being smart :)), however it only evaluated the cell values within the current display, leaving the rest of the column cell values as exceptions. The thinking was that I would be able to freeze the expr using `cache-col` (as I wanted to chang ethte name of the source column), however to do so it also required me to do some kind of function which forced evaluation of the entire column (e.g. freq sheet), _then_ do `cache-col`. It's an unexpected extra step that I believe you need an understanding of vd to be able to figure out how to get what you want.

**Expected result**
When using `cache-col` I expected the entire column values to be evaluated and cached

**Comment by saulpw** [comment]
Hi @geekscrapy, thanks for pointing this out.  You're right that `cache-col` just enables/resets the column cache rather than computing all values, and this is by design.  You might want to try out `freeze-col` (bound to `'`) which creates a new "frozen" column with all the values computed.  Maybe we could streamline the way that freezing works to make it better for this kind of case; e.g. replacing the column with an identically named but now-frozen column.  This particular solution makes me a bit nervous but maybe there's something we can do so that you're not surprised by the behavior.

**Comment by geekscrapy** [comment]
Maybe it's just a naming thing?
`cache-col` makes me think that it'll go away and cache the columns values? Maybe that's my confusion. Maybe something like `recalc-col` is appropriate? Appreciate that's now not an easy thing as others might depend on it..!

Now I know that freeze-col does that, it makes sense (I mainly used it to convert epoch dates to a date col). My thought with freezing was that it set the display value of the column and tried to cast/force to the current columns type (but it turns out that's just me no RTFM.... 🙂)

As always thanks for the explanation
