### ISSUE TITLE
ALT-# bindings not working on MacOS

### ISSUE THREAD

**Issue by rswgnu** [saulpw/visidata#778]
I am using V2.0.1 and all other keys seem to be as documented but I can't get any response from trying ALT-# keys nor ESC [0-9].

**Comment by rswgnu** [comment]
The issue was the Mac Terminal program grabbing those escape sequences.  There is a setting to use Option as the Meta key and with that turned on, then these keys work.

**Comment by ajkerrigan** [comment]
I see that this issue is already resolved, great! I ran into a related issue a while back though, so it's worth posting a response in case someone else comes searching.

The ALT-# bindings worked out of the box for me in the default Mac terminal, but I'm primarily an Alacritty user. Alacritty's ALT-# bindings were sending unicode characters by default. I worked around that by either binding those characters to the VisiData jump commands in `~/.visidatarc`:

```
BaseSheet.bindkey('¡', 'jump-sheet-1')
BaseSheet.bindkey('™', 'jump-sheet-2')
BaseSheet.bindkey('£', 'jump-sheet-3')
BaseSheet.bindkey('¢', 'jump-sheet-4')
BaseSheet.bindkey('∞', 'jump-sheet-5')
BaseSheet.bindkey('§', 'jump-sheet-6')
BaseSheet.bindkey('¶', 'jump-sheet-7')
BaseSheet.bindkey('•', 'jump-sheet-8')
BaseSheet.bindkey('ª', 'jump-sheet-9')
BaseSheet.bindkey('º', 'jump-sheet-10')
```

Or adding a block to `~/.config/alacritty/alacritty.yml` so Alacritty would send the escape sequences I expect:

```
  - { key: Key1, mods: Alt, chars: "\x1b1" }
  - { key: Key2, mods: Alt, chars: "\x1b2" }
  - { key: Key3, mods: Alt, chars: "\x1b3" }
  - { key: Key4, mods: Alt, chars: "\x1b4" }
  - { key: Key5, mods: Alt, chars: "\x1b5" }
  - { key: Key6, mods: Alt, chars: "\x1b6" }
  - { key: Key7, mods: Alt, chars: "\x1b7" }
  - { key: Key8, mods: Alt, chars: "\x1b8" }
  - { key: Key9, mods: Alt, chars: "\x1b9" }
  - { key: Key0, mods: Alt, chars: "\x1b0" }
```

Either way can get ALT-# bindings working inside VisiData, and I expect that other platform/terminal combinations might need similar tweaks. (To be clear I'm not suggesting that VisiData should try to handle those cases automatically. That way madness lies.)
