### ISSUE TITLE
[interface] add option for more immediate results to save keystrokes

### ISSUE THREAD

**Issue by rswgnu** [saulpw/visidata#780]
I'd like to suggest you consider adding an immediate mode that a user can toggle in an out of.  Since most users have a variety of data analysis tools to choose from, one of the big selling points of VisiData (and there are many) is its interactivity and the resulting immediacy of on-screen feedback.  But there are a few areas where this could improve.

Often one just wants to apply a filter to some data and immediately see the effect without having to apply multiple commands.  Immediate mode would allow this as well as other capabilities.  If a selection operation selects multiple rows, then a new sheet would appear with just the selected rows (as if " had been pressed).  If an aggregator were applied to a column, the aggregation result would immediately appear and stay visible after successive commands.  The general idea would be to change the mode from 'select' and then apply operation to 'select and filter' all at once.

**Comment by saulpw** [comment]
Interesting idea, @rswgnu. For the selection case it seems like there is some overlap with `options.bulk_select_clear`.  I don't understand how the aggregator case would work, since the aggregated column and the group by columns are different.  In any event these seem like meager efficiency gains for the effort required to implement.

Kondo'ed for now.
