### ISSUE TITLE
Show command description when showing full command

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#782]
To assist with learning and discovering the purpose of commands, a suggestion would be to show the command description after the command string at the prompt, maybe separated by a pipe character (for example) or positioned at a set offset.

This would assist all levels of users, those that are new to vd, up to experienced users discovering features in new plugins.

**Comment by saulpw** [comment]
Back in v1.2.1, VisiData briefly had a longname menu (bound to Space), which allowed you to browse commands on the status line, and it would show the next level or the helpstr one line above.  It didn't survive very long, in part because it was really difficult to organize the commands meaningfully within the longnames themselves.  But I'm curious if what you're looking for is something like this, maybe in exec-longname?

**Comment by saulpw** [comment]
Kondo'ed for now.
