### ISSUE TITLE
Apply `n` and `N` search continuation to `c` column search

### ISSUE THREAD

**Issue by lamchau** [saulpw/visidata#842]
**Small description**
`n`/`N` applies to all _regex_ commands **except** for _columns_.

```
      /   ? regex     search for regex forward/backward in current column
     g/  g? regex     search for regex forward/backward over all visible columns
     z/  z? expr      search by Python expr forward/backward in current column (with column names as variables)
      n   N           go to next/previous match from last regex search

      c regex         go to next column with name matching regex
      r regex         go to next row with key matching regex
```

**Expected result**
Pressing `n`/`N` jumps to the next column matching _regex_

**Actual result with screenshot**
`no regex` warning appears

![image](https://user-images.githubusercontent.com/4911400/102092645-20a5d780-3dd5-11eb-8b8a-a81d54c42f31.png)

**Steps to reproduce with sample data and a .vd**
 1. `vd data.csv`
 2. `c` (column regex)
 3. Query for `a`
 4. Press `<enter>`
 5. `n`/`N` for next column
 6. `no regex` warning appears

```csv
A,B,C,A,B,C,A,B,C
1,2,3,1,2,3,1,2,3
1,2,3,1,2,3,1,2,3
1,2,3,1,2,3,1,2,3
1,2,3,1,2,3,1,2,3
1,2,3,1,2,3,1,2,3
```

**Additional context**
```shell
> vd -v
saul.pw/VisiData v2.1
```

```shell
> pfetch
       .:'
    _ :'_       os     macOS Catalina 10.15.7
 .'`_`-'_``.    host   MacBookPro15,1
:________.-'    kernel 19.6.0
:_______:
 :_______`-;
  `._.-._.'
```

```shell
> python3 --version
Python 3.9.1
```

**Comment by saulpw** [comment]
Hi @lamchau, I'm not sure if `n` and `N` should apply to `c` and `r` commands.  If people want to lobby one way or the other, please add comments here.

**Comment by lamchau** [comment]
Hi @saulpw, luckily it already works with `r` for row keys (as expected; similar to `/`)! The only one it's missing from is `c`, so perhaps we could just add it in for completeness?

**Comment by saulpw** [comment]
Hi @lamchau, I looked into this a bit more, and the continuations work with `r` because it's a row-based movement. So `c` is kind of fundamentally different even if it seems very similar in usage.  Searching with continuation is also more complicated than you might expect--particularly the ability to bounce between the prev and next found item.  

As a workaround, you can use `c Enter` to re-do the previous column-name search.

This feature request is not entirely out of the question, but at the moment it's not worth it to implement.  If others have strong opinions, please chime in.  Kondo'ed for now.
