### ISSUE TITLE
How to select only null cells or only empty cells

### ISSUE THREAD

**Issue by tomwitt2** [saulpw/visidata#880]
**Small description**
Can't select specifically empty cells vs cells containing null

**Expected result**
If my file format (JSON) can distinguish between an empty value ("FAVORITE_COLOR": "" ) and a null value ("FAVORITE_COLOR": null), I would expect doing selections in Visidata using any of the following would give me selections identical to my indicated target value
- using comma while on an empty value to select only empty value cells
- using comma while on a null value to select only null value cells
- using z| FAVORITE_COLOR == '' ; to select only empty value cells
- using z| FAVORITE_COLOR is None ; to select only null value cells

**Actual result with screenshot**
- using comma while on an empty value (actual result is selects both empty and null value cells)
- using comma while on a null value (actual result is selects both empty and null value cells)
- using z| FAVORITE_COLOR == ''  (actual result is this works and selects only empty value cells)
- using z| FAVORITE_COLOR is None (actual result is no rows are selected)

If you get an unexpected error, please include the full stack trace that you get with `Ctrl-E`.

**Steps to reproduce with sample data and a .vd**
Please attach the commandlog (saved with `Ctrl-D`) to show the steps that led to the issue.
See [here](http://visidata.org/docs/save-restore/
![Selection_015](https://user-images.githubusercontent.com/8881606/106077161-069f2a80-60df-11eb-8a22-459710e429a4.png)

[visidata_issue.zip](https://github.com/saulpw/visidata/files/5884211/visidata_issue.zip)

) for more details.

**Additional context**
Please include the version of VisiData.
Version is saul.pw/VisiData v2.1.1

**Comment by saulpw** [comment]
Hi @tomwitt2, this is a good question, and your approaches are very reasonable.  

You can select those rows with None by using `z,` or "select-exact-cell".  This matches by the **typed value**, whereas "select-equal-cell" matches by the **displayed value**.

You can also go to the Describe Sheet (`Shift+I`) and use `zs` ("select-cell") on a nulls cell, to select those rows.

FWIW, I thought that `z| col is None` should work too (for an `anytype` column, anyway).  But it turns out that the [typed value of Python None is always a `TypedWrapper`](https://www.visidata.org/docs/api/columns.html#user-defined-types), which allows sorting etc on columns with None values.  This means you could also use `z| col.val is None` (although this is undocumented currently, so it's not the recommended solution).

**Comment by tomwitt2** [comment]
Awesome! Thanks for the quick response.  z,   ... my new best friend.

**Comment by anjakefala** [comment]
The docs on the website are going to be updated with the answer here in the next release!

Thanks for the good question. =)
