### ISSUE TITLE
[splitwin] Fixed splitwin location

### ISSUE THREAD

**Issue by lamchau** [saulpw/visidata#894]
Thank you for adding a [`splitwin`](https://www.visidata.org/blog/2020/splitwin/) feature!

I feel it has a couple of use cases but the current one feels a little counterintuitive. I'm treating it more as a preview panel so I'd like to understand how to use it.

**Example**:
1. Open a JSON file (array of objects)
2. Shift-Z (`splitwin` opens at the bottom)
3. Select Row > Enter
4. `splitwin` opens (columnar-row view [top], `Sheet` [bottom])
5. Tab > Select Row > Enter
6. `splitwin` opens (columnar-row view [bottom], `Sheet` [top])

As I go through a flow of steps 3-6, it continuously swaps makes it hard to know spatially where I am. I'm expecting the `splitwin` to be static/fixed. If this is an intentional design, could we add a `fixed.location` option for this use case?

My current workaround is to `(` to expand, then undo to "re-collapse" vs preview pane (alternatively keeping `vim` in a split pane).

**Comment by saulpw** [comment]
Hi @lamchau, this is great feedback, and I appreciate the very explicit workflow example.  I tried a couple of different approaches during development, and you're not the first person to notice that the one that got released doesn't really work for some basic use cases. The current model for splitpane--show top two sheets with `options.disp_splitwin_pct` determining how much and which part of the screen the second sheet gets--is probably insufficient and not how this feature will be structured long-term.

One idea I've been considering is changing the second pane to be a "pinned sheet" instead.  For your case, you'd pin your top sheet, and then pressing enter on a row would push that row onto the stack in the first pane.  The trick here is that if you Tab back to the other sheet and then press Enter again, as in the given workflow, you'd wind up having both rows on the stack now--you'd have to deliberately 'q'uit the sheet instead of Tab.  Maybe that's desirable.

Anyway we'll do something about this. Thanks for filing an issue!

**Comment by anjakefala** [comment]
Hi @lamchau! I can confirm that the current splitwin on `v2.4` has a much more intuitive and "sticky". The example you gave works as you would expect it to. The columnvar-row does not move around. 

Update and give it a try! `v2.5` will be out soon, and it will have an additional bit of polish.

**Comment by lamchau** [comment]
@anjakefala thank you for this, i've been giving `master` a go for several days now!

**Comment by saulpw** [comment]
I hope you mean the `develop` branch! Our main branch (with 2.4, still the most recently released version) is `stable` :)
