### ISSUE TITLE
[help] help-commands-all missing some bindings

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#896]
**Small description**
`help-commands-all` sheet is missing some key bindings.

**Expected result**
All bindings are shown in `help-commands-all`

**Actual result with screenshot**
https://asciinema.org/a/D71Iq7pDIK5wnhGeZgKdFHSqB

**Steps to reproduce with sample data and a .vd**

Go to `help-commands-all` search for keys.

I was trying to find the bindings for PgUp/PgDown keys, but I was not able to find them in help-commands-all.  The source code has the binding, but I use `help-commands-all`.  I am not sure why the binding is missing.

https://github.com/saulpw/visidata/blob/d48c91ce9fee9daffc85a671af62b3f412495f50/visidata/movement.py#L147

**Additional context**
Please include the version of VisiData. latest version of develop

**Comment by saulpw** [comment]
After some thought, I've added a hidden `all_bindings` column to the HelpSheet that is a list of all the bindings for that command.  Unhide with `gv` and unfurl with `zM`, or whatever you like depending on your needs.  I chose not to change the existing `keystrokes` column because it was confusing for the base case ("what keystrokes do I press for this command?").
