### ISSUE TITLE
[unfurl] Unfurling a row with an empty list/dict causes the row not to be shown

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#898]
**Small description**
unfurling an empty list or dict causes the row not to be shown.

**Expected result**
The row to be shown with a null value in the value column

**Actual result with screenshot**
https://asciinema.org/a/doNxLH2PzLCT5CeabB4279ceq

The rows are not shown.

**Steps to reproduce with sample data and a .vd**
```
cat > bug.jsonl <<EOF
{"a":[]}
{"a":[]}
EOF

vd foo.jsonl
unfurl-col
```

**Additional context**
Please include the version of VisiData. Latest version of develop

**Comment by geekscrapy** [comment]
This was originally described in #639, but I don't think it was looked at again.
I'm still in favour of an empty list being shown in the final results and not dropped

**Comment by saulpw** [comment]
This behavior is intentional, and for the cases I use unfurl, I *don't* want a blank row for source rows with an empty list. For me, unfurl is all about the elements in the list column, and the other columns are useful only in relation to those elements.  Melt, similarly, does not create rows for missing/None values.

Can you provide your actual use-case?  Maybe there's a reasonable workaround, or maybe we can create an option.

**Comment by geekscrapy** [comment]
There are definitely times that I need the full rows in my dataset, just to show that they _didn't_ have anything of importance. At the moment I have to rejoin the original data to get a full list.

My use case is retrieving list data from an API. If nothing is found, that's fine, but I still need to know this as it is part of the output.

An option to include nulls would be very welcome

**Comment by saulpw** [comment]
Option added.

**Comment by frosencrantz** [comment]
🎊  Wonderful!  Thank you, @saulpw!
