### ISSUE TITLE
$XDG_CONFIG_HOME used literally

### ISSUE THREAD

**Issue by wavexx** [saulpw/visidata#93]
When reading the config file, vd looks for '$XDG_CONFIG_HOME' literally (that is, without expansion).
Moreover, it's not that simple. $XDG_CONFIG_HOME is usually not set explicitly. You should use the 'xdg' module.

**Comment by saulpw** [comment]
That is due to os.path.expandvars() apparently working as designed: "Malformed variable names and references to non-existing variables are left unchanged."  Which is not like the shell, but makes sense from a security standpoint.

I would much prefer not to add an additional dependency just to play nice with xdg config dirs.  Do you use the xdg config layout yourself?

According to [this superuser question](https://superuser.com/questions/365847/where-should-the-xdg-config-home-variable-be-defined), the XDG spec says: "If $XDG_CONFIG_HOME is either not set or empty, a default equal to  $HOME/.config should be used."  So I can add a bit of code to `bin/vd` to check if `XDG_CONFIG_DIRS` is set, and if not, check for `$HOME/.config/.visidatarc` instead.  Is this worth it?  Alternatively we can just remove the `XDG_CONFIG_DIRS` option entirely (I was unsure about including it in the first place but it was easy enough so I figured why not).

**Comment by saulpw** [comment]
Removed `$XDG_CONFIG_HOME/.visidatarc` option.  @wavexx, hopefully this is not inconvenient for you.

**Comment by wavexx** [comment]
On Thu, Dec 28 2017, Saul Pwanson wrote:
> Removed $XDG_CONFIG_HOME/.visidatarc option. @wavexx, hopefully this
> is not inconvenient for you.

Fine with that.

But looking at the patch, I now notice that .visidatarc is also sourced
from the current directory.

I would *strongly* advise against that, since visidatarc allows code to
be run.

**Comment by saulpw** [comment]
@wavexx okay, that's a good point.  I've removed it from develop and will cherry-pick 691b21c to stable for 1.0.  Thanks for the advice.
