### ISSUE TITLE
[pyobj-show-hidden] Pyobj show hidden doesn't apply to current table

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#947]
**Small description**
 Pyobj show hidden doesn't apply immediately to current table

**Expected result**
`gv` in Pyobj shows hidden attributes and methods

**Actual result with screenshot**
https://asciinema.org/a/jtxaRz10aG58lFdX5mMzC7U5O

**Steps to reproduce with sample data and a .vd**
```
vd benchmark.csv
g^Y  - get to pyobj-sheet
gv   - show hidden
```

**Additional context**
Please include the version of VisiData. Latest develop version.

This is a minor issue.  Noticed this when trying to debug my other issues with colorizers.

Workaround: quit the table and return works, or changing visibility option ahead of time works.

Also, vd reports `no rows selected` 2 or more times when running the g^Y command. Even more minor, but might point to a real issue.

**Comment by anjakefala** [comment]
Hi @frosencrantz 

Believe it or not, the "no rows selected" was unrelated. It is because `onlySelectedRows` is a property, so the getattr results in it being "executed", and part of its execution is a `vd.fail` if no rows are selected. Down the line, we will consider what to do for that, but for now the bug is fixed on develop.

Thanks!

**Comment by frosencrantz** [comment]
This works for me know. Thanks Anja!  Great as always.

Thanks for looking explaining "no rows selected", that makes sense.
