### ISSUE TITLE
[splitwin]  Allow mouse to switch between splits.

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#954]
I've been trying the split window code, and it is feels more usable than before.  Great work! Thanks!

One thing that would make it more usable, is if the mouse could automatically focus the split clicked.
Now VisiData ignores mouse clicks outside the current split.

**Comment by anjakefala** [comment]
Hi @frosencrantz!

This was turned off because clicking in the non-active pane currently results in a `slide-col`. As in, a column will slide from one location to the location where the click is pressed. I am not quite sure why this is happening, which makes it hard to fix it.

I think a column randomly sliding would be more egregious than the non-active pane being not clickable, so I have turned off clicking for the non-active pane. 

This can be returned to after further investigating sliding, but I think that is going to be pretty time consuming and I am going to `wishlist` it for now.

**Comment by frosencrantz** [comment]
Thanks for investigating @anjakefala!  

When I do use the mouse it is mostly to get the cursor where I'm pointing.  TIL it is possible to move columns and rows around via the mouse.   That seems very useful, recently I was trying to move columns around a bit day, and slide-leght-n commands were tedious.

I do feel this request is one of those small details that adds polish to VisiData usability.    In no way blocking, but good to fix.  So I do hope someone is able to revisit someday.

**Comment by anjakefala** [comment]
This is on `develop` and will be in the next release. Thanks @saulpw! https://github.com/saulpw/visidata/pull/1112/commits/f2067485a264e62fa9e1a4c2eedf5d50fc1c3002
