### ISSUE TITLE
[wishlist modify] autosave feature

### ISSUE THREAD

**Issue by jvns** [saulpw/visidata#955]
I've been using VisiData to create and edit CSV files recently, and I really love it! I've been finding it a bit stressful to remember to save my work though, because (as far as I can tell) there's no indication that there have been edits to a sheet and there's no warning about unsaved changes when I quit a sheet that I've edited. I see there's an issue #483 about that already.

I've been working around this by using `vd --confirm-overwrite=false --quitguard`, which works pretty well.

I think it might be nice to have an autosave feature that makes VisiData act more like Google Sheets, where all changes get automatically committed as soon as you make them.

I [made a very brief attempt at implementing this](https://github.com/saulpw/visidata/compare/stable...jvns:autosave?expand=1), but the code doesn't work yet and I don't know if that approach is viable.

**Comment by saulpw** [comment]
Hi @jvns!  Thanks for the request.  I think we're on the verge of implementing some form of "modified" flag and corresponding quitguard functionality that only demands confirmation on quit if the sheet has been modified since last save.  Would this put you sufficiently at ease, or would you want the autosave feature also?

Interestingly, we did just implement an autosave feature for DarkDraw (a new VisiData plugin for drawing terminal art and animation), which saves every minute (configurable) to a dated file; more like an automated backup, or a way to save snapshots of the drawing process over time.  This approach was an easier sell for me because it wasn't overwriting the official file without the user doing it deliberately.

In my mind, losing data on disk is 100x worse than losing work you've done but haven't explicitly saved--at least then you know what work you have to redo.  We have very few tales of lost data (the last one was due to quitting before a sheet had finished saving), but I'm still paranoid from years of data wrangling; it can be so devastating if/when it does happen that I prefer to wear both a belt and suspenders even if it is a bit more inconvenient.

All this is to say that I'm moderately opposed to this request as stated, though I appreciate how convenient it would be (and I would take advantage of it myself), so I'm open to arguments and design angles to make it happen.  Maybe autosave could rename the existing source as a dated backup, before it saves the current version onto the "real" filename?  This might also be a good idea for save in general, even apart from autosave.

**Comment by jvns** [comment]
The modified flag / quitguard feature sounds awesome, I think that would solve my problem!

Renaming the existing source as a dated backup definitely seems safer (and maybe if someone was really not worried about data loss they could pass a `--no-backup-on-save` option).

Also definitely please close this if you don't think it's right for VisiData :)

**Comment by saulpw** [comment]
Okay, we're now [tracking modifications](https://github.com/saulpw/visidata/issues/844#issuecomment-856555840) in the `develop` branch.  Would you be willing to install from the develop branch (cutting edge!) and let me know how it feels?  I want you and other people to feel reasonably safe and secure using VisiData for data input.
