### ISSUE TITLE
Feature request: Additional aggregators

### ISSUE THREAD

**Issue by jsvine** [saulpw/visidata#96]
In v0.98.1, the aggregator options appear to be `min/max/avg/mean/sum/distinct/count/keymax`. Would be wonderful to have "median" as one of those options. Would be happy to file a PR, if you'd like.

**Comment by saulpw** [comment]
Yes, this is definitely reasonable.  The sample .visidatarc in the manpage shows how to define the median aggregator yourself, but you're right, it should be in there by default.  I've been putting it off because it seems like there should be more generic 1st/2nd/3rd quartile aggregators (with 2nd == median) but I haven't figured out how I want that to work yet.  I'll add median as a default, and it'll go in v0.99 (released by Dec 22nd).  I appreciate the offer to submit a PR, I'll take you up on that for a future feature for sure :)

**Comment by jsvine** [comment]
Ah, fantastic!

And percentile/quartile aggregators sound like a nice feature. I don't know if the VisiData internals would easily support this, but maybe a prefixed argument like `p25` and `p75`, where the characters following `p` could be any integer or float between 0 and 100?

**Comment by saulpw** [comment]
Hm, do you ever want such fine granularity like p37? It seems like you would either want quartiles, deciles, or percentiles, and that you'd want all of them if you did.  When would it make sense to use a specific decile or percentile?

**Comment by jsvine** [comment]
Good question! Most times, I'd probably just want (p50,), (p25, p50, p75), or (p10 ... p90), etc., but I could also imagine wanting (p20, p80), or possibly (p33, p67). To be sure, those scenarios are rarer than just wanting a simple set of quartiles, quintiles, or deciles.

**Comment by saulpw** [comment]
Sorry this took so long!  What I came up with is 'aggregator groups' for these predefined quantiles.   This adds `q3/q4/q5/q10` aggregator choices, which add (for e.g. `q3`) the `p33`/`p67` aggregators.  Other quantiles or percentiles can't be specified, though we can easily add others (or via`.visidatarc`).  See [the design brief](https://github.com/saulpw/visidata/blob/develop/dev/design/168.md).  This will be in v1.3.

Should we add `q2` as an alias for `median`?

**Comment by jsvine** [comment]
Sounds good, and thanks!

And I'm split on `q2`. (Pun not intended, but not avoided, either!) Might be nice to have, for symmetry's sake, but can also see the argument for avoiding redundant commands/options.
