### ISSUE TITLE
Is there way to change the default dot size?

### ISSUE THREAD

**Issue by albert-ying** [saulpw/visidata#963]
Hi, I found that the data points plotted are way too small, especially when I'm working with small/sparse datasets. Sometimes I can't even distinguish the dots from the dust on my monitor.

I'm wondering if there is a way to adjust the default dot size?

Thank you so much for this amazing tool!

Here is an extreme example with 5 data points, I still couldn't find all 5 points...

<img width="976" alt="image" src="https://user-images.githubusercontent.com/59846322/115944811-1b911d00-a486-11eb-8669-d18bd5f26375.png">

**Comment by saulpw** [comment]
The terminal plotting function uses braille characters and I've found it works best when graphing thousands of data points.  Maybe there is a braille font that has larger dots?

What do you use to plot graphs normally?

**Comment by albert-ying** [comment]
I use R, but it is just much easier to casually plot in Visidata -- it only takes a few keystrokes!  Is it possible to change the font size of braille characters? Or maybe more straightforward, use, say, multiple dot characters to represent one dot, as usually seen in pixel art.

I don't know how other people use this plotting function. But in my real-life work, I only use it to quickly check the dataset or peek at the correlation of variables (like the histogram function). In these scenarios, I usually do not have that many data points and I never really use it to plot large datasets or any serious plotting.  Maybe this is why I feel that the dots are too small.

**Comment by saulpw** [comment]
Okay @albert-ying, you've convinced me to make it configurable.  With the next release (or current latest develop), if you add this to your `.visidatarc`:

    options.disp_canvas_charset = ''

it will use a simple default of `' o'` so that any points on the graph become an `o`, which is hopefully big enough to see.  You can of course use a different character, just make sure that the first character is a space.  This option can also be configured more precisely if you want to vary the character by how many/which points are present, but I won't go into the specifics of that here.

Hopefully this helps you differentiate your dots from the dust on your screen!

**Comment by albert-ying** [comment]
Wow, this is the quickest fix I ever saw on Github. Thank you so much!
